// This file is auto-generated by @hey-api/openapi-ts
import {
  zAccountGetAccountInformationData,
  zAccountGetSsoTokenData,
  zAccountPostSequencesData,
  zAccountRegisterCompanyData,
  zAccountUpdateLicenseData,
  zAccountAddLicenseBillableData,
  zAccountantGetFeedsData,
  zAccountantPostFeedsData,
  zAccountantDeleteFeedsData,
  zAccountantGetIndexData,
  zAccountantPostConfirmData,
  zAccountantGetFileData,
  zCashbookInitializeCashbookData,
  zCashbookCloseCashbookData,
  zCashbookGetCashbookData,
  zCashbookGetCashbookEntriesData,
  zCashbookGetCashbooksData,
  zCashbookGetCashbookHistoryData,
  zCashbookPostCashbookEntryData,
  zDailyReceiptPostDailyReceiptBookEntryData,
  zDailyReceiptGetDailyReceiptEntryData,
  zDailyReceiptGetDailyReceiptBooksData,
  zDailyReceiptGetDailyReceiptBooks2Data,
  zDocumentGetDocumentsData,
  zDocumentPostDocumentData,
  zDocumentGetDocumentData,
  zEinvoiceGetRegistrationsData,
  zEinvoicePostRegistrationData,
  zEinvoiceDeleteRegistrationData,
  zEinvoiceGetRegistrationData,
  zEinvoicePatchEntityData,
  zEinvoicePostRegistrationIntegrationData,
  zEinvoiceDeleteRegistrationIntegrationData,
  zEinvoicePostSendData,
  zEinvoiceGetOrdersData,
  zEinvoiceGetFileData,
  zEinvoiceGetOrderData,
  zEinvoicePatchOrderData,
  zEinvoiceGetWebhooksData,
  zEinvoicePostWebhookData,
  zEinvoiceDeleteWebhooksData,
  zEinvoiceRefreshWebhookSecretData,
  zEinvoicePostKycInitiationData,
  zFileGetOrdersData,
  zFinancialTransactionPostImportFileData,
  zFinancialTransactionPostImportData,
  zFinancialTransactionGetBankTransactionsData,
  zGlAccountPostGlAccountData,
  zGlAccountPostGlAccountBulkData,
  zJournalPostGlAccountData,
  zMiscGetCompanySearchData,
  zMiscGetTypeCodesData,
  zMiscGetTranslationData,
  zOAuth2PostTokenData,
  zOAuth2PostTokenRevokeData,
  zOrderGetOrdersData,
  zOrderPostOrdersData,
  zOrderPutOrderBookingsData,
  zOrderDeleteOrderData,
  zOrderGetOrderData,
  zOrderPatchOrdersData,
  zOrderPostOrderPaymentData,
  zOrderPostSendData,
  zOrderESignOrderData,
  zOrderGetDeletedData,
  zPartyGetPartyData,
  zPartyPatchPartiesData,
  zPartyGetPartiesData,
  zPartyPostPartyData,
  zPeppolDeleteParticipantData,
  zPeppolPostParticipantData,
  zPeppolGetInboxData,
  zPeppolInboxItemConfirmData,
  zPeppolInboxItemRefuseData,
  zPeppolPostSendOrderData,
  zPeppolGetParticipantInformationData,
  zProductGetProductData,
  zProductGetProductsData,
  zProductPostProductData,
  zReportReportListGetData,
  zReportReportDetailGetData,
  zToProcessPostToProcessData,
  zToProcessDeleteToProcessData,
  zWebhookGetWebhooksData,
  zWebhookPostWebhookData,
  zWebhookDeleteWebhooksData,
  zWebhookRefreshWebhookSecretData,
} from './zod.gen';
import {
  accountGetAccountInformationResponseTransformer,
  cashbookGetCashbookResponseTransformer,
  cashbookGetCashbookEntriesResponseTransformer,
  cashbookGetCashbooksResponseTransformer,
  cashbookGetCashbookHistoryResponseTransformer,
  cashbookPostCashbookEntryResponseTransformer,
  dailyReceiptGetDailyReceiptBooksResponseTransformer,
  dailyReceiptGetDailyReceiptBooks2ResponseTransformer,
  documentGetDocumentsResponseTransformer,
  documentGetDocumentResponseTransformer,
  einvoiceGetOrdersResponseTransformer,
  einvoiceGetOrderResponseTransformer,
  miscGetCompanySearchResponseTransformer,
  orderGetOrdersResponseTransformer,
  orderGetOrderResponseTransformer,
  orderGetDeletedResponseTransformer,
  partyGetPartyResponseTransformer,
  partyGetPartiesResponseTransformer,
  peppolGetInboxResponseTransformer,
  productGetProductResponseTransformer,
  productGetProductsResponseTransformer,
} from './transformers.gen';
import { client as _heyApiClient } from './client.gen';
/**
 * Get account information about the current user
 */
export const accountGetAccountInformation = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zAccountGetAccountInformationData.parseAsync(data);
    },
    responseTransformer: accountGetAccountInformationResponseTransformer,
    url: '/v1/account/accountInformation',
    ...options,
  });
};
/**
 * Get an SSO token of the current user
 */
export const accountGetSsoToken = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zAccountGetSsoTokenData.parseAsync(data);
    },
    url: '/v1/account/ssoToken',
    ...options,
  });
};
/**
 * Update the sequence of a specific type
 */
export const accountPostSequences = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zAccountPostSequencesData.parseAsync(data);
    },
    url: '/v1/account/sequences',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Registers a Company in the Billit-ecosphere
 */
export const accountRegisterCompany = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zAccountRegisterCompanyData.parseAsync(data);
    },
    url: '/v1/account/registercompany',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Update the license
 */
export const accountUpdateLicense = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zAccountUpdateLicenseData.parseAsync(data);
    },
    url: '/v1/account/license',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Add new License Billable
 */
export const accountAddLicenseBillable = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zAccountAddLicenseBillableData.parseAsync(data);
    },
    url: '/v1/account/license/addons',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Get a list of all feeds to download
 */
export const accountantGetFeeds = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zAccountantGetFeedsData.parseAsync(data);
    },
    url: '/v1/accountant/feeds',
    ...options,
  });
};
/**
 * Register a new feed. All newly exported orders or documents will be available in this new feed.
 */
export const accountantPostFeeds = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zAccountantPostFeedsData.parseAsync(data);
    },
    url: '/v1/accountant/feeds',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Delete the feed
 */
export const accountantDeleteFeeds = options => {
  return (options.client ?? _heyApiClient).delete({
    requestValidator: async data => {
      return await zAccountantDeleteFeedsData.parseAsync(data);
    },
    url: '/v1/accountant/feeds/{feedName}',
    ...options,
  });
};
/**
 * Get A list of all feeds to download. Only query this once per minute
 */
export const accountantGetIndex = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zAccountantGetIndexData.parseAsync(data);
    },
    url: '/v1/accountant/feeds/{feedName}',
    ...options,
  });
};
/**
 * Confirm each succesfully downloaded feed item to remove it from the feedlist
 */
export const accountantPostConfirm = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zAccountantPostConfirmData.parseAsync(data);
    },
    url: '/v1/accountant/feeds/{feedName}/{feedItemID}/confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * download a coda file from the feed
 */
export const accountantGetFile = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zAccountantGetFileData.parseAsync(data);
    },
    url: '/v1/accountant/feeds/{feedName}/{feedItemID}',
    ...options,
  });
};
/**
 * Initialize the cash book for first use
 */
export const cashbookInitializeCashbook = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zCashbookInitializeCashbookData.parseAsync(data);
    },
    url: '/v1/Cashbook/Initialize',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Permanently close the cash book
 */
export const cashbookCloseCashbook = options => {
  return (options?.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zCashbookCloseCashbookData.parseAsync(data);
    },
    url: '/v1/Cashbook/Close',
    ...options,
  });
};
/**
 * Get the current active cash book
 */
export const cashbookGetCashbook = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zCashbookGetCashbookData.parseAsync(data);
    },
    responseTransformer: cashbookGetCashbookResponseTransformer,
    url: '/v1/Cashbook',
    ...options,
  });
};
/**
 * Get an overview of all the entries in the current active cash book
 */
export const cashbookGetCashbookEntries = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zCashbookGetCashbookEntriesData.parseAsync(data);
    },
    responseTransformer: cashbookGetCashbookEntriesResponseTransformer,
    url: '/v1/Cashbook/Entries',
    ...options,
  });
};
/**
 * Get an overview of all the closed cash books
 */
export const cashbookGetCashbooks = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zCashbookGetCashbooksData.parseAsync(data);
    },
    responseTransformer: cashbookGetCashbooksResponseTransformer,
    url: '/v1/Cashbook/History',
    ...options,
  });
};
/**
 * Get an overview of all the entries in a closed cash book
 */
export const cashbookGetCashbookHistory = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zCashbookGetCashbookHistoryData.parseAsync(data);
    },
    responseTransformer: cashbookGetCashbookHistoryResponseTransformer,
    url: '/v1/Cashbook/{cashbookID}/History',
    ...options,
  });
};
/**
 * Add an entry to the current active cash book
 */
export const cashbookPostCashbookEntry = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zCashbookPostCashbookEntryData.parseAsync(data);
    },
    responseTransformer: cashbookPostCashbookEntryResponseTransformer,
    url: '/v1/Cashbook/AddEntry',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Add a new daily receipt to a new or open daily receipt book
 */
export const dailyReceiptPostDailyReceiptBookEntry = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zDailyReceiptPostDailyReceiptBookEntryData.parseAsync(data);
    },
    url: '/v1/DailyReceiptBooks/commands/CreateEntryInOpenExistingOrNew',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Get a daily receipt entry
 */
export const dailyReceiptGetDailyReceiptEntry = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zDailyReceiptGetDailyReceiptEntryData.parseAsync(data);
    },
    url: '/v1/DailyReceiptBooks/DailyReceiptEntry/{DailyReceiptEntryID}',
    ...options,
  });
};
/**
 * Get a daily receipt book with details
 */
export const dailyReceiptGetDailyReceiptBooks = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zDailyReceiptGetDailyReceiptBooksData.parseAsync(data);
    },
    responseTransformer: dailyReceiptGetDailyReceiptBooksResponseTransformer,
    url: '/v1/DailyReceiptBooks/{DailyReceiptBookID}',
    ...options,
  });
};
/**
 * Get a daily receipt book list
 */
export const dailyReceiptGetDailyReceiptBooks2 = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zDailyReceiptGetDailyReceiptBooks2Data.parseAsync(data);
    },
    responseTransformer: dailyReceiptGetDailyReceiptBooks2ResponseTransformer,
    url: '/v1/DailyReceiptBooks',
    ...options,
  });
};
/**
 * Get a list of documents
 */
export const documentGetDocuments = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zDocumentGetDocumentsData.parseAsync(data);
    },
    responseTransformer: documentGetDocumentsResponseTransformer,
    url: '/v1/documents',
    ...options,
  });
};
/**
 * Save a document
 */
export const documentPostDocument = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zDocumentPostDocumentData.parseAsync(data);
    },
    url: '/v1/documents',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Get a document specified by the documentID
 */
export const documentGetDocument = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zDocumentGetDocumentData.parseAsync(data);
    },
    responseTransformer: documentGetDocumentResponseTransformer,
    url: '/v1/documents/{documentID}',
    ...options,
  });
};
/**
 * Retrieve all E-invoice registrations
 */
export const einvoiceGetRegistrations = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zEinvoiceGetRegistrationsData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations',
    ...options,
  });
};
/**
 * Create an E-invoice registration for a new entity
 */
export const einvoicePostRegistration = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zEinvoicePostRegistrationData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Delete a registration
 */
export const einvoiceDeleteRegistration = options => {
  return (options.client ?? _heyApiClient).delete({
    requestValidator: async data => {
      return await zEinvoiceDeleteRegistrationData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations/{registrationID}',
    ...options,
  });
};
/**
 * Retrieve an E-invoice registration
 */
export const einvoiceGetRegistration = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zEinvoiceGetRegistrationData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations/{registrationID}',
    ...options,
  });
};
/**
 * Update an E-invoice registration
 */
export const einvoicePatchEntity = options => {
  return (options.client ?? _heyApiClient).patch({
    requestValidator: async data => {
      return await zEinvoicePatchEntityData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations/{registrationID}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Activate a new integration
 */
export const einvoicePostRegistrationIntegration = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zEinvoicePostRegistrationIntegrationData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations/{registrationID}/integrations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Deactivate an integration
 */
export const einvoiceDeleteRegistrationIntegration = options => {
  return (options.client ?? _heyApiClient).delete({
    requestValidator: async data => {
      return await zEinvoiceDeleteRegistrationIntegrationData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations/{registrationID}/integrations/{integrationID}',
    ...options,
  });
};
/**
 * Create and send an E-document
 */
export const einvoicePostSend = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zEinvoicePostSendData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations/{registrationID}/commands/send',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Get a list of orders
 */
export const einvoiceGetOrders = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zEinvoiceGetOrdersData.parseAsync(data);
    },
    responseTransformer: einvoiceGetOrdersResponseTransformer,
    url: '/v1/einvoices/registrations/{registrationID}/orders',
    ...options,
  });
};
/**
 * Get a file specified by the fileID
 */
export const einvoiceGetFile = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zEinvoiceGetFileData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations/{registrationID}/files/{fileID}',
    ...options,
  });
};
/**
 * Get an order specified by the orderID
 */
export const einvoiceGetOrder = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zEinvoiceGetOrderData.parseAsync(data);
    },
    responseTransformer: einvoiceGetOrderResponseTransformer,
    url: '/v1/einvoices/registrations/{registrationID}/orders/{orderID}',
    ...options,
  });
};
/**
 * Patch an E-document
 */
export const einvoicePatchOrder = options => {
  return (options.client ?? _heyApiClient).patch({
    requestValidator: async data => {
      return await zEinvoicePatchOrderData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations/{registrationID}/orders/{orderID}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Get all webhooks
 */
export const einvoiceGetWebhooks = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zEinvoiceGetWebhooksData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations/{registrationID}/webhooks',
    ...options,
  });
};
/**
 * Create a webhook
 */
export const einvoicePostWebhook = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zEinvoicePostWebhookData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations/{registrationID}/webhooks',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Delete a webhook
 */
export const einvoiceDeleteWebhooks = options => {
  return (options.client ?? _heyApiClient).delete({
    requestValidator: async data => {
      return await zEinvoiceDeleteWebhooksData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations/{registrationID}/webhooks/{webhookID}',
    ...options,
  });
};
/**
 * Refresh an webhook secret
 */
export const einvoiceRefreshWebhookSecret = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zEinvoiceRefreshWebhookSecretData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations/{registrationID}/webhooks/refresh/{webhookID}',
    ...options,
  });
};
/**
 * Initiate a KYC procedure
 */
export const einvoicePostKycInitiation = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zEinvoicePostKycInitiationData.parseAsync(data);
    },
    url: '/v1/einvoices/registrations/{registrationID}/identification',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Get a file specified by the fileID
 */
export const fileGetOrders = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zFileGetOrdersData.parseAsync(data);
    },
    url: '/v1/files/{fileID}',
    ...options,
  });
};
/**
 * Upload a coda file and import the transactions
 */
export const financialTransactionPostImportFile = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zFinancialTransactionPostImportFileData.parseAsync(data);
    },
    url: '/v1/financialTransactions/importFile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Create transactions using a list
 */
export const financialTransactionPostImport = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zFinancialTransactionPostImportData.parseAsync(data);
    },
    url: '/v1/financialTransactions/commands/import',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
export const financialTransactionGetBankTransactions = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zFinancialTransactionGetBankTransactionsData.parseAsync(data);
    },
    url: '/v1/financialTransactions',
    ...options,
  });
};
/**
 * Create a general ledger account
 */
export const glAccountPostGlAccount = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zGlAccountPostGlAccountData.parseAsync(data);
    },
    url: '/v1/glaccounts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Create multiple general ledger accounts using a list
 */
export const glAccountPostGlAccountBulk = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zGlAccountPostGlAccountBulkData.parseAsync(data);
    },
    url: '/v1/glaccounts/commands/import',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Import a list of journals
 */
export const journalPostGlAccount = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zJournalPostGlAccountData.parseAsync(data);
    },
    url: '/v1/journals/commands/import',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Search for parties/companies based on a keyword
 */
export const miscGetCompanySearch = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zMiscGetCompanySearchData.parseAsync(data);
    },
    responseTransformer: miscGetCompanySearchResponseTransformer,
    url: '/v1/misc/companysearch/{Keywords}',
    ...options,
  });
};
/**
 * Get all translations of a specified TypeCode
 */
export const miscGetTypeCodes = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zMiscGetTypeCodesData.parseAsync(data);
    },
    url: '/v1/misc/typecodes/{TypeCodeType}',
    ...options,
  });
};
/**
 * Get a translations of a key of a typecode, optionally in a specified language
 */
export const miscGetTranslation = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zMiscGetTranslationData.parseAsync(data);
    },
    url: '/v1/misc/typecodes/{TypeCodeType}/{key}/{language}',
    ...options,
  });
};
export const oAuth2PostToken = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zOAuth2PostTokenData.parseAsync(data);
    },
    url: '/OAuth2/token',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
export const oAuth2PostTokenRevoke = options => {
  return (options?.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zOAuth2PostTokenRevokeData.parseAsync(data);
    },
    url: '/OAuth2/revoke',
    ...options,
  });
};
/**
 * Get a list of invoices/credit notes/order/...
 */
export const orderGetOrders = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zOrderGetOrdersData.parseAsync(data);
    },
    responseTransformer: orderGetOrdersResponseTransformer,
    url: '/v1/orders',
    ...options,
  });
};
/**
 * Create a new order or update an existing one
 */
export const orderPostOrders = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zOrderPostOrdersData.parseAsync(data);
    },
    url: '/v1/orders',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Add a booking lines collection
 */
export const orderPutOrderBookings = options => {
  return (options.client ?? _heyApiClient).put({
    requestValidator: async data => {
      return await zOrderPutOrderBookingsData.parseAsync(data);
    },
    url: '/v1/orders/{orderID}/bookingEntries',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Delete a specific order
 */
export const orderDeleteOrder = options => {
  return (options.client ?? _heyApiClient).delete({
    requestValidator: async data => {
      return await zOrderDeleteOrderData.parseAsync(data);
    },
    url: '/v1/orders/{orderID}',
    ...options,
  });
};
/**
 * Get a specific order
 */
export const orderGetOrder = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zOrderGetOrderData.parseAsync(data);
    },
    responseTransformer: orderGetOrderResponseTransformer,
    url: '/v1/orders/{orderID}',
    ...options,
  });
};
/**
 * Patch an order
 */
export const orderPatchOrders = options => {
  return (options.client ?? _heyApiClient).patch({
    requestValidator: async data => {
      return await zOrderPatchOrdersData.parseAsync(data);
    },
    url: '/v1/orders/{orderID}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Add a partial or full payment to an order
 */
export const orderPostOrderPayment = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zOrderPostOrderPaymentData.parseAsync(data);
    },
    url: '/v1/orders/{orderID}/payments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Send a list of orders via a specified channel
 */
export const orderPostSend = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zOrderPostSendData.parseAsync(data);
    },
    url: '/v1/orders/commands/send',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * E-Sign an order
 */
export const orderESignOrder = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zOrderESignOrderData.parseAsync(data);
    },
    url: '/v1/orders/commands/eSign/{orderID}',
    ...options,
  });
};
/**
 * Get a list of deleted orders
 */
export const orderGetDeleted = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zOrderGetDeletedData.parseAsync(data);
    },
    responseTransformer: orderGetDeletedResponseTransformer,
    url: '/v1/orders/deleted',
    ...options,
  });
};
/**
 * Get a party specified by the partyID
 */
export const partyGetParty = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zPartyGetPartyData.parseAsync(data);
    },
    responseTransformer: partyGetPartyResponseTransformer,
    url: '/v1/parties/{partyID}',
    ...options,
  });
};
/**
 * Patch Party Properties. NavigationProperties are not supported.
 */
export const partyPatchParties = options => {
  return (options.client ?? _heyApiClient).patch({
    requestValidator: async data => {
      return await zPartyPatchPartiesData.parseAsync(data);
    },
    url: '/v1/parties/{partyID}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Get a list of customers or suppliers
 */
export const partyGetParties = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zPartyGetPartiesData.parseAsync(data);
    },
    responseTransformer: partyGetPartiesResponseTransformer,
    url: '/v1/parties',
    ...options,
  });
};
/**
 * Create a new party or update an existing one
 */
export const partyPostParty = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zPartyPostPartyData.parseAsync(data);
    },
    url: '/v1/parties',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Delete a Peppol registration for a specific company
 */
export const peppolDeleteParticipant = options => {
  return (options.client ?? _heyApiClient).delete({
    requestValidator: async data => {
      return await zPeppolDeleteParticipantData.parseAsync(data);
    },
    url: '/v1/peppol/participants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Create a new Peppol registration for a specific company
 */
export const peppolPostParticipant = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zPeppolPostParticipantData.parseAsync(data);
    },
    url: '/v1/peppol/participants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Lists the first 10 peppol items in the inbox. Use the file api to download the actual message. Use the confirm or refuse endpoint to remove it from the queue
 */
export const peppolGetInbox = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zPeppolGetInboxData.parseAsync(data);
    },
    responseTransformer: peppolGetInboxResponseTransformer,
    url: '/v1/peppol/inbox',
    ...options,
  });
};
/**
 * Confirm an inbox item and remove it from the queue
 */
export const peppolInboxItemConfirm = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zPeppolInboxItemConfirmData.parseAsync(data);
    },
    url: '/v1/peppol/inbox/{inboxItemId}/confirm',
    ...options,
  });
};
/**
 * Refuse an inbox item and remove it from the queue
 */
export const peppolInboxItemRefuse = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zPeppolInboxItemRefuseData.parseAsync(data);
    },
    url: '/v1/peppol/inbox/{inboxItemId}/refuse',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Send a direct Peppol message. Compatible with receivers that support Invoice5, Creditnote5, BisV3 Invoice or BisV3 Creditnote
 */
export const peppolPostSendOrder = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zPeppolPostSendOrderData.parseAsync(data);
    },
    url: '/v1/peppol/sendOrder',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Get Peppol participant information. API key is not required
 */
export const peppolGetParticipantInformation = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zPeppolGetParticipantInformationData.parseAsync(data);
    },
    url: '/v1/peppol/participantInformation/{VATorCBE}',
    ...options,
  });
};
/**
 * Get a specific product
 */
export const productGetProduct = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zProductGetProductData.parseAsync(data);
    },
    responseTransformer: productGetProductResponseTransformer,
    url: '/v1/products/{productID}',
    ...options,
  });
};
/**
 * Get a list of products
 */
export const productGetProducts = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zProductGetProductsData.parseAsync(data);
    },
    responseTransformer: productGetProductsResponseTransformer,
    url: '/v1/products',
    ...options,
  });
};
/**
 * Create a new product or update an existing one
 */
export const productPostProduct = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zProductPostProductData.parseAsync(data);
    },
    url: '/v1/products',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Get a list of available reports for the current user
 */
export const reportReportListGet = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zReportReportListGetData.parseAsync(data);
    },
    url: '/v1/reports',
    ...options,
  });
};
/**
 * Get the result and name of the report specified by the reportID
 */
export const reportReportDetailGet = options => {
  return (options.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zReportReportDetailGetData.parseAsync(data);
    },
    url: '/v1/reports/{reportID}',
    ...options,
  });
};
/**
 * Save a new document to process
 */
export const toProcessPostToProcess = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zToProcessPostToProcessData.parseAsync(data);
    },
    url: '/v1/toProcess',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Delete a document to process
 */
export const toProcessDeleteToProcess = options => {
  return (options.client ?? _heyApiClient).delete({
    requestValidator: async data => {
      return await zToProcessDeleteToProcessData.parseAsync(data);
    },
    url: '/v1/toProcess/{uploadID}',
    ...options,
  });
};
/**
 * Get all webhooks
 */
export const webhookGetWebhooks = options => {
  return (options?.client ?? _heyApiClient).get({
    requestValidator: async data => {
      return await zWebhookGetWebhooksData.parseAsync(data);
    },
    url: '/v1/webhooks',
    ...options,
  });
};
/**
 * Create a webhook
 * Sample request:
 *
 * POST /v1/webhooks
 * {
 * "EntityType": "Order",
 * "WebhookURL": "https://my.Webhook.url.com/Callback"
 * }
 */
export const webhookPostWebhook = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zWebhookPostWebhookData.parseAsync(data);
    },
    url: '/v1/webhooks',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
/**
 * Delete a webhook
 */
export const webhookDeleteWebhooks = options => {
  return (options.client ?? _heyApiClient).delete({
    requestValidator: async data => {
      return await zWebhookDeleteWebhooksData.parseAsync(data);
    },
    url: '/v1/webhooks/{webhookID}',
    ...options,
  });
};
/**
 * Refresh a webhook secret
 */
export const webhookRefreshWebhookSecret = options => {
  return (options.client ?? _heyApiClient).post({
    requestValidator: async data => {
      return await zWebhookRefreshWebhookSecretData.parseAsync(data);
    },
    url: '/v1/webhooks/refresh/{webhookID}',
    ...options,
  });
};
