// This file is auto-generated by @hey-api/openapi-ts
const accountInformationPartySchemaResponseTransformer = (data) => {
    if (data.BookYearStart) {
        data.BookYearStart = new Date(data.BookYearStart);
    }
    if (data.LastModified) {
        data.LastModified = new Date(data.LastModified);
    }
    if (data.Created) {
        data.Created = new Date(data.Created);
    }
    if (data.GLAccountCode) {
        data.GLAccountCode = BigInt(data.GLAccountCode.toString());
    }
    if (data.DomiciliationMandateSigningDate) {
        data.DomiciliationMandateSigningDate = new Date(data.DomiciliationMandateSigningDate);
    }
    if (data.GLDefaultExpiryOffset) {
        data.GLDefaultExpiryOffset = BigInt(data.GLDefaultExpiryOffset.toString());
    }
    return data;
};
const accountInformationSchemaResponseTransformer = (data) => {
    if (data.Companies) {
        data.Companies = data.Companies.map((item) => {
            return accountInformationPartySchemaResponseTransformer(item);
        });
    }
    return data;
};
export const accountGetAccountInformationResponseTransformer = async (data) => {
    data = accountInformationSchemaResponseTransformer(data);
    return data;
};
const cashbookModelSchemaResponseTransformer = (data) => {
    if (data.CreationDate) {
        data.CreationDate = new Date(data.CreationDate);
    }
    if (data.LastEntryDate) {
        data.LastEntryDate = new Date(data.LastEntryDate);
    }
    return data;
};
export const cashbookGetCashbookResponseTransformer = async (data) => {
    data = cashbookModelSchemaResponseTransformer(data);
    return data;
};
const cashbookEntrySchemaResponseTransformer = (data) => {
    if (data.TransactionDate) {
        data.TransactionDate = new Date(data.TransactionDate);
    }
    return data;
};
const pageResultCashbookEntrySchemaResponseTransformer = (data) => {
    if (data.Items) {
        data.Items = data.Items.map((item) => {
            return cashbookEntrySchemaResponseTransformer(item);
        });
    }
    if (data.Count) {
        data.Count = BigInt(data.Count.toString());
    }
    return data;
};
export const cashbookGetCashbookEntriesResponseTransformer = async (data) => {
    data = pageResultCashbookEntrySchemaResponseTransformer(data);
    return data;
};
export const cashbookGetCashbooksResponseTransformer = async (data) => {
    data = data.map((item) => {
        return cashbookModelSchemaResponseTransformer(item);
    });
    return data;
};
export const cashbookGetCashbookHistoryResponseTransformer = async (data) => {
    data = pageResultCashbookEntrySchemaResponseTransformer(data);
    return data;
};
export const cashbookPostCashbookEntryResponseTransformer = async (data) => {
    data = cashbookEntrySchemaResponseTransformer(data);
    return data;
};
const cashbookSchemaResponseTransformer = (data) => {
    if (data.FromDate) {
        data.FromDate = new Date(data.FromDate);
    }
    return data;
};
const dailyReceiptBookModelResponseModelSchemaResponseTransformer = (data) => {
    if (data.Cashbooks) {
        data.Cashbooks = data.Cashbooks.map((item) => {
            return cashbookSchemaResponseTransformer(item);
        });
    }
    return data;
};
export const dailyReceiptGetDailyReceiptBooksResponseTransformer = async (data) => {
    data = dailyReceiptBookModelResponseModelSchemaResponseTransformer(data);
    return data;
};
export const dailyReceiptGetDailyReceiptBooks2ResponseTransformer = async (data) => {
    data = dailyReceiptBookModelResponseModelSchemaResponseTransformer(data);
    return data;
};
const documentApiViewSchemaResponseTransformer = (data) => {
    if (data.DocumentDate) {
        data.DocumentDate = new Date(data.DocumentDate);
    }
    if (data.CreationDate) {
        data.CreationDate = new Date(data.CreationDate);
    }
    return data;
};
const pageResultDocumentApiViewSchemaResponseTransformer = (data) => {
    if (data.Items) {
        data.Items = data.Items.map((item) => {
            return documentApiViewSchemaResponseTransformer(item);
        });
    }
    if (data.Count) {
        data.Count = BigInt(data.Count.toString());
    }
    return data;
};
export const documentGetDocumentsResponseTransformer = async (data) => {
    data = pageResultDocumentApiViewSchemaResponseTransformer(data);
    return data;
};
export const documentGetDocumentResponseTransformer = async (data) => {
    data = documentApiViewSchemaResponseTransformer(data);
    return data;
};
const partySchemaResponseTransformer = (data) => {
    if (data.BookYearStart) {
        data.BookYearStart = new Date(data.BookYearStart);
    }
    if (data.LastModified) {
        data.LastModified = new Date(data.LastModified);
    }
    if (data.Created) {
        data.Created = new Date(data.Created);
    }
    if (data.GLAccountCode) {
        data.GLAccountCode = BigInt(data.GLAccountCode.toString());
    }
    if (data.DomiciliationMandateSigningDate) {
        data.DomiciliationMandateSigningDate = new Date(data.DomiciliationMandateSigningDate);
    }
    if (data.GLDefaultExpiryOffset) {
        data.GLDefaultExpiryOffset = BigInt(data.GLDefaultExpiryOffset.toString());
    }
    return data;
};
const documentDeliveryDetailsSchemaResponseTransformer = (data) => {
    if (data.DocumentRefusedDate) {
        data.DocumentRefusedDate = new Date(data.DocumentRefusedDate);
    }
    if (data.DocumentDeliveryDate) {
        data.DocumentDeliveryDate = new Date(data.DocumentDeliveryDate);
    }
    return data;
};
const orderMessageSchemaResponseTransformer = (data) => {
    if (data.CreationDate) {
        data.CreationDate = new Date(data.CreationDate);
    }
    return data;
};
const timezoneInfoSchemaResponseTransformer = (data) => {
    if (data.DateTime) {
        data.DateTime = new Date(data.DateTime);
    }
    return data;
};
const eInvoiceSignatureModelSchemaResponseTransformer = (data) => {
    if (data.DateTimeInfo) {
        data.DateTimeInfo = timezoneInfoSchemaResponseTransformer(data.DateTimeInfo);
    }
    return data;
};
const orderSchemaResponseTransformer = (data) => {
    if (data.Customer) {
        data.Customer = partySchemaResponseTransformer(data.Customer);
    }
    if (data.Supplier) {
        data.Supplier = partySchemaResponseTransformer(data.Supplier);
    }
    if (data.CounterParty) {
        data.CounterParty = partySchemaResponseTransformer(data.CounterParty);
    }
    if (data.OrderDate) {
        data.OrderDate = new Date(data.OrderDate);
    }
    if (data.ExpiryDate) {
        data.ExpiryDate = new Date(data.ExpiryDate);
    }
    if (data.LastModified) {
        data.LastModified = new Date(data.LastModified);
    }
    if (data.Created) {
        data.Created = new Date(data.Created);
    }
    if (data.PaymentDiscountDate) {
        data.PaymentDiscountDate = new Date(data.PaymentDiscountDate);
    }
    if (data.PaidDate) {
        data.PaidDate = new Date(data.PaidDate);
    }
    if (data.PeriodFrom) {
        data.PeriodFrom = new Date(data.PeriodFrom);
    }
    if (data.PeriodTill) {
        data.PeriodTill = new Date(data.PeriodTill);
    }
    if (data.LastReminder) {
        data.LastReminder = new Date(data.LastReminder);
    }
    if (data.DeliveryDate) {
        data.DeliveryDate = new Date(data.DeliveryDate);
    }
    if (data.CurrentDocumentDeliveryDetails) {
        data.CurrentDocumentDeliveryDetails = documentDeliveryDetailsSchemaResponseTransformer(data.CurrentDocumentDeliveryDetails);
    }
    if (data.Messages) {
        data.Messages = data.Messages.map((item) => {
            return orderMessageSchemaResponseTransformer(item);
        });
    }
    if (data.TaxPointDate) {
        data.TaxPointDate = new Date(data.TaxPointDate);
    }
    if (data.Signature) {
        data.Signature = eInvoiceSignatureModelSchemaResponseTransformer(data.Signature);
    }
    return data;
};
const pageResultOrderSchemaResponseTransformer = (data) => {
    if (data.Items) {
        data.Items = data.Items.map((item) => {
            return orderSchemaResponseTransformer(item);
        });
    }
    if (data.Count) {
        data.Count = BigInt(data.Count.toString());
    }
    return data;
};
export const einvoiceGetOrdersResponseTransformer = async (data) => {
    data = pageResultOrderSchemaResponseTransformer(data);
    return data;
};
export const einvoiceGetOrderResponseTransformer = async (data) => {
    data = orderSchemaResponseTransformer(data);
    return data;
};
const companySearchResultItemSchemaResponseTransformer = (data) => {
    if (data.StartDate) {
        data.StartDate = new Date(data.StartDate);
    }
    return data;
};
const companySearchResultSchemaResponseTransformer = (data) => {
    if (data.Items) {
        data.Items = data.Items.map((item) => {
            return companySearchResultItemSchemaResponseTransformer(item);
        });
    }
    return data;
};
export const miscGetCompanySearchResponseTransformer = async (data) => {
    data = companySearchResultSchemaResponseTransformer(data);
    return data;
};
export const orderGetOrdersResponseTransformer = async (data) => {
    data = pageResultOrderSchemaResponseTransformer(data);
    return data;
};
export const orderGetOrderResponseTransformer = async (data) => {
    data = orderSchemaResponseTransformer(data);
    return data;
};
export const orderGetDeletedResponseTransformer = async (data) => {
    data = pageResultOrderSchemaResponseTransformer(data);
    return data;
};
export const partyGetPartyResponseTransformer = async (data) => {
    data = partySchemaResponseTransformer(data);
    return data;
};
const pageResultPartySchemaResponseTransformer = (data) => {
    if (data.Items) {
        data.Items = data.Items.map((item) => {
            return partySchemaResponseTransformer(item);
        });
    }
    if (data.Count) {
        data.Count = BigInt(data.Count.toString());
    }
    return data;
};
export const partyGetPartiesResponseTransformer = async (data) => {
    data = pageResultPartySchemaResponseTransformer(data);
    return data;
};
const inboxGetResultItemSchemaResponseTransformer = (data) => {
    if (data.CreationDate) {
        data.CreationDate = new Date(data.CreationDate);
    }
    return data;
};
const inboxGetResultSchemaResponseTransformer = (data) => {
    if (data.InboxItems) {
        data.InboxItems = data.InboxItems.map((item) => {
            return inboxGetResultItemSchemaResponseTransformer(item);
        });
    }
    return data;
};
export const peppolGetInboxResponseTransformer = async (data) => {
    data = inboxGetResultSchemaResponseTransformer(data);
    return data;
};
const productSchemaResponseTransformer = (data) => {
    if (data.Created) {
        data.Created = new Date(data.Created);
    }
    if (data.LastModified) {
        data.LastModified = new Date(data.LastModified);
    }
    if (data.ChildProducts) {
        data.ChildProducts = data.ChildProducts.map((item) => {
            return productSchemaResponseTransformer(item);
        });
    }
    return data;
};
export const productGetProductResponseTransformer = async (data) => {
    data = productSchemaResponseTransformer(data);
    return data;
};
const pageResultProductSchemaResponseTransformer = (data) => {
    if (data.Items) {
        data.Items = data.Items.map((item) => {
            return productSchemaResponseTransformer(item);
        });
    }
    if (data.Count) {
        data.Count = BigInt(data.Count.toString());
    }
    return data;
};
export const productGetProductsResponseTransformer = async (data) => {
    data = pageResultProductSchemaResponseTransformer(data);
    return data;
};
