// This file is auto-generated by @hey-api/openapi-ts
import { z } from "zod";
export const zApiEnabledFeatures = z.object({
    TimeRegistration: z.optional(z.boolean()),
    Projects: z.optional(z.boolean()),
    DailyReceipts: z.optional(z.boolean()),
    FinancialReduction: z.optional(z.boolean()),
    GLAccounts: z.optional(z.boolean()),
    Cashbook: z.optional(z.boolean()),
});
export const zPartyAddress = z.object({
    AddressType: z.optional(z.string()),
    Tav: z.optional(z.string()),
    Name: z.optional(z.string()),
    Street: z.optional(z.string()),
    StreetNumber: z.optional(z.string()),
    Box: z.optional(z.string()),
    Zipcode: z.optional(z.string()),
    City: z.optional(z.string()),
    CountryCode: z.optional(z.string()),
    Phone: z.optional(z.string()),
});
export const zMutableKeyValuePairStringString = z.object({
    Key: z.optional(z.string()),
    Value: z.optional(z.string()),
});
export const zBankAccount = z.object({
    IBAN: z.optional(z.string()),
    BIC: z.optional(z.string()),
    Currency: z.optional(z.string()),
    Verified: z.optional(z.boolean()),
    Name: z.optional(z.string()),
    Saldo: z.optional(z.number()),
    ExternalProviderID: z.optional(z.string()),
    LogoFileID: z.optional(z.uuid()),
    LogoFileUrl: z.optional(z.string()),
    CountryCode: z.optional(z.string()),
    BankAccountName: z.optional(z.string()),
    BankProviderStatus: z.optional(z.string()),
    AccountIdentification: z.optional(z.string()),
    Active: z.optional(z.boolean()),
});
export const zUserCoreInfo = z.object({
    FirstName: z.optional(z.string()),
    LastName: z.optional(z.string()),
    Role: z.optional(z.string()),
    ExternalProviderID: z.optional(z.string()),
});
export const zPartyIdentifier = z.object({
    IdentifierType: z.optional(z.string()),
    Identifier: z.optional(z.string()),
    SchemeID: z.optional(z.string()),
    Preferred: z.optional(z.boolean()),
});
export const zAccountInformationParty = z.object({
    TabNameAlias: z.optional(z.string()),
    APIAllowed: z.optional(z.boolean()),
    LogoFileID: z.optional(z.uuid()),
    APIEnabledFeatures: z.optional(zApiEnabledFeatures),
    UserLanguage: z.optional(z.string()),
    PartyID: z.optional(z.int()),
    BookYearStart: z.optional(z.iso.datetime()),
    Nr: z.optional(z.string()),
    Name: z.optional(z.string()),
    CommercialName: z.optional(z.string()),
    Addresses: z.optional(z.array(zPartyAddress)),
    Street: z.optional(z.string()),
    StreetNumber: z.optional(z.string()),
    Box: z.optional(z.string()),
    Zipcode: z.optional(z.string()),
    CostCategoryCode: z.optional(z.int()),
    AccountingCostTypeName: z.optional(z.string()),
    City: z.optional(z.string()),
    CountryCode: z.optional(z.string()),
    IBAN: z.optional(z.string()),
    BIC: z.optional(z.string()),
    Mobile: z.optional(z.string()),
    Phone: z.optional(z.string()),
    Fax: z.optional(z.string()),
    Email: z.optional(z.string()),
    Website: z.optional(z.string()),
    Contact: z.optional(z.string()),
    ContactFirstName: z.optional(z.string()),
    ContactLastName: z.optional(z.string()),
    VATNumber: z.optional(z.string()),
    PeppolIdentifier: z.optional(z.string()),
    RPR: z.optional(z.string()),
    LastModified: z.optional(z.iso.datetime()),
    Created: z.optional(z.iso.datetime()),
    PartyType: z.optional(z.enum(["Customer", "Supplier"])),
    VATLiable: z.optional(z.boolean()),
    AccountantCode: z.optional(z.int()),
    GLAccountCode: z.optional(z.coerce.bigint()),
    Language: z.optional(z.string()),
    VentilationCode: z.optional(z.string()),
    ExternalProviderID: z.optional(z.string()),
    ExternalProviderTC: z.optional(z.string()),
    CustomFields: z.optional(z.array(zMutableKeyValuePairStringString)),
    BankAccounts: z.optional(z.array(zBankAccount)),
    Users: z.optional(z.array(zUserCoreInfo)),
    DefaultPaymentMethodTC: z.optional(z.string()),
    DomiciliationMandateID: z.optional(z.string()),
    DomiciliationMandateSigningDate: z.optional(z.iso.datetime()),
    DefaultPaid: z.optional(z.boolean()),
    DisplayName: z.optional(z.string()),
    DefaultTransportTypeTC: z.optional(z.string()),
    FinancialReductionPercentageDefault: z.optional(z.number()),
    FinancialReductionDaysDefault: z.optional(z.int()),
    DefaultExpiryOffset: z.optional(z.int()),
    GLDefaultExpiryOffset: z.optional(z.coerce.bigint()),
    Role: z.optional(z.string()),
    InternalInfo: z.optional(z.string()),
    VATDeductable: z.optional(z.boolean()),
    DefaultReductionPercentage: z.optional(z.number()),
    Identifiers: z.optional(z.array(zPartyIdentifier)),
    BookCategoryTC: z.optional(z.string()),
    SmallEnterprise: z.optional(z.boolean()),
    AutoSendInvoiceReminders: z.optional(z.boolean()),
    DefaultCurrencyTC: z.optional(z.string()),
    Regime: z.optional(z.string()),
    SubRegime: z.optional(z.string()),
    IsHighRisk: z.optional(z.boolean()),
    SendUBL: z.optional(z.boolean()),
    SendPDF: z.optional(z.boolean()),
});
export const zUserCompanyRole = z.object({
    PartyID: z.optional(z.int()),
    UserRoleTypes: z.optional(z.array(z.string())),
});
export const zAccountInformation = z.object({
    Email: z.optional(z.string()),
    Companies: z.optional(z.array(zAccountInformationParty)),
    UserCompanyRoles: z.optional(z.array(zUserCompanyRole)),
    ExternalProviderID: z.optional(z.string()),
    ExternalProviderTC: z.optional(z.string()),
    FirstName: z.optional(z.string()),
    LastName: z.optional(z.string()),
    LoginOrRegisterNeeded: z.optional(z.boolean()),
    NationalIdentityNumber: z.optional(z.string()),
    CardNumber: z.optional(z.string()),
    PhoneNumber: z.optional(z.string()),
    UniqueReference: z.optional(z.string()),
});
export const zSequenceRequest = z.object({
    SequenceType: z.optional(z.string()),
    Consume: z.optional(z.boolean()),
});
export const zParty = z.object({
    PartyID: z.optional(z.int()),
    BookYearStart: z.optional(z.iso.datetime()),
    Nr: z.optional(z.string()),
    Name: z.optional(z.string()),
    CommercialName: z.optional(z.string()),
    Addresses: z.optional(z.array(zPartyAddress)),
    Street: z.optional(z.string()),
    StreetNumber: z.optional(z.string()),
    Box: z.optional(z.string()),
    Zipcode: z.optional(z.string()),
    CostCategoryCode: z.optional(z.int()),
    AccountingCostTypeName: z.optional(z.string()),
    City: z.optional(z.string()),
    CountryCode: z.optional(z.string()),
    IBAN: z.optional(z.string()),
    BIC: z.optional(z.string()),
    Mobile: z.optional(z.string()),
    Phone: z.optional(z.string()),
    Fax: z.optional(z.string()),
    Email: z.optional(z.string()),
    Website: z.optional(z.string()),
    Contact: z.optional(z.string()),
    ContactFirstName: z.optional(z.string()),
    ContactLastName: z.optional(z.string()),
    VATNumber: z.optional(z.string()),
    PeppolIdentifier: z.optional(z.string()),
    RPR: z.optional(z.string()),
    LastModified: z.optional(z.iso.datetime()),
    Created: z.optional(z.iso.datetime()),
    PartyType: z.optional(z.enum(["Customer", "Supplier"])),
    VATLiable: z.optional(z.boolean()),
    AccountantCode: z.optional(z.int()),
    GLAccountCode: z.optional(z.coerce.bigint()),
    Language: z.optional(z.string()),
    VentilationCode: z.optional(z.string()),
    ExternalProviderID: z.optional(z.string()),
    ExternalProviderTC: z.optional(z.string()),
    CustomFields: z.optional(z.array(zMutableKeyValuePairStringString)),
    BankAccounts: z.optional(z.array(zBankAccount)),
    Users: z.optional(z.array(zUserCoreInfo)),
    DefaultPaymentMethodTC: z.optional(z.string()),
    DomiciliationMandateID: z.optional(z.string()),
    DomiciliationMandateSigningDate: z.optional(z.iso.datetime()),
    DefaultPaid: z.optional(z.boolean()),
    DisplayName: z.optional(z.string()),
    DefaultTransportTypeTC: z.optional(z.string()),
    FinancialReductionPercentageDefault: z.optional(z.number()),
    FinancialReductionDaysDefault: z.optional(z.int()),
    DefaultExpiryOffset: z.optional(z.int()),
    GLDefaultExpiryOffset: z.optional(z.coerce.bigint()),
    Role: z.optional(z.string()),
    InternalInfo: z.optional(z.string()),
    VATDeductable: z.optional(z.boolean()),
    DefaultReductionPercentage: z.optional(z.number()),
    Identifiers: z.optional(z.array(zPartyIdentifier)),
    BookCategoryTC: z.optional(z.string()),
    SmallEnterprise: z.optional(z.boolean()),
    AutoSendInvoiceReminders: z.optional(z.boolean()),
    DefaultCurrencyTC: z.optional(z.string()),
    Regime: z.optional(z.string()),
    SubRegime: z.optional(z.string()),
    IsHighRisk: z.optional(z.boolean()),
    SendUBL: z.optional(z.boolean()),
    SendPDF: z.optional(z.boolean()),
});
export const zAccountSettings = z.object({
    BulkInputFastForward: z.optional(z.boolean()),
    SendPeppolInvoiceReceivedMail: z.optional(z.boolean()),
    ExternalLicenseID: z.optional(z.string()),
    BulkInputIncomeUBLFastForward: z.optional(z.boolean()),
    ProcessUBLPrePaidAmount: z.optional(z.boolean()),
});
export const zLicenseAddons = z.object({
    AmountOfExtraUsers: z.optional(z.int()),
    AmountOfExtraDocuments: z.optional(z.int()),
});
export const zLicenseConfiguration = z.object({
    LicenseID: z.optional(z.int()),
    PeriodID: z.optional(z.int()),
    Addons: z.optional(zLicenseAddons),
});
export const zRegisterAccountRequestModel = z.object({
    Company: z.optional(zParty),
    AccountSettings: z.optional(zAccountSettings),
    License: z.optional(zLicenseConfiguration),
});
export const zUserIdBundle = z.object({
    UserID: z.optional(z.int()),
    ExternalProviderID: z.optional(z.string()),
});
export const zBankAccountState = z.object({
    BankAccountID: z.optional(z.int()),
    IBAN: z.optional(z.string()),
    BankAccountName: z.optional(z.string()),
    Active: z.optional(z.boolean()),
});
export const zRegisterAccountResponse = z.object({
    CompanyID: z.optional(z.int()),
    APIKey: z.optional(z.uuid()),
    Users: z.optional(z.array(zUserIdBundle)),
    BankAccounts: z.optional(z.array(zBankAccountState)),
});
export const zUpdateLicenseRequestModel = z.object({
    CompanyID: z.optional(z.int()),
    License: z.optional(zLicenseConfiguration),
});
export const zAddNewLicenseBillableModel = z.object({
    CompanyID: z.optional(z.int()),
    AmountOfExtraDocuments: z.optional(z.int()),
    AmountOfExtraUsers: z.optional(z.int()),
});
export const zFeed = z.object({
    Name: z.optional(z.string()),
});
export const zFeedItem = z.object({
    FeedItemID: z.optional(z.int()),
    EntityID: z.optional(z.int()),
    EntityType: z.optional(z.string()),
    PartyID: z.optional(z.int()),
});
/**
 * Optional, For logging purpose
 */
export const zConfirmRequest = z.object({
    RemoteServerName: z.optional(z.string()),
    RemotePath: z.optional(z.string()),
});
export const zFileDetails = z.object({
    FileName: z.optional(z.string()),
    FileContent: z.optional(z.string()),
    FileContentSHA256Hash: z.optional(z.string()),
});
export const zCashbookInitialization = z.object({
    StartDate: z.optional(z.iso.datetime()),
    StartBalance: z.optional(z.number()),
});
export const zCashbookModel = z.object({
    CashbookID: z.optional(z.int()),
    Name: z.optional(z.string()),
    CreationDate: z.optional(z.iso.datetime()),
    Saldo: z.optional(z.number()),
    LastEntryDate: z.optional(z.iso.datetime()),
    Currency: z.optional(z.string()),
});
export const zIEdmSchemaElement = z.object({
    SchemaElementKind: z.optional(z.enum(["None", "TypeDefinition", "Function", "ValueTerm", "EntityContainer"])),
    Namespace: z.optional(z.string().readonly()),
    Name: z.optional(z.string().readonly()),
});
export const zIEdmTerm = z.object({
    TermKind: z.optional(z.enum(["None", "Type", "Value"])),
    SchemaElementKind: z.optional(z.enum(["None", "TypeDefinition", "Function", "ValueTerm", "EntityContainer"])),
    Namespace: z.optional(z.string().readonly()),
    Name: z.optional(z.string().readonly()),
});
export const zIEdmVocabularyAnnotatable = z.record(z.string(), z.unknown());
export const zIEdmVocabularyAnnotation = z.object({
    Qualifier: z.optional(z.string().readonly()),
    Term: z.optional(zIEdmTerm),
    Target: z.optional(zIEdmVocabularyAnnotatable),
});
export const zIEdmDirectValueAnnotationsManager = z.record(z.string(), z.unknown());
export const zIEdmModel = z.object({
    SchemaElements: z.optional(z.array(zIEdmSchemaElement).readonly()),
    VocabularyAnnotations: z.optional(z.array(zIEdmVocabularyAnnotation).readonly()),
    get ReferencedModels() {
        return z.optional(z
            .array(z.lazy(() => {
            return zIEdmModel;
        }))
            .readonly());
    },
    DirectValueAnnotationsManager: z.optional(zIEdmDirectValueAnnotationsManager),
});
export const zIEdmType = z.object({
    TypeKind: z.optional(z.enum([
        "None",
        "Primitive",
        "Entity",
        "Complex",
        "Row",
        "Collection",
        "EntityReference",
        "Enum",
    ])),
});
export const zODataQueryContext = z.object({
    Model: z.optional(zIEdmModel),
    ElementType: z.optional(zIEdmType),
    ElementClrType: z.optional(z.string().readonly()),
});
export const zODataRawQueryOptions = z.object({
    Filter: z.optional(z.string().readonly()),
    OrderBy: z.optional(z.string().readonly()),
    Top: z.optional(z.string().readonly()),
    Skip: z.optional(z.string().readonly()),
    Select: z.optional(z.string().readonly()),
    Expand: z.optional(z.string().readonly()),
    InlineCount: z.optional(z.string().readonly()),
    Format: z.optional(z.string().readonly()),
    SkipToken: z.optional(z.string().readonly()),
});
export const zSelectExpandQueryValidator = z.record(z.string(), z.unknown());
export const zSelectItem = z.record(z.string(), z.unknown());
export const zSelectExpandClause = z.object({
    SelectedItems: z.optional(z.array(zSelectItem).readonly()),
    AllSelected: z.optional(z.boolean().readonly()),
});
export const zSelectExpandQueryOption = z.object({
    Context: z.optional(zODataQueryContext),
    RawSelect: z.optional(z.string().readonly()),
    RawExpand: z.optional(z.string().readonly()),
    Validator: z.optional(zSelectExpandQueryValidator),
    SelectExpandClause: z.optional(zSelectExpandClause),
});
export const zFilterQueryValidator = z.record(z.string(), z.unknown());
export const zIEdmTypeReference = z.object({
    IsNullable: z.optional(z.boolean().readonly()),
    Definition: z.optional(zIEdmType),
});
export const zSingleValueNode = z.object({
    TypeReference: z.optional(zIEdmTypeReference),
    Kind: z.optional(z.enum([
        "None",
        "Constant",
        "Convert",
        "NonentityRangeVariableReference",
        "BinaryOperator",
        "UnaryOperator",
        "SingleValuePropertyAccess",
        "CollectionPropertyAccess",
        "SingleValueFunctionCall",
        "Any",
        "CollectionNavigationNode",
        "SingleNavigationNode",
        "SingleValueOpenPropertyAccess",
        "SingleEntityCast",
        "All",
        "EntityCollectionCast",
        "EntityRangeVariableReference",
        "SingleEntityFunctionCall",
        "CollectionFunctionCall",
        "EntityCollectionFunctionCall",
        "NamedFunctionParameter",
    ])),
});
export const zRangeVariable = z.object({
    Name: z.optional(z.string().readonly()),
    TypeReference: z.optional(zIEdmTypeReference),
    Kind: z.optional(z.int().readonly()),
});
export const zFilterClause = z.object({
    Expression: z.optional(zSingleValueNode),
    RangeVariable: z.optional(zRangeVariable),
    ItemType: z.optional(zIEdmTypeReference),
});
export const zFilterQueryOption = z.object({
    Context: z.optional(zODataQueryContext),
    Validator: z.optional(zFilterQueryValidator),
    FilterClause: z.optional(zFilterClause),
    RawValue: z.optional(z.string().readonly()),
});
export const zOrderByNode = z.object({
    Direction: z.optional(z.enum(["Ascending", "Descending"])),
});
export const zOrderByQueryValidator = z.record(z.string(), z.unknown());
export const zOrderByClause = z.object({
    get ThenBy() {
        return z.optional(z.lazy(() => {
            return zOrderByClause;
        }));
    },
    Expression: z.optional(zSingleValueNode),
    Direction: z.optional(z.enum(["Ascending", "Descending"])),
    RangeVariable: z.optional(zRangeVariable),
    ItemType: z.optional(zIEdmTypeReference),
});
export const zOrderByQueryOption = z.object({
    Context: z.optional(zODataQueryContext),
    OrderByNodes: z.optional(z.array(zOrderByNode).readonly()),
    RawValue: z.optional(z.string().readonly()),
    Validator: z.optional(zOrderByQueryValidator),
    OrderByClause: z.optional(zOrderByClause),
});
export const zSkipQueryValidator = z.record(z.string(), z.unknown());
export const zSkipQueryOption = z.object({
    Context: z.optional(zODataQueryContext),
    RawValue: z.optional(z.string().readonly()),
    Value: z.optional(z.int().readonly()),
    Validator: z.optional(zSkipQueryValidator),
});
export const zTopQueryValidator = z.record(z.string(), z.unknown());
export const zTopQueryOption = z.object({
    Context: z.optional(zODataQueryContext),
    RawValue: z.optional(z.string().readonly()),
    Value: z.optional(z.int().readonly()),
    Validator: z.optional(zTopQueryValidator),
});
export const zInlineCountQueryOption = z.object({
    Context: z.optional(zODataQueryContext),
    RawValue: z.optional(z.string().readonly()),
    Value: z.optional(z.enum(["None", "AllPages"])),
});
export const zODataQueryValidator = z.record(z.string(), z.unknown());
export const zODataQueryOptionsCashbookEntry = z.object({
    IfMatch: z.optional(z.record(z.string(), z.unknown()).readonly()),
    IfNoneMatch: z.optional(z.record(z.string(), z.unknown()).readonly()),
    Context: z.optional(zODataQueryContext),
    Request: z.optional(z.record(z.string(), z.unknown()).readonly()),
    RawValues: z.optional(zODataRawQueryOptions),
    SelectExpand: z.optional(zSelectExpandQueryOption),
    Filter: z.optional(zFilterQueryOption),
    OrderBy: z.optional(zOrderByQueryOption),
    Skip: z.optional(zSkipQueryOption),
    Top: z.optional(zTopQueryOption),
    InlineCount: z.optional(zInlineCountQueryOption),
    Validator: z.optional(zODataQueryValidator),
});
export const zCashbookEntry = z.object({
    TransactionDate: z.optional(z.iso.datetime()),
    EntryType: z.optional(z.string()),
    Note: z.optional(z.string()),
    InternalInformation: z.optional(z.string()),
    Direction: z.optional(z.string()),
    Amount: z.optional(z.number()),
});
export const zPageResultCashbookEntry = z.object({
    Items: z.optional(z.array(zCashbookEntry)),
    NextPageLink: z.optional(z.string()),
    Count: z.optional(z.coerce.bigint()),
});
export const zDailyReceiptBookEntryModel = z.object({
    Description: z.optional(z.string()),
    VATPercentage: z.optional(z.number()),
    TotalIncl: z.optional(z.number()),
    InputDate: z.optional(z.iso.datetime()),
    VentilationCodeTC: z.optional(z.string()),
});
export const zPostDailyReceiptBookEntryResponseModel = z.object({
    CashbookId: z.optional(z.int()),
    CashbookEntryId: z.optional(z.int()),
});
export const zGetDailyReceiptEntryResponseModel = z.object({
    CashbookEntryID: z.optional(z.int()),
    CashbookID: z.optional(z.int()),
    VAT: z.optional(z.number()),
    Description: z.optional(z.string()),
    Orderid: z.optional(z.int()),
    TotalIncl: z.optional(z.number()),
    TotalExcl: z.optional(z.number()),
    TotalVAT: z.optional(z.number()),
});
export const zCashbook = z.object({
    CashbookID: z.optional(z.int()),
    FromDate: z.optional(z.iso.datetime()),
    Closed: z.optional(z.boolean()),
});
export const zDailyReceiptBookModelResponseModel = z.object({
    Cashbooks: z.optional(z.array(zCashbook)),
    CashbookEntries: z.optional(z.array(zGetDailyReceiptEntryResponseModel)),
});
export const zFile = z.object({
    FileID: z.optional(z.uuid()),
    FileName: z.optional(z.string()),
    MimeType: z.optional(z.string()),
    FileContent: z.optional(z.string()),
});
export const zDocument = z.object({
    DocumentID: z.optional(z.int()),
    CompanyID: z.optional(z.int()),
    File: z.optional(zFile),
    Name: z.optional(z.string()),
    Description: z.optional(z.string()),
    DocumentDate: z.optional(z.iso.datetime()),
    CreationDate: z.optional(z.iso.datetime()),
    Tags: z.optional(z.array(z.string())),
});
export const zODataQueryOptionsDocumentApiView = z.object({
    IfMatch: z.optional(z.record(z.string(), z.unknown()).readonly()),
    IfNoneMatch: z.optional(z.record(z.string(), z.unknown()).readonly()),
    Context: z.optional(zODataQueryContext),
    Request: z.optional(z.record(z.string(), z.unknown()).readonly()),
    RawValues: z.optional(zODataRawQueryOptions),
    SelectExpand: z.optional(zSelectExpandQueryOption),
    Filter: z.optional(zFilterQueryOption),
    OrderBy: z.optional(zOrderByQueryOption),
    Skip: z.optional(zSkipQueryOption),
    Top: z.optional(zTopQueryOption),
    InlineCount: z.optional(zInlineCountQueryOption),
    Validator: z.optional(zODataQueryValidator),
});
export const zDocumentApiView = z.object({
    DocumentID: z.optional(z.int()),
    CompanyID: z.optional(z.int()),
    File: z.optional(zFile),
    Name: z.optional(z.string()),
    Description: z.optional(z.string()),
    DocumentDate: z.optional(z.iso.datetime()),
    CreationDate: z.optional(z.iso.datetime()),
    Tags: z.optional(z.array(z.string())),
});
export const zPageResultDocumentApiView = z.object({
    Items: z.optional(z.array(zDocumentApiView)),
    NextPageLink: z.optional(z.string()),
    Count: z.optional(z.coerce.bigint()),
});
export const zEinvoiceAccountSettings = z.object({
    ProcessUBLPrePaidAmount: z.optional(z.boolean()),
});
export const zEinvoiceRegistrationPost = z.object({
    TaxIdentifier: z.optional(z.string()),
    CompanyName: z.optional(z.string()),
    CommercialName: z.optional(z.string()),
    Addresses: z.optional(z.array(zPartyAddress)),
    TaxDeductable: z.optional(z.boolean()),
    TaxLiable: z.optional(z.boolean()),
    IBAN: z.optional(z.string()),
    BIC: z.optional(z.string()),
    Mobile: z.optional(z.string()),
    Phone: z.optional(z.string()),
    Email: z.optional(z.string()),
    ContactFirstName: z.optional(z.string()),
    ContactLastName: z.optional(z.string()),
    Language: z.optional(z.string()),
    Identifiers: z.optional(z.array(zPartyIdentifier)),
    AccountSettings: z.optional(zEinvoiceAccountSettings),
});
export const zAccountRegistrationResponse = z.object({
    RegistrationID: z.optional(z.int()),
});
export const zEinvoiceIntegration = z.object({
    IntegrationID: z.optional(z.int()),
    Integration: z.optional(z.string()),
    IntegrationStatus: z.optional(z.string()),
    IntegrationStatusDescription: z.optional(z.string()),
    IntegrationDocumentToSign: z.optional(z.string()),
});
export const zEinvoiceRegistrationsAccount = z.object({
    RegistrationID: z.optional(z.int()),
    CompanyDetails: z.optional(zEinvoiceRegistrationPost),
    Integrations: z.optional(z.array(zEinvoiceIntegration)),
});
export const zGetEinvoiceAccountsReponse = z.object({
    Companies: z.optional(z.array(zEinvoiceRegistrationsAccount)),
});
export const zIntegrationPost = z.object({
    Externalprovider: z.optional(z.string()),
    Credentials: z.optional(z.record(z.string(), z.string())),
    Certificates: z.optional(z.record(z.string(), zFile)),
});
export const zExternalProviderReference = z.object({
    ExternalProvider: z.optional(z.string()),
    Category: z.optional(z.string()),
    Value: z.optional(z.string()),
    EntityType: z.optional(z.string()),
    EntityID: z.optional(z.int()),
});
export const zOrderLine = z.object({
    Quantity: z.optional(z.number()),
    UnitPriceExcl: z.optional(z.number()),
    AccountCode: z.optional(z.int()),
    Reference: z.optional(z.string()),
    Description: z.optional(z.string()),
    TotalExcl: z.optional(z.number()),
    TotalVAT: z.optional(z.number()),
    VATPercentage: z.optional(z.number()),
    VentilationCode: z.optional(z.string()),
    ProductID: z.optional(z.int()),
    Unit: z.optional(z.string()),
    CustomFields: z.optional(z.record(z.string(), z.string())),
    ExternalProviderReferences: z.optional(z.array(zExternalProviderReference)),
    InclLeading: z.optional(z.boolean()),
    UnitPriceIncl: z.optional(z.number()),
    TotalIncl: z.optional(z.number()),
    AnalyticCostBearer: z.optional(z.string()),
    AnalyticCostCenter: z.optional(z.string()),
    ReductionPercentage: z.optional(z.number()),
    DescriptionExtended: z.optional(z.string()),
});
export const zBookingEntry = z.object({
    BookingEntryID: z.optional(z.int()),
    OrderID: z.optional(z.int()),
    AccountCode: z.optional(z.int()),
    Amount: z.optional(z.number()),
    DebetOrCredit: z.optional(z.string()),
    VAT1: z.optional(z.int()),
    VAT2: z.optional(z.int()),
    VAT3: z.optional(z.int()),
});
export const zVatGroup = z.object({
    VentilationCode: z.optional(z.string()),
    VATPercentage: z.optional(z.number()),
    TotalExcl: z.optional(z.number()),
    TotalVAT: z.optional(z.number()),
    TotalIncl: z.optional(z.number()),
    Mtvh: z.optional(z.number()),
    FinancialReductionAmount: z.optional(z.number()),
});
export const zOcrText = z.object({
    Text: z.optional(z.string()),
    X: z.optional(z.number()),
    Y: z.optional(z.number()),
    Width: z.optional(z.number()),
    Height: z.optional(z.number()),
});
export const zOcrPage = z.object({
    TextList: z.optional(z.array(zOcrText)),
});
export const zPaymentLink = z.object({
    ExternalProvider: z.optional(z.string()),
    ClickUrl: z.optional(z.string()),
    QRImageUrl: z.optional(z.string()),
});
export const zDocumentDeliveryDetails = z.object({
    DocumentRefusedDate: z.optional(z.iso.datetime()),
    DocumentDeliveryDate: z.optional(z.iso.datetime()),
    DocumentDeliveryInfo: z.optional(z.string()),
    DocumentRefusedReasonTC: z.optional(z.string()),
    DocumentRefusedInfo: z.optional(z.string()),
    IsDocumentDelivered: z.optional(z.boolean()),
    DocumentDeliveryStatus: z.optional(z.string()),
});
export const zOrderMessage = z.object({
    OrderID: z.optional(z.int()),
    Description: z.optional(z.string()),
    FileID: z.optional(z.uuid()),
    CreationDate: z.optional(z.iso.datetime()),
    TransportType: z.optional(z.string()),
    Success: z.optional(z.boolean()),
    Trials: z.optional(z.int()),
    Destination: z.optional(z.string()),
    MessageDirection: z.optional(z.string()),
});
export const zAdditionalDocuments = z.object({
    DocumentDescription: z.optional(z.string()),
    ID: z.optional(z.string()),
    DocumentType: z.optional(z.string()),
    Attachment: z.optional(zFile),
    CustomFields: z.optional(z.record(z.string(), z.string())),
});
export const zContractDocumentReference = z.object({
    ID: z.optional(z.string()),
});
export const zCategoryFieldItem = z.object({
    Value: z.optional(z.string()),
    Name: z.optional(z.string()),
});
export const zTimezoneInfo = z.object({
    TimeZoneInfo: z.optional(z.string()),
    DateTime: z.optional(z.iso.datetime()),
});
export const zEInvoiceSignatureModel = z.object({
    OrginalString: z.optional(z.string()),
    NetworkCertificateNumber: z.optional(z.string()),
    DocumentCertificateNumber: z.optional(z.string()),
    UUID: z.optional(z.string()),
    NetworkStamp: z.optional(z.string()),
    DocumentStamp: z.optional(z.string()),
    DateTimeInfo: z.optional(zTimezoneInfo),
    QRCode: z.optional(z.string()),
    Cfdi: z.optional(z.string()),
    StampUrl: z.optional(z.string()),
});
export const zOrder = z.object({
    OrderID: z.optional(z.int()),
    CompanyID: z.optional(z.int()),
    OrderPDF: z.optional(zFile),
    Attachments: z.optional(z.array(zFile)),
    OrderNumber: z.optional(z.string()),
    CustomerID: z.optional(z.int()),
    SupplierID: z.optional(z.int()),
    CounterPartyID: z.optional(z.int()),
    Customer: z.optional(zParty),
    Supplier: z.optional(zParty),
    CounterParty: z.optional(zParty),
    OrderDate: z.optional(z.iso.datetime()),
    ExpiryDate: z.optional(z.iso.datetime()),
    OrderType: z.optional(z.string()),
    LastModified: z.optional(z.iso.datetime()),
    Created: z.optional(z.iso.datetime()),
    OrderDirection: z.optional(z.string()),
    OrderLines: z.optional(z.array(zOrderLine)),
    BookingEntries: z.optional(z.array(zBookingEntry)),
    Journal: z.optional(z.string()),
    OrderTitle: z.optional(z.string()),
    PaymentDiscountPercentage: z.optional(z.number()),
    PaymentDiscountAmount: z.optional(z.number()),
    PaymentReductionDays: z.optional(z.int()),
    PaymentDiscountDate: z.optional(z.iso.datetime()),
    VatGroups: z.optional(z.array(zVatGroup)),
    VentilationCode: z.optional(z.string()),
    TotalExcl: z.optional(z.number()),
    TotalIncl: z.optional(z.number()),
    TotalVAT: z.optional(z.number()),
    Reference: z.optional(z.string()),
    Tags: z.optional(z.array(z.string())),
    DepartmentID: z.optional(z.int()),
    PaymentReference: z.optional(z.string()),
    AboutInvoiceNumber: z.optional(z.string()),
    OCRRawText: z.optional(z.string()),
    OCRMetaPages: z.optional(z.array(zOcrPage)),
    Paid: z.optional(z.boolean()),
    PaidDate: z.optional(z.iso.datetime()),
    ExternalProviderID: z.optional(z.string()),
    ExternalProvider: z.optional(z.string()),
    ProjectID: z.optional(z.int()),
    ProjectName: z.optional(z.string()),
    ExternalProviderReferences: z.optional(z.array(zExternalProviderReference)),
    Comments: z.optional(z.string()),
    Currency: z.optional(z.string()),
    VatDeduction: z.optional(z.number()),
    MixedUseProfessionalPercentage: z.optional(z.number()),
    InternalInfo: z.optional(z.string()),
    IsSent: z.optional(z.boolean()),
    Invoiced: z.optional(z.boolean()),
    CustomFields: z.optional(z.record(z.string(), z.string())),
    PeriodFrom: z.optional(z.iso.datetime()),
    PeriodTill: z.optional(z.iso.datetime()),
    CostCategoryCode: z.optional(z.int()),
    AccountCode: z.optional(z.int()),
    AccountingCostTypeTC: z.optional(z.string()),
    LastReminder: z.optional(z.iso.datetime()),
    RemindersSent: z.optional(z.int()),
    ToPay: z.optional(z.number()),
    OrderStatus: z.optional(z.string()),
    ApprovalStatus: z.optional(z.string()),
    Overdue: z.optional(z.boolean()),
    DaysOverdue: z.optional(z.int()),
    FXRateToForeign: z.optional(z.number()),
    PaymentMethod: z.optional(z.string()),
    DeliveryDate: z.optional(z.iso.datetime()),
    ExportedToConnector: z.optional(z.boolean()),
    PaymentLinks: z.optional(z.array(zPaymentLink)),
    TemplateID: z.optional(z.int()),
    MessageTemplateID: z.optional(z.int()),
    AnalyticCostBearer: z.optional(z.string()),
    AnalyticCostCenter: z.optional(z.string()),
    AccountantVerificationNeeded: z.optional(z.boolean()),
    CurrentDocumentDeliveryDetails: z.optional(zDocumentDeliveryDetails),
    Messages: z.optional(z.array(zOrderMessage)),
    AdditionalDocumentReference: z.optional(z.array(zAdditionalDocuments)),
    PaymentTerms: z.optional(z.string()),
    ContractDocumentReference: z.optional(z.array(zContractDocumentReference)),
    TaxPointDate: z.optional(z.iso.datetime()),
    CategoryFieldItems: z.optional(z.array(zCategoryFieldItem)),
    Signature: z.optional(zEInvoiceSignatureModel),
});
export const zCreateAndSendEDocumentPost = z.object({
    TransportType: z.optional(z.string()),
    Order: z.optional(zOrder),
});
export const zError = z.object({
    ErrorEnum: z.optional(z.string()),
    ErrorParams: z.optional(z.array(z.record(z.string(), z.unknown()))),
    ErrorMessage: z.optional(z.string()),
    Append: z.optional(z.string()),
    DefaultText: z.optional(z.string()),
});
export const zCreateAndSendEdocumentResponse = z.object({
    OrderID: z.optional(z.int()),
    TranssportStatus: z.optional(z.int()),
    TransportMessages: z.optional(z.array(zError)),
});
export const zODataQueryOptionsOrder = z.object({
    IfMatch: z.optional(z.record(z.string(), z.unknown()).readonly()),
    IfNoneMatch: z.optional(z.record(z.string(), z.unknown()).readonly()),
    Context: z.optional(zODataQueryContext),
    Request: z.optional(z.record(z.string(), z.unknown()).readonly()),
    RawValues: z.optional(zODataRawQueryOptions),
    SelectExpand: z.optional(zSelectExpandQueryOption),
    Filter: z.optional(zFilterQueryOption),
    OrderBy: z.optional(zOrderByQueryOption),
    Skip: z.optional(zSkipQueryOption),
    Top: z.optional(zTopQueryOption),
    InlineCount: z.optional(zInlineCountQueryOption),
    Validator: z.optional(zODataQueryValidator),
});
export const zPageResultOrder = z.object({
    Items: z.optional(z.array(zOrder)),
    NextPageLink: z.optional(z.string()),
    Count: z.optional(z.coerce.bigint()),
});
export const zWebhook = z.object({
    WebhookID: z.optional(z.int()),
    CompanyID: z.optional(z.int()),
    UserID: z.optional(z.int()),
    EntityType: z.optional(z.string()),
    EntityUpdateType: z.optional(z.string()),
    WebhookURL: z.optional(z.string()),
    Secret: z.optional(z.string()),
});
export const zKycInitiationPost = z.object({
    IdentificationProviderTC: z.optional(z.string()),
    RedirectURL: z.optional(z.string()),
});
export const zKycInitiationResponse = z.object({
    URL: z.optional(z.string()),
});
export const zAssignedEntity = z.object({
    AssignedAmount: z.optional(z.number()),
    FXRateToBankCurrency: z.optional(z.number()),
    EntityType: z.optional(z.string()),
    EntityID: z.optional(z.int()),
});
export const zTransaction = z.object({
    BankAccountTransactionID: z.optional(z.int()),
    BankName: z.optional(z.string()),
    IBAN: z.optional(z.string()),
    BIC: z.optional(z.string()),
    BankAccountID: z.optional(z.int()),
    DocumentId: z.optional(z.int()),
    IBANCounterParty: z.optional(z.string()),
    BICCounterParty: z.optional(z.string()),
    NameCounterParty: z.optional(z.string()),
    TotalAmount: z.optional(z.number()),
    TransactionType: z.optional(z.string()),
    ValueDate: z.optional(z.iso.datetime()),
    Currency: z.optional(z.string()),
    Description: z.optional(z.string()),
    ExternalProviderID: z.optional(z.string()),
    ExternalProviderTC: z.optional(z.string()),
    FreeMessage: z.optional(z.string()),
    CodaSource: z.optional(z.string()),
    CodaFileID: z.optional(z.uuid()),
    BankReference: z.optional(z.string()),
    ClientReference: z.optional(z.string()),
    Note: z.optional(z.string()),
    AssignedEntities: z.optional(z.array(zAssignedEntity)),
    ProprietaryBankTransactionCode: z.optional(z.string()),
    BankTransactionCode: z.optional(z.string()),
});
export const zODataQueryOptionsTransaction = z.object({
    IfMatch: z.optional(z.record(z.string(), z.unknown()).readonly()),
    IfNoneMatch: z.optional(z.record(z.string(), z.unknown()).readonly()),
    Context: z.optional(zODataQueryContext),
    Request: z.optional(z.record(z.string(), z.unknown()).readonly()),
    RawValues: z.optional(zODataRawQueryOptions),
    SelectExpand: z.optional(zSelectExpandQueryOption),
    Filter: z.optional(zFilterQueryOption),
    OrderBy: z.optional(zOrderByQueryOption),
    Skip: z.optional(zSkipQueryOption),
    Top: z.optional(zTopQueryOption),
    InlineCount: z.optional(zInlineCountQueryOption),
    Validator: z.optional(zODataQueryValidator),
});
export const zPageResultTransaction = z.object({
    Items: z.optional(z.array(zTransaction)),
    NextPageLink: z.optional(z.string()),
    Count: z.optional(z.coerce.bigint()),
});
export const zGlAccount = z.object({
    Code: z.optional(z.int()),
    Description: z.optional(z.string()),
    GLAccountType: z.optional(z.string()),
});
export const zJournal = z.object({
    Code: z.optional(z.string()),
    Description: z.optional(z.string()),
    JournalType: z.optional(z.enum(["Income", "Cost"])),
});
export const zCompanySearchResultItem = z.object({
    Source: z.optional(z.string()),
    CompanyIdentification: z.optional(z.string()),
    Street: z.optional(z.string()),
    Number: z.optional(z.string()),
    Name: z.optional(z.string()),
    Zipcode: z.optional(z.string()),
    City: z.optional(z.string()),
    Box: z.optional(z.string()),
    Country: z.optional(z.string()),
    StartDate: z.optional(z.iso.datetime()),
    CommercialName: z.optional(z.string()),
});
export const zCompanySearchResult = z.object({
    Items: z.optional(z.array(zCompanySearchResultItem)),
});
export const zTypeCodeResultItem = z.object({
    Key: z.optional(z.string()),
    Value: z.optional(z.string()),
});
export const zTypeCodeResult = z.object({
    Items: z.optional(z.array(zTypeCodeResultItem)),
});
export const zOAuthAccessTokenRequest = z.object({
    client_id: z.optional(z.string()),
    client_secret: z.optional(z.string()),
    code: z.optional(z.string()),
    grant_type: z.optional(z.string()),
    redirect_uri: z.optional(z.string()),
    refresh_token: z.optional(z.string()),
    state: z.optional(z.string()),
});
export const zPostPaymentRequest = z.object({
    Amount: z.optional(z.number()),
    Description: z.optional(z.string()),
    Date: z.optional(z.iso.datetime()),
});
export const zSendRequest = z.object({
    OrderIds: z.optional(z.array(z.int())),
    TransportType: z.optional(z.string()),
    PrintType: z.optional(z.string()),
});
export const zODataQueryOptionsParty = z.object({
    IfMatch: z.optional(z.record(z.string(), z.unknown()).readonly()),
    IfNoneMatch: z.optional(z.record(z.string(), z.unknown()).readonly()),
    Context: z.optional(zODataQueryContext),
    Request: z.optional(z.record(z.string(), z.unknown()).readonly()),
    RawValues: z.optional(zODataRawQueryOptions),
    SelectExpand: z.optional(zSelectExpandQueryOption),
    Filter: z.optional(zFilterQueryOption),
    OrderBy: z.optional(zOrderByQueryOption),
    Skip: z.optional(zSkipQueryOption),
    Top: z.optional(zTopQueryOption),
    InlineCount: z.optional(zInlineCountQueryOption),
    Validator: z.optional(zODataQueryValidator),
});
export const zPageResultParty = z.object({
    Items: z.optional(z.array(zParty)),
    NextPageLink: z.optional(z.string()),
    Count: z.optional(z.coerce.bigint()),
});
export const zRegisterParticipantRequest = z.object({
    CompanyID: z.optional(z.string()),
});
export const zDeleteParticipantRequest = z.object({
    CompanyID: z.optional(z.string()),
});
export const zInboxGetResultItem = z.object({
    InboxItemID: z.optional(z.int()),
    SenderPeppolID: z.optional(z.string()),
    PeppolDocumentType: z.optional(z.string()),
    ReceiverPeppolID: z.optional(z.string()),
    SenderCompanyID: z.optional(z.string()),
    ReceiverCompanyID: z.optional(z.string()),
    CreationDate: z.optional(z.iso.datetime()),
    PeppolFileID: z.optional(z.uuid()),
});
export const zInboxGetResult = z.object({
    InboxItems: z.optional(z.array(zInboxGetResultItem)),
});
export const zRefusePeppolItemRequest = z.object({
    RefusalReason: z.optional(z.string()),
});
export const zEndpoint = z.object({
    EndpointURL: z.optional(z.string()),
    TransportProfile: z.optional(z.string()),
    Certificate: z.optional(z.string()),
});
export const zProcessInfo = z.object({
    ProcessIdentifier: z.optional(z.string()),
    ProcessIdentifierScheme: z.optional(z.string()),
    Endpoints: z.optional(z.array(zEndpoint)),
});
export const zServiceDetail = z.object({
    DocumentIdentifier: z.optional(z.string()),
    DocumentIdentifierScheme: z.optional(z.string()),
    Processes: z.optional(z.array(zProcessInfo)),
});
export const zParticipantInformationResponse = z.object({
    Registered: z.optional(z.boolean()),
    Identifier: z.optional(z.string()),
    DocumentTypes: z.optional(z.array(z.enum([
        "Invoice4",
        "Invoice5",
        "CreditNote5",
        "MLR",
        "MLRBISV3",
        "MLRBISV2",
        "IMR",
        "EFFF",
        "BISv3Invoice",
        "BISv3CreditNote",
        "BISv3OrderForm",
        "BISv3AUNZInvoice",
        "BISv3AUNZCreditNote",
        "XRechnung22Invoice",
        "XRechnung22CreditNote",
        "SIInvoice",
        "SICreditNote",
        "UBLBEInvoice",
        "UBLBECreditNote",
        "CII",
        "PTCIUSInvoice",
        "PTCIUSCreditNote",
        "BISv3SGInvoice",
        "BISv3SGCreditNote",
        "ROCIUSInvoice",
        "ROCIUSCreditNote",
        "XRechnung3Invoice",
        "XRechnung3CreditNote",
        "EndUserStatistics",
        "TransactionStatistics",
        "MYPintInvoice",
        "MYPintCreditNote",
        "MYPintInvoiceWildCard",
        "MYPintCreditNoteWildCard",
        "PintInvoiceWildCard",
        "PintCreditNoteWildCard",
        "AUNZPintInvoice",
        "AUNZPintCreditNote",
        "FACeCIUSInvoice",
        "FACeCIUSCreditNote",
        "PintBillingWildCard",
    ]))),
    ServiceDetails: z.optional(z.array(zServiceDetail)),
    ServiceProviderID: z.optional(z.string()),
});
export const zProduct = z.object({
    ProductID: z.optional(z.int()),
    Reference: z.optional(z.string()),
    Description: z.optional(z.string()),
    AmountExcl: z.optional(z.number()),
    VAT: z.optional(z.number()),
    Unit: z.optional(z.string()),
    GroupID: z.optional(z.int()),
    GroupName: z.optional(z.string()),
    AmountIncl: z.optional(z.number()),
    StockQuantity: z.optional(z.number()),
    MinimumBilledQuantity: z.optional(z.number()),
    BuyExcl: z.optional(z.number()),
    InternalInformation: z.optional(z.string()),
    Created: z.optional(z.iso.datetime()),
    LastModified: z.optional(z.iso.datetime()),
    EAN: z.optional(z.string()),
    GTIN: z.optional(z.string()),
    GLN: z.optional(z.string()),
    ExternalProviderTC: z.optional(z.string()),
    get ChildProducts() {
        return z.optional(z.array(z.lazy(() => {
            return zProduct;
        })));
    },
});
export const zODataQueryOptionsProduct = z.object({
    IfMatch: z.optional(z.record(z.string(), z.unknown()).readonly()),
    IfNoneMatch: z.optional(z.record(z.string(), z.unknown()).readonly()),
    Context: z.optional(zODataQueryContext),
    Request: z.optional(z.record(z.string(), z.unknown()).readonly()),
    RawValues: z.optional(zODataRawQueryOptions),
    SelectExpand: z.optional(zSelectExpandQueryOption),
    Filter: z.optional(zFilterQueryOption),
    OrderBy: z.optional(zOrderByQueryOption),
    Skip: z.optional(zSkipQueryOption),
    Top: z.optional(zTopQueryOption),
    InlineCount: z.optional(zInlineCountQueryOption),
    Validator: z.optional(zODataQueryValidator),
});
export const zPageResultProduct = z.object({
    Items: z.optional(z.array(zProduct)),
    NextPageLink: z.optional(z.string()),
    Count: z.optional(z.coerce.bigint()),
});
export const zReportsExportOverViewModel = z.object({
    ReportID: z.optional(z.int()),
    ReportName: z.optional(z.string()),
});
export const zReportDetailModel = z.object({
    ID: z.optional(z.int()),
    Name: z.optional(z.string()),
    CSVs: z.optional(z.array(z.string())),
});
export const zUploadMetadata = z.object({
    TotalIncl: z.optional(z.number()),
    CostType: z.optional(z.string()),
    PaymentMethod: z.optional(z.string()),
    Description: z.optional(z.string()),
    CurrencyTC: z.optional(z.string()),
    OrderDate: z.optional(z.iso.datetime()),
});
export const zToProcessSaveRequest = z.object({
    Split: z.optional(z.boolean()),
    File: z.optional(zFile),
    FileSource: z.optional(zFile),
    MetaData: z.optional(zUploadMetadata),
});
export const zAccountGetAccountInformationData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * Account information of the current user
 */
export const zAccountGetAccountInformationResponse = zAccountInformation;
export const zAccountGetSsoTokenData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * object with SSO token
 */
export const zAccountGetSsoTokenResponse = z.record(z.string(), z.unknown());
export const zAccountPostSequencesData = z.object({
    body: zSequenceRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * Sequence updated
 */
export const zAccountPostSequencesResponse = z.string();
export const zAccountRegisterCompanyData = z.object({
    body: zRegisterAccountRequestModel,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * New company registered
 */
export const zAccountRegisterCompanyResponse = zRegisterAccountResponse;
export const zAccountUpdateLicenseData = z.object({
    body: zUpdateLicenseRequestModel,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * Company license updated
 */
export const zAccountUpdateLicenseResponse = z.int();
export const zAccountAddLicenseBillableData = z.object({
    body: zAddNewLicenseBillableModel,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * New license billable added
 */
export const zAccountAddLicenseBillableResponse = z.int();
export const zAccountantGetFeedsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * A list of all feeds to download.
 */
export const zAccountantGetFeedsResponse = z.array(zFeed);
export const zAccountantPostFeedsData = z.object({
    body: zFeed,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
export const zAccountantDeleteFeedsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        feedName: z.string(),
    }),
    query: z.optional(z.never()),
});
export const zAccountantGetIndexData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        feedName: z.string(),
    }),
    query: z.optional(z.never()),
});
/**
 * A list of all files to download.
 */
export const zAccountantGetIndexResponse = z.array(zFeedItem);
export const zAccountantPostConfirmData = z.object({
    body: zConfirmRequest,
    path: z.object({
        feedName: z.string(),
        feedItemID: z.int(),
    }),
    query: z.optional(z.never()),
});
export const zAccountantGetFileData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        feedItemID: z.int(),
        feedName: z.string(),
    }),
    query: z.optional(z.never()),
});
/**
 * File downloaded
 */
export const zAccountantGetFileResponse = zFileDetails;
export const zCashbookInitializeCashbookData = z.object({
    body: zCashbookInitialization,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * Cash book was initialized
 */
export const zCashbookInitializeCashbookResponse = z.int();
export const zCashbookCloseCashbookData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
export const zCashbookGetCashbookData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * Information about the current active cash book
 */
export const zCashbookGetCashbookResponse = zCashbookModel;
export const zCashbookGetCashbookEntriesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        fullTextSearch: z.optional(z.string()),
    })),
});
/**
 * A list of all the entries in the cash book
 */
export const zCashbookGetCashbookEntriesResponse = zPageResultCashbookEntry;
export const zCashbookGetCashbooksData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * A list of all the closed cash books
 */
export const zCashbookGetCashbooksResponse = z.array(zCashbookModel);
export const zCashbookGetCashbookHistoryData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        cashbookID: z.int(),
    }),
    query: z.optional(z.object({
        fullTextSearch: z.optional(z.string()),
    })),
});
/**
 * A list of all the entries in a closed cash book
 */
export const zCashbookGetCashbookHistoryResponse = zPageResultCashbookEntry;
export const zCashbookPostCashbookEntryData = z.object({
    body: zCashbookEntry,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * Entry has been added to the current active cash book
 */
export const zCashbookPostCashbookEntryResponse = zCashbookEntry;
export const zDailyReceiptPostDailyReceiptBookEntryData = z.object({
    body: zDailyReceiptBookEntryModel,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * Daily receipt entry was created
 */
export const zDailyReceiptPostDailyReceiptBookEntryResponse = zPostDailyReceiptBookEntryResponseModel;
export const zDailyReceiptGetDailyReceiptEntryData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        DailyReceiptEntryID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Detail of a daily receipt entry
 */
export const zDailyReceiptGetDailyReceiptEntryResponse = zGetDailyReceiptEntryResponseModel;
export const zDailyReceiptGetDailyReceiptBooksData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        DailyReceiptBookID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Detail of a daily receipt book
 */
export const zDailyReceiptGetDailyReceiptBooksResponse = zDailyReceiptBookModelResponseModel;
export const zDailyReceiptGetDailyReceiptBooks2Data = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * A list of daily receipt books
 */
export const zDailyReceiptGetDailyReceiptBooks2Response = zDailyReceiptBookModelResponseModel;
export const zDocumentGetDocumentsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        fullTextSearch: z.optional(z.string()),
    })),
});
/**
 * A list of documents
 */
export const zDocumentGetDocumentsResponse = zPageResultDocumentApiView;
export const zDocumentPostDocumentData = z.object({
    body: zDocument,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * Document was saved
 */
export const zDocumentPostDocumentResponse = z.int();
export const zDocumentGetDocumentData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        documentID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * A document
 */
export const zDocumentGetDocumentResponse = zDocumentApiView;
export const zEinvoiceGetRegistrationsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * A list of E-invoice registrations
 */
export const zEinvoiceGetRegistrationsResponse = zGetEinvoiceAccountsReponse;
export const zEinvoicePostRegistrationData = z.object({
    body: zEinvoiceRegistrationPost,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * E-invoice registration was created
 */
export const zEinvoicePostRegistrationResponse = zAccountRegistrationResponse;
export const zEinvoiceDeleteRegistrationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        registrationID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Registration was deleted
 */
export const zEinvoiceDeleteRegistrationResponse = z.boolean();
export const zEinvoiceGetRegistrationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        registrationID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * An E-invoice registration
 */
export const zEinvoiceGetRegistrationResponse = zGetEinvoiceAccountsReponse;
export const zEinvoicePatchEntityData = z.object({
    body: z.record(z.string(), z.unknown()),
    path: z.object({
        registrationID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Properties were updated
 */
export const zEinvoicePatchEntityResponse = z.boolean();
export const zEinvoicePostRegistrationIntegrationData = z.object({
    body: zIntegrationPost,
    path: z.object({
        registrationID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Integration was activated
 */
export const zEinvoicePostRegistrationIntegrationResponse = zEinvoiceIntegration;
export const zEinvoiceDeleteRegistrationIntegrationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        registrationID: z.int(),
        integrationID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Integration was deactivated
 */
export const zEinvoiceDeleteRegistrationIntegrationResponse = z.boolean();
export const zEinvoicePostSendData = z.object({
    body: zCreateAndSendEDocumentPost,
    path: z.object({
        registrationID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * E-document was created and sent
 */
export const zEinvoicePostSendResponse = zCreateAndSendEdocumentResponse;
export const zEinvoiceGetOrdersData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        registrationID: z.int(),
    }),
    query: z.optional(z.object({
        fullTextSearch: z.optional(z.string()),
    })),
});
/**
 * A list of orders
 */
export const zEinvoiceGetOrdersResponse = zPageResultOrder;
export const zEinvoiceGetFileData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        registrationID: z.int(),
        fileID: z.uuid(),
    }),
    query: z.optional(z.never()),
});
/**
 * A file
 */
export const zEinvoiceGetFileResponse = zFile;
export const zEinvoiceGetOrderData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        registrationID: z.int(),
        orderID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * An order
 */
export const zEinvoiceGetOrderResponse = zOrder;
export const zEinvoicePatchOrderData = z.object({
    body: z.record(z.string(), z.unknown()),
    path: z.object({
        registrationID: z.int(),
        orderID: z.int(),
    }),
    query: z.optional(z.never()),
});
export const zEinvoiceGetWebhooksData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        registrationID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * A list of webhooks
 */
export const zEinvoiceGetWebhooksResponse = z.array(zWebhook);
export const zEinvoicePostWebhookData = z.object({
    body: zWebhook,
    path: z.object({
        registrationID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Webhook was created
 */
export const zEinvoicePostWebhookResponse = zWebhook;
export const zEinvoiceDeleteWebhooksData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        registrationID: z.int(),
        webhookID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Webhook was deleted
 */
export const zEinvoiceDeleteWebhooksResponse = z.boolean();
export const zEinvoiceRefreshWebhookSecretData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        registrationID: z.int(),
        webhookID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Refreshed webhook secret
 */
export const zEinvoiceRefreshWebhookSecretResponse = z.string();
export const zEinvoicePostKycInitiationData = z.object({
    body: zKycInitiationPost,
    path: z.object({
        registrationID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * KYC procedure was initiated
 */
export const zEinvoicePostKycInitiationResponse = zKycInitiationResponse;
export const zFileGetOrdersData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        fileID: z.uuid(),
    }),
    query: z.optional(z.never()),
});
/**
 * A file
 */
export const zFileGetOrdersResponse = zFile;
export const zFinancialTransactionPostImportFileData = z.object({
    body: zFile,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
export const zFinancialTransactionPostImportData = z.object({
    body: z.array(zTransaction),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
export const zFinancialTransactionGetBankTransactionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        fullTextSearch: z.optional(z.string()),
    })),
});
export const zGlAccountPostGlAccountData = z.object({
    body: zGlAccount,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * General ledger account was created
 */
export const zGlAccountPostGlAccountResponse = z.int();
export const zGlAccountPostGlAccountBulkData = z.object({
    body: z.array(zGlAccount),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
export const zJournalPostGlAccountData = z.object({
    body: z.array(zJournal),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
export const zMiscGetCompanySearchData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        Keywords: z.string(),
    }),
    query: z.optional(z.never()),
});
/**
 * Search result based on a keyword
 */
export const zMiscGetCompanySearchResponse = zCompanySearchResult;
export const zMiscGetTypeCodesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        TypeCodeType: z.string(),
    }),
    query: z.optional(z.never()),
});
/**
 * A list of translations of a specified TypeCode
 */
export const zMiscGetTypeCodesResponse = zTypeCodeResult;
export const zMiscGetTranslationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        TypeCodeType: z.string(),
        key: z.string(),
        language: z.string(),
    }),
    query: z.optional(z.never()),
});
/**
 * A translation of a key of a typecode
 */
export const zMiscGetTranslationResponse = zTypeCodeResult;
export const zOAuth2PostTokenData = z.object({
    body: zOAuthAccessTokenRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * OK
 */
export const zOAuth2PostTokenResponse = z.record(z.string(), z.unknown());
export const zOAuth2PostTokenRevokeData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * OK
 */
export const zOAuth2PostTokenRevokeResponse = z.record(z.string(), z.unknown());
export const zOrderGetOrdersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        fullTextSearch: z.optional(z.string()),
    })),
});
/**
 * A list of invoices/creditnotes/offers/...
 */
export const zOrderGetOrdersResponse = zPageResultOrder;
export const zOrderPostOrdersData = z.object({
    body: zOrder,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * Order was created/updated
 */
export const zOrderPostOrdersResponse = z.int();
export const zOrderPutOrderBookingsData = z.object({
    body: z.array(zBookingEntry),
    path: z.object({
        orderID: z.int(),
    }),
    query: z.optional(z.never()),
});
export const zOrderDeleteOrderData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        orderID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Order was deleted
 */
export const zOrderDeleteOrderResponse = z.boolean();
export const zOrderGetOrderData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        orderID: z.int(),
    }),
    query: z.optional(z.object({
        documentType: z.optional(z.string()),
    })),
});
/**
 * An order based on the orderID
 */
export const zOrderGetOrderResponse = zOrder;
export const zOrderPatchOrdersData = z.object({
    body: z.record(z.string(), z.unknown()),
    path: z.object({
        orderID: z.int(),
    }),
    query: z.optional(z.never()),
});
export const zOrderPostOrderPaymentData = z.object({
    body: zPostPaymentRequest,
    path: z.object({
        orderID: z.int(),
    }),
    query: z.optional(z.never()),
});
export const zOrderPostSendData = z.object({
    body: zSendRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
export const zOrderESignOrderData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        orderID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Order was E-Signed
 */
export const zOrderESignOrderResponse = z.boolean();
export const zOrderGetDeletedData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * A list of deleted orders
 */
export const zOrderGetDeletedResponse = zPageResultOrder;
export const zPartyGetPartyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        partyID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * A party specified by the partyID
 */
export const zPartyGetPartyResponse = zParty;
export const zPartyPatchPartiesData = z.object({
    body: z.record(z.string(), z.unknown()),
    path: z.object({
        partyID: z.int(),
    }),
    query: z.optional(z.never()),
});
export const zPartyGetPartiesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        fullTextSearch: z.optional(z.string()),
    })),
});
/**
 * A list of parties
 */
export const zPartyGetPartiesResponse = zPageResultParty;
export const zPartyPostPartyData = z.object({
    body: zParty,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * Party was created/updated
 */
export const zPartyPostPartyResponse = z.int();
export const zPeppolDeleteParticipantData = z.object({
    body: zDeleteParticipantRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
export const zPeppolPostParticipantData = z.object({
    body: zRegisterParticipantRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
export const zPeppolGetInboxData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        ReceiverCompanyID: z.optional(z.string()),
    })),
});
/**
 * An inbox result with a list of the first 10 items in the inbox
 */
export const zPeppolGetInboxResponse = zInboxGetResult;
export const zPeppolInboxItemConfirmData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        inboxItemId: z.int(),
    }),
    query: z.optional(z.never()),
});
export const zPeppolInboxItemRefuseData = z.object({
    body: zRefusePeppolItemRequest,
    path: z.object({
        inboxItemId: z.int(),
    }),
    query: z.optional(z.never()),
});
export const zPeppolPostSendOrderData = z.object({
    body: zOrder,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * Invoice was sent via Peppol
 */
export const zPeppolPostSendOrderResponse = z.int();
export const zPeppolGetParticipantInformationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        VATorCBE: z.string(),
    }),
    query: z.optional(z.object({
        OnlyCheckDNS: z.optional(z.boolean()),
    })),
});
/**
 * Participant information
 */
export const zPeppolGetParticipantInformationResponse = zParticipantInformationResponse;
export const zProductGetProductData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        productID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * A product specified by the productID
 */
export const zProductGetProductResponse = zProduct;
export const zProductGetProductsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * A list of products
 */
export const zProductGetProductsResponse = zPageResultProduct;
export const zProductPostProductData = z.object({
    body: zProduct,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * Product was created/updated
 */
export const zProductPostProductResponse = z.int();
export const zReportReportListGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * A list of reports
 */
export const zReportReportListGetResponse = z.array(zReportsExportOverViewModel);
export const zReportReportDetailGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        reportID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Result and name of a report
 */
export const zReportReportDetailGetResponse = zReportDetailModel;
export const zToProcessPostToProcessData = z.object({
    body: zToProcessSaveRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * An upload ID
 */
export const zToProcessPostToProcessResponse = z.int();
export const zToProcessDeleteToProcessData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uploadID: z.int(),
    }),
    query: z.optional(z.never()),
});
export const zWebhookGetWebhooksData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * A list of webhooks
 */
export const zWebhookGetWebhooksResponse = z.array(zWebhook);
export const zWebhookPostWebhookData = z.object({
    body: zWebhook,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
/**
 * Webhook was created
 */
export const zWebhookPostWebhookResponse = zWebhook;
export const zWebhookDeleteWebhooksData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        webhookID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Webhook was deleted
 */
export const zWebhookDeleteWebhooksResponse = z.boolean();
export const zWebhookRefreshWebhookSecretData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        webhookID: z.int(),
    }),
    query: z.optional(z.never()),
});
/**
 * Refreshed webhook secret
 */
export const zWebhookRefreshWebhookSecretResponse = z.string();
