// This file is auto-generated by @hey-api/openapi-ts

export const AccountInformationSchema = {
  type: "object",
  properties: {
    Email: {
      type: "string",
    },
    Companies: {
      type: "array",
      items: {
        $ref: "#/definitions/AccountInformationParty",
      },
    },
    UserCompanyRoles: {
      type: "array",
      items: {
        $ref: "#/definitions/UserCompanyRole",
      },
    },
    ExternalProviderID: {
      type: "string",
    },
    ExternalProviderTC: {
      type: "string",
    },
    FirstName: {
      type: "string",
    },
    LastName: {
      type: "string",
    },
    LoginOrRegisterNeeded: {
      type: "boolean",
    },
    NationalIdentityNumber: {
      type: "string",
    },
    CardNumber: {
      type: "string",
    },
    PhoneNumber: {
      type: "string",
    },
    UniqueReference: {
      type: "string",
    },
  },
} as const;

export const AccountInformationPartySchema = {
  type: "object",
  properties: {
    TabNameAlias: {
      type: "string",
    },
    APIAllowed: {
      type: "boolean",
    },
    LogoFileID: {
      format: "uuid",
      type: "string",
      example: "00000000-0000-0000-0000-000000000000",
    },
    APIEnabledFeatures: {
      $ref: "#/definitions/APIEnabledFeatures",
    },
    UserLanguage: {
      type: "string",
    },
    PartyID: {
      format: "int32",
      type: "integer",
    },
    BookYearStart: {
      format: "date-time",
      type: "string",
    },
    Nr: {
      type: "string",
    },
    Name: {
      type: "string",
    },
    CommercialName: {
      type: "string",
    },
    Addresses: {
      type: "array",
      items: {
        $ref: "#/definitions/PartyAddress",
      },
    },
    Street: {
      type: "string",
    },
    StreetNumber: {
      type: "string",
    },
    Box: {
      type: "string",
    },
    Zipcode: {
      type: "string",
    },
    CostCategoryCode: {
      format: "int32",
      type: "integer",
    },
    AccountingCostTypeName: {
      type: "string",
    },
    City: {
      type: "string",
    },
    CountryCode: {
      type: "string",
    },
    IBAN: {
      type: "string",
    },
    BIC: {
      type: "string",
    },
    Mobile: {
      type: "string",
    },
    Phone: {
      type: "string",
    },
    Fax: {
      type: "string",
    },
    Email: {
      type: "string",
    },
    Website: {
      type: "string",
    },
    Contact: {
      type: "string",
    },
    ContactFirstName: {
      type: "string",
    },
    ContactLastName: {
      type: "string",
    },
    VATNumber: {
      type: "string",
    },
    PeppolIdentifier: {
      type: "string",
    },
    RPR: {
      type: "string",
    },
    LastModified: {
      format: "date-time",
      type: "string",
    },
    Created: {
      format: "date-time",
      type: "string",
    },
    PartyType: {
      enum: ["Customer", "Supplier"],
      type: "string",
    },
    VATLiable: {
      type: "boolean",
    },
    AccountantCode: {
      format: "int32",
      type: "integer",
    },
    GLAccountCode: {
      format: "int64",
      type: "integer",
    },
    Language: {
      type: "string",
    },
    VentilationCode: {
      type: "string",
    },
    ExternalProviderID: {
      type: "string",
    },
    ExternalProviderTC: {
      type: "string",
    },
    CustomFields: {
      type: "array",
      items: {
        $ref: "#/definitions/MutableKeyValuePair_StringString",
      },
    },
    BankAccounts: {
      type: "array",
      items: {
        $ref: "#/definitions/BankAccount",
      },
    },
    Users: {
      type: "array",
      items: {
        $ref: "#/definitions/UserCoreInfo",
      },
    },
    DefaultPaymentMethodTC: {
      type: "string",
    },
    DomiciliationMandateID: {
      type: "string",
    },
    DomiciliationMandateSigningDate: {
      format: "date-time",
      type: "string",
    },
    DefaultPaid: {
      type: "boolean",
    },
    DisplayName: {
      type: "string",
    },
    DefaultTransportTypeTC: {
      type: "string",
    },
    FinancialReductionPercentageDefault: {
      format: "double",
      type: "number",
    },
    FinancialReductionDaysDefault: {
      format: "int32",
      type: "integer",
    },
    DefaultExpiryOffset: {
      format: "int32",
      type: "integer",
    },
    GLDefaultExpiryOffset: {
      format: "int64",
      type: "integer",
    },
    Role: {
      type: "string",
    },
    InternalInfo: {
      type: "string",
    },
    VATDeductable: {
      type: "boolean",
    },
    DefaultReductionPercentage: {
      format: "double",
      type: "number",
    },
    Identifiers: {
      type: "array",
      items: {
        $ref: "#/definitions/PartyIdentifier",
      },
    },
    BookCategoryTC: {
      type: "string",
    },
    SmallEnterprise: {
      type: "boolean",
    },
    AutoSendInvoiceReminders: {
      type: "boolean",
    },
    DefaultCurrencyTC: {
      type: "string",
    },
    Regime: {
      type: "string",
    },
    SubRegime: {
      type: "string",
    },
    IsHighRisk: {
      type: "boolean",
    },
    SendUBL: {
      type: "boolean",
    },
    SendPDF: {
      type: "boolean",
    },
  },
} as const;

export const UserCompanyRoleSchema = {
  type: "object",
  properties: {
    PartyID: {
      format: "int32",
      type: "integer",
    },
    UserRoleTypes: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
} as const;

export const APIEnabledFeaturesSchema = {
  type: "object",
  properties: {
    TimeRegistration: {
      type: "boolean",
    },
    Projects: {
      type: "boolean",
    },
    DailyReceipts: {
      type: "boolean",
    },
    FinancialReduction: {
      type: "boolean",
    },
    GLAccounts: {
      type: "boolean",
    },
    Cashbook: {
      type: "boolean",
    },
  },
} as const;

export const PartyAddressSchema = {
  type: "object",
  properties: {
    AddressType: {
      type: "string",
    },
    Tav: {
      type: "string",
    },
    Name: {
      type: "string",
    },
    Street: {
      type: "string",
    },
    StreetNumber: {
      type: "string",
    },
    Box: {
      type: "string",
    },
    Zipcode: {
      type: "string",
    },
    City: {
      type: "string",
    },
    CountryCode: {
      type: "string",
    },
    Phone: {
      type: "string",
    },
  },
} as const;

export const MutableKeyValuePair_StringStringSchema = {
  type: "object",
  properties: {
    Key: {
      type: "string",
    },
    Value: {
      type: "string",
    },
  },
} as const;

export const BankAccountSchema = {
  type: "object",
  properties: {
    IBAN: {
      type: "string",
    },
    BIC: {
      type: "string",
    },
    Currency: {
      type: "string",
    },
    Verified: {
      type: "boolean",
    },
    Name: {
      type: "string",
    },
    Saldo: {
      format: "double",
      type: "number",
    },
    ExternalProviderID: {
      type: "string",
    },
    LogoFileID: {
      format: "uuid",
      type: "string",
      example: "00000000-0000-0000-0000-000000000000",
    },
    LogoFileUrl: {
      type: "string",
    },
    CountryCode: {
      type: "string",
    },
    BankAccountName: {
      type: "string",
    },
    BankProviderStatus: {
      type: "string",
    },
    AccountIdentification: {
      type: "string",
    },
    Active: {
      type: "boolean",
    },
  },
} as const;

export const UserCoreInfoSchema = {
  type: "object",
  properties: {
    FirstName: {
      type: "string",
    },
    LastName: {
      type: "string",
    },
    Role: {
      type: "string",
    },
    ExternalProviderID: {
      type: "string",
    },
  },
} as const;

export const PartyIdentifierSchema = {
  type: "object",
  properties: {
    IdentifierType: {
      type: "string",
    },
    Identifier: {
      type: "string",
    },
    SchemeID: {
      type: "string",
    },
    Preferred: {
      type: "boolean",
    },
  },
} as const;

export const SequenceRequestSchema = {
  type: "object",
  properties: {
    SequenceType: {
      type: "string",
    },
    Consume: {
      type: "boolean",
    },
  },
} as const;

export const RegisterAccountRequestModelSchema = {
  type: "object",
  properties: {
    Company: {
      $ref: "#/definitions/Party",
    },
    AccountSettings: {
      $ref: "#/definitions/AccountSettings",
    },
    License: {
      $ref: "#/definitions/LicenseConfiguration",
    },
  },
} as const;

export const PartySchema = {
  type: "object",
  properties: {
    PartyID: {
      format: "int32",
      type: "integer",
    },
    BookYearStart: {
      format: "date-time",
      type: "string",
    },
    Nr: {
      type: "string",
    },
    Name: {
      type: "string",
    },
    CommercialName: {
      type: "string",
    },
    Addresses: {
      type: "array",
      items: {
        $ref: "#/definitions/PartyAddress",
      },
    },
    Street: {
      type: "string",
    },
    StreetNumber: {
      type: "string",
    },
    Box: {
      type: "string",
    },
    Zipcode: {
      type: "string",
    },
    CostCategoryCode: {
      format: "int32",
      type: "integer",
    },
    AccountingCostTypeName: {
      type: "string",
    },
    City: {
      type: "string",
    },
    CountryCode: {
      type: "string",
    },
    IBAN: {
      type: "string",
    },
    BIC: {
      type: "string",
    },
    Mobile: {
      type: "string",
    },
    Phone: {
      type: "string",
    },
    Fax: {
      type: "string",
    },
    Email: {
      type: "string",
    },
    Website: {
      type: "string",
    },
    Contact: {
      type: "string",
    },
    ContactFirstName: {
      type: "string",
    },
    ContactLastName: {
      type: "string",
    },
    VATNumber: {
      type: "string",
    },
    PeppolIdentifier: {
      type: "string",
    },
    RPR: {
      type: "string",
    },
    LastModified: {
      format: "date-time",
      type: "string",
    },
    Created: {
      format: "date-time",
      type: "string",
    },
    PartyType: {
      enum: ["Customer", "Supplier"],
      type: "string",
    },
    VATLiable: {
      type: "boolean",
    },
    AccountantCode: {
      format: "int32",
      type: "integer",
    },
    GLAccountCode: {
      format: "int64",
      type: "integer",
    },
    Language: {
      type: "string",
    },
    VentilationCode: {
      type: "string",
    },
    ExternalProviderID: {
      type: "string",
    },
    ExternalProviderTC: {
      type: "string",
    },
    CustomFields: {
      type: "array",
      items: {
        $ref: "#/definitions/MutableKeyValuePair_StringString",
      },
    },
    BankAccounts: {
      type: "array",
      items: {
        $ref: "#/definitions/BankAccount",
      },
    },
    Users: {
      type: "array",
      items: {
        $ref: "#/definitions/UserCoreInfo",
      },
    },
    DefaultPaymentMethodTC: {
      type: "string",
    },
    DomiciliationMandateID: {
      type: "string",
    },
    DomiciliationMandateSigningDate: {
      format: "date-time",
      type: "string",
    },
    DefaultPaid: {
      type: "boolean",
    },
    DisplayName: {
      type: "string",
    },
    DefaultTransportTypeTC: {
      type: "string",
    },
    FinancialReductionPercentageDefault: {
      format: "double",
      type: "number",
    },
    FinancialReductionDaysDefault: {
      format: "int32",
      type: "integer",
    },
    DefaultExpiryOffset: {
      format: "int32",
      type: "integer",
    },
    GLDefaultExpiryOffset: {
      format: "int64",
      type: "integer",
    },
    Role: {
      type: "string",
    },
    InternalInfo: {
      type: "string",
    },
    VATDeductable: {
      type: "boolean",
    },
    DefaultReductionPercentage: {
      format: "double",
      type: "number",
    },
    Identifiers: {
      type: "array",
      items: {
        $ref: "#/definitions/PartyIdentifier",
      },
    },
    BookCategoryTC: {
      type: "string",
    },
    SmallEnterprise: {
      type: "boolean",
    },
    AutoSendInvoiceReminders: {
      type: "boolean",
    },
    DefaultCurrencyTC: {
      type: "string",
    },
    Regime: {
      type: "string",
    },
    SubRegime: {
      type: "string",
    },
    IsHighRisk: {
      type: "boolean",
    },
    SendUBL: {
      type: "boolean",
    },
    SendPDF: {
      type: "boolean",
    },
  },
} as const;

export const AccountSettingsSchema = {
  type: "object",
  properties: {
    BulkInputFastForward: {
      type: "boolean",
    },
    SendPeppolInvoiceReceivedMail: {
      type: "boolean",
    },
    ExternalLicenseID: {
      type: "string",
    },
    BulkInputIncomeUBLFastForward: {
      type: "boolean",
    },
    ProcessUBLPrePaidAmount: {
      type: "boolean",
    },
  },
} as const;

export const LicenseConfigurationSchema = {
  type: "object",
  properties: {
    LicenseID: {
      format: "int32",
      type: "integer",
    },
    PeriodID: {
      format: "int32",
      type: "integer",
    },
    Addons: {
      $ref: "#/definitions/LicenseAddons",
    },
  },
} as const;

export const LicenseAddonsSchema = {
  type: "object",
  properties: {
    AmountOfExtraUsers: {
      format: "int32",
      type: "integer",
    },
    AmountOfExtraDocuments: {
      format: "int32",
      type: "integer",
    },
  },
} as const;

export const RegisterAccountResponseSchema = {
  type: "object",
  properties: {
    CompanyID: {
      format: "int32",
      type: "integer",
    },
    APIKey: {
      format: "uuid",
      type: "string",
      example: "00000000-0000-0000-0000-000000000000",
    },
    Users: {
      type: "array",
      items: {
        $ref: "#/definitions/UserIdBundle",
      },
    },
    BankAccounts: {
      type: "array",
      items: {
        $ref: "#/definitions/BankAccountState",
      },
    },
  },
} as const;

export const UserIdBundleSchema = {
  type: "object",
  properties: {
    UserID: {
      format: "int32",
      type: "integer",
    },
    ExternalProviderID: {
      type: "string",
    },
  },
} as const;

export const BankAccountStateSchema = {
  type: "object",
  properties: {
    BankAccountID: {
      format: "int32",
      type: "integer",
    },
    IBAN: {
      type: "string",
    },
    BankAccountName: {
      type: "string",
    },
    Active: {
      type: "boolean",
    },
  },
} as const;

export const UpdateLicenseRequestModelSchema = {
  type: "object",
  properties: {
    CompanyID: {
      format: "int32",
      type: "integer",
    },
    License: {
      $ref: "#/definitions/LicenseConfiguration",
    },
  },
} as const;

export const AddNewLicenseBillableModelSchema = {
  type: "object",
  properties: {
    CompanyID: {
      format: "int32",
      type: "integer",
    },
    AmountOfExtraDocuments: {
      format: "int32",
      type: "integer",
    },
    AmountOfExtraUsers: {
      format: "int32",
      type: "integer",
    },
  },
} as const;

export const FeedSchema = {
  type: "object",
  properties: {
    Name: {
      type: "string",
    },
  },
} as const;

export const FeedItemSchema = {
  type: "object",
  properties: {
    FeedItemID: {
      format: "int32",
      description:
        "The ID of the feeditem itself. Use this ID to confirm that the feed was succesfully processed",
      type: "integer",
    },
    EntityID: {
      format: "int32",
      description:
        "The ID of the order or the ID of the document. Use this ID in the Order or Document API to fetch the data",
      type: "integer",
    },
    EntityType: {
      description: "Order or Document",
      type: "string",
    },
    PartyID: {
      format: "int32",
      description:
        "The ID of the company that uploaded the document. Use this ID in the contextPartyID header when downloading the order or document",
      type: "integer",
    },
  },
} as const;

export const ConfirmRequestSchema = {
  description: "Optional, For logging purpose",
  type: "object",
  properties: {
    RemoteServerName: {
      type: "string",
    },
    RemotePath: {
      type: "string",
    },
  },
} as const;

export const FileDetailsSchema = {
  type: "object",
  properties: {
    FileName: {
      type: "string",
    },
    FileContent: {
      format: "byte",
      description: "Base64 encoded byte array",
      type: "string",
    },
    FileContentSHA256Hash: {
      description: "SHA256 hash of byte array (not the Base64)",
      type: "string",
    },
  },
} as const;

export const CashbookInitializationSchema = {
  type: "object",
  properties: {
    StartDate: {
      format: "date-time",
      type: "string",
    },
    StartBalance: {
      format: "double",
      type: "number",
    },
  },
} as const;

export const CashbookModelSchema = {
  type: "object",
  properties: {
    CashbookID: {
      format: "int32",
      type: "integer",
    },
    Name: {
      type: "string",
    },
    CreationDate: {
      format: "date-time",
      type: "string",
    },
    Saldo: {
      format: "double",
      type: "number",
    },
    LastEntryDate: {
      format: "date-time",
      type: "string",
    },
    Currency: {
      type: "string",
    },
  },
} as const;

export const ODataQueryOptions_CashbookEntrySchema = {
  type: "object",
  properties: {
    IfMatch: {
      type: "object",
      readOnly: true,
    },
    IfNoneMatch: {
      type: "object",
      readOnly: true,
    },
    Context: {
      $ref: "#/definitions/ODataQueryContext",
      readOnly: true,
    },
    Request: {
      type: "object",
      readOnly: true,
    },
    RawValues: {
      $ref: "#/definitions/ODataRawQueryOptions",
      readOnly: true,
    },
    SelectExpand: {
      $ref: "#/definitions/SelectExpandQueryOption",
      readOnly: true,
    },
    Filter: {
      $ref: "#/definitions/FilterQueryOption",
      readOnly: true,
    },
    OrderBy: {
      $ref: "#/definitions/OrderByQueryOption",
      readOnly: true,
    },
    Skip: {
      $ref: "#/definitions/SkipQueryOption",
      readOnly: true,
    },
    Top: {
      $ref: "#/definitions/TopQueryOption",
      readOnly: true,
    },
    InlineCount: {
      $ref: "#/definitions/InlineCountQueryOption",
      readOnly: true,
    },
    Validator: {
      $ref: "#/definitions/ODataQueryValidator",
    },
  },
} as const;

export const ODataQueryContextSchema = {
  type: "object",
  properties: {
    Model: {
      $ref: "#/definitions/IEdmModel",
      readOnly: true,
    },
    ElementType: {
      $ref: "#/definitions/IEdmType",
      readOnly: true,
    },
    ElementClrType: {
      type: "string",
      readOnly: true,
    },
  },
} as const;

export const ODataRawQueryOptionsSchema = {
  type: "object",
  properties: {
    Filter: {
      type: "string",
      readOnly: true,
    },
    OrderBy: {
      type: "string",
      readOnly: true,
    },
    Top: {
      type: "string",
      readOnly: true,
    },
    Skip: {
      type: "string",
      readOnly: true,
    },
    Select: {
      type: "string",
      readOnly: true,
    },
    Expand: {
      type: "string",
      readOnly: true,
    },
    InlineCount: {
      type: "string",
      readOnly: true,
    },
    Format: {
      type: "string",
      readOnly: true,
    },
    SkipToken: {
      type: "string",
      readOnly: true,
    },
  },
} as const;

export const SelectExpandQueryOptionSchema = {
  type: "object",
  properties: {
    Context: {
      $ref: "#/definitions/ODataQueryContext",
      readOnly: true,
    },
    RawSelect: {
      type: "string",
      readOnly: true,
    },
    RawExpand: {
      type: "string",
      readOnly: true,
    },
    Validator: {
      $ref: "#/definitions/SelectExpandQueryValidator",
    },
    SelectExpandClause: {
      $ref: "#/definitions/SelectExpandClause",
      readOnly: true,
    },
  },
} as const;

export const FilterQueryOptionSchema = {
  type: "object",
  properties: {
    Context: {
      $ref: "#/definitions/ODataQueryContext",
      readOnly: true,
    },
    Validator: {
      $ref: "#/definitions/FilterQueryValidator",
    },
    FilterClause: {
      $ref: "#/definitions/FilterClause",
      readOnly: true,
    },
    RawValue: {
      type: "string",
      readOnly: true,
    },
  },
} as const;

export const OrderByQueryOptionSchema = {
  type: "object",
  properties: {
    Context: {
      $ref: "#/definitions/ODataQueryContext",
      readOnly: true,
    },
    OrderByNodes: {
      type: "array",
      items: {
        $ref: "#/definitions/OrderByNode",
      },
      readOnly: true,
    },
    RawValue: {
      type: "string",
      readOnly: true,
    },
    Validator: {
      $ref: "#/definitions/OrderByQueryValidator",
    },
    OrderByClause: {
      $ref: "#/definitions/OrderByClause",
      readOnly: true,
    },
  },
} as const;

export const SkipQueryOptionSchema = {
  type: "object",
  properties: {
    Context: {
      $ref: "#/definitions/ODataQueryContext",
      readOnly: true,
    },
    RawValue: {
      type: "string",
      readOnly: true,
    },
    Value: {
      format: "int32",
      type: "integer",
      readOnly: true,
    },
    Validator: {
      $ref: "#/definitions/SkipQueryValidator",
    },
  },
} as const;

export const TopQueryOptionSchema = {
  type: "object",
  properties: {
    Context: {
      $ref: "#/definitions/ODataQueryContext",
      readOnly: true,
    },
    RawValue: {
      type: "string",
      readOnly: true,
    },
    Value: {
      format: "int32",
      type: "integer",
      readOnly: true,
    },
    Validator: {
      $ref: "#/definitions/TopQueryValidator",
    },
  },
} as const;

export const InlineCountQueryOptionSchema = {
  type: "object",
  properties: {
    Context: {
      $ref: "#/definitions/ODataQueryContext",
      readOnly: true,
    },
    RawValue: {
      type: "string",
      readOnly: true,
    },
    Value: {
      enum: ["None", "AllPages"],
      type: "string",
      readOnly: true,
    },
  },
} as const;

export const ODataQueryValidatorSchema = {
  type: "object",
  properties: {},
} as const;

export const IEdmModelSchema = {
  type: "object",
  properties: {
    SchemaElements: {
      type: "array",
      items: {
        $ref: "#/definitions/IEdmSchemaElement",
      },
      readOnly: true,
    },
    VocabularyAnnotations: {
      type: "array",
      items: {
        $ref: "#/definitions/IEdmVocabularyAnnotation",
      },
      readOnly: true,
    },
    ReferencedModels: {
      type: "array",
      items: {
        $ref: "#/definitions/IEdmModel",
      },
      readOnly: true,
    },
    DirectValueAnnotationsManager: {
      $ref: "#/definitions/IEdmDirectValueAnnotationsManager",
      readOnly: true,
    },
  },
} as const;

export const IEdmTypeSchema = {
  type: "object",
  properties: {
    TypeKind: {
      enum: [
        "None",
        "Primitive",
        "Entity",
        "Complex",
        "Row",
        "Collection",
        "EntityReference",
        "Enum",
      ],
      type: "string",
      readOnly: true,
    },
  },
} as const;

export const SelectExpandQueryValidatorSchema = {
  type: "object",
  properties: {},
} as const;

export const SelectExpandClauseSchema = {
  type: "object",
  properties: {
    SelectedItems: {
      type: "array",
      items: {
        $ref: "#/definitions/SelectItem",
      },
      readOnly: true,
    },
    AllSelected: {
      type: "boolean",
      readOnly: true,
    },
  },
} as const;

export const FilterQueryValidatorSchema = {
  type: "object",
  properties: {},
} as const;

export const FilterClauseSchema = {
  type: "object",
  properties: {
    Expression: {
      $ref: "#/definitions/SingleValueNode",
      readOnly: true,
    },
    RangeVariable: {
      $ref: "#/definitions/RangeVariable",
      readOnly: true,
    },
    ItemType: {
      $ref: "#/definitions/IEdmTypeReference",
      readOnly: true,
    },
  },
} as const;

export const OrderByNodeSchema = {
  type: "object",
  properties: {
    Direction: {
      enum: ["Ascending", "Descending"],
      type: "string",
      readOnly: true,
    },
  },
} as const;

export const OrderByQueryValidatorSchema = {
  type: "object",
  properties: {},
} as const;

export const OrderByClauseSchema = {
  type: "object",
  properties: {
    ThenBy: {
      $ref: "#/definitions/OrderByClause",
      readOnly: true,
    },
    Expression: {
      $ref: "#/definitions/SingleValueNode",
      readOnly: true,
    },
    Direction: {
      enum: ["Ascending", "Descending"],
      type: "string",
      readOnly: true,
    },
    RangeVariable: {
      $ref: "#/definitions/RangeVariable",
      readOnly: true,
    },
    ItemType: {
      $ref: "#/definitions/IEdmTypeReference",
      readOnly: true,
    },
  },
} as const;

export const SkipQueryValidatorSchema = {
  type: "object",
  properties: {},
} as const;

export const TopQueryValidatorSchema = {
  type: "object",
  properties: {},
} as const;

export const IEdmSchemaElementSchema = {
  type: "object",
  properties: {
    SchemaElementKind: {
      enum: ["None", "TypeDefinition", "Function", "ValueTerm", "EntityContainer"],
      type: "string",
      readOnly: true,
    },
    Namespace: {
      type: "string",
      readOnly: true,
    },
    Name: {
      type: "string",
      readOnly: true,
    },
  },
} as const;

export const IEdmVocabularyAnnotationSchema = {
  type: "object",
  properties: {
    Qualifier: {
      type: "string",
      readOnly: true,
    },
    Term: {
      $ref: "#/definitions/IEdmTerm",
      readOnly: true,
    },
    Target: {
      $ref: "#/definitions/IEdmVocabularyAnnotatable",
      readOnly: true,
    },
  },
} as const;

export const IEdmDirectValueAnnotationsManagerSchema = {
  type: "object",
  properties: {},
} as const;

export const SelectItemSchema = {
  type: "object",
  properties: {},
} as const;

export const SingleValueNodeSchema = {
  type: "object",
  properties: {
    TypeReference: {
      $ref: "#/definitions/IEdmTypeReference",
      readOnly: true,
    },
    Kind: {
      enum: [
        "None",
        "Constant",
        "Convert",
        "NonentityRangeVariableReference",
        "BinaryOperator",
        "UnaryOperator",
        "SingleValuePropertyAccess",
        "CollectionPropertyAccess",
        "SingleValueFunctionCall",
        "Any",
        "CollectionNavigationNode",
        "SingleNavigationNode",
        "SingleValueOpenPropertyAccess",
        "SingleEntityCast",
        "All",
        "EntityCollectionCast",
        "EntityRangeVariableReference",
        "SingleEntityFunctionCall",
        "CollectionFunctionCall",
        "EntityCollectionFunctionCall",
        "NamedFunctionParameter",
      ],
      type: "string",
      readOnly: true,
    },
  },
} as const;

export const RangeVariableSchema = {
  type: "object",
  properties: {
    Name: {
      type: "string",
      readOnly: true,
    },
    TypeReference: {
      $ref: "#/definitions/IEdmTypeReference",
      readOnly: true,
    },
    Kind: {
      format: "int32",
      type: "integer",
      readOnly: true,
    },
  },
} as const;

export const IEdmTypeReferenceSchema = {
  type: "object",
  properties: {
    IsNullable: {
      type: "boolean",
      readOnly: true,
    },
    Definition: {
      $ref: "#/definitions/IEdmType",
      readOnly: true,
    },
  },
} as const;

export const IEdmTermSchema = {
  type: "object",
  properties: {
    TermKind: {
      enum: ["None", "Type", "Value"],
      type: "string",
      readOnly: true,
    },
    SchemaElementKind: {
      enum: ["None", "TypeDefinition", "Function", "ValueTerm", "EntityContainer"],
      type: "string",
      readOnly: true,
    },
    Namespace: {
      type: "string",
      readOnly: true,
    },
    Name: {
      type: "string",
      readOnly: true,
    },
  },
} as const;

export const IEdmVocabularyAnnotatableSchema = {
  type: "object",
  properties: {},
} as const;

export const PageResult_CashbookEntrySchema = {
  type: "object",
  properties: {
    Items: {
      type: "array",
      items: {
        $ref: "#/definitions/CashbookEntry",
      },
    },
    NextPageLink: {
      type: "string",
    },
    Count: {
      format: "int64",
      type: "integer",
    },
  },
} as const;

export const CashbookEntrySchema = {
  type: "object",
  properties: {
    TransactionDate: {
      format: "date-time",
      type: "string",
    },
    EntryType: {
      type: "string",
    },
    Note: {
      type: "string",
    },
    InternalInformation: {
      type: "string",
    },
    Direction: {
      type: "string",
    },
    Amount: {
      format: "double",
      type: "number",
    },
  },
} as const;

export const DailyReceiptBookEntryModelSchema = {
  type: "object",
  properties: {
    Description: {
      type: "string",
    },
    VATPercentage: {
      format: "double",
      type: "number",
    },
    TotalIncl: {
      format: "double",
      type: "number",
    },
    InputDate: {
      format: "date-time",
      type: "string",
    },
    VentilationCodeTC: {
      type: "string",
    },
  },
} as const;

export const PostDailyReceiptBookEntryResponseModelSchema = {
  type: "object",
  properties: {
    CashbookId: {
      format: "int32",
      type: "integer",
    },
    CashbookEntryId: {
      format: "int32",
      type: "integer",
    },
  },
} as const;

export const GetDailyReceiptEntryResponseModelSchema = {
  type: "object",
  properties: {
    CashbookEntryID: {
      format: "int32",
      type: "integer",
    },
    CashbookID: {
      format: "int32",
      type: "integer",
    },
    VAT: {
      format: "double",
      type: "number",
    },
    Description: {
      type: "string",
    },
    Orderid: {
      format: "int32",
      type: "integer",
    },
    TotalIncl: {
      format: "double",
      type: "number",
    },
    TotalExcl: {
      format: "double",
      type: "number",
    },
    TotalVAT: {
      format: "double",
      type: "number",
    },
  },
} as const;

export const DailyReceiptBookModelResponseModelSchema = {
  type: "object",
  properties: {
    Cashbooks: {
      type: "array",
      items: {
        $ref: "#/definitions/Cashbook",
      },
    },
    CashbookEntries: {
      type: "array",
      items: {
        $ref: "#/definitions/GetDailyReceiptEntryResponseModel",
      },
    },
  },
} as const;

export const CashbookSchema = {
  type: "object",
  properties: {
    CashbookID: {
      format: "int32",
      type: "integer",
    },
    FromDate: {
      format: "date-time",
      type: "string",
    },
    Closed: {
      type: "boolean",
    },
  },
} as const;

export const DocumentSchema = {
  type: "object",
  properties: {
    DocumentID: {
      format: "int32",
      type: "integer",
    },
    CompanyID: {
      format: "int32",
      type: "integer",
    },
    File: {
      $ref: "#/definitions/File",
    },
    Name: {
      type: "string",
    },
    Description: {
      type: "string",
    },
    DocumentDate: {
      format: "date-time",
      type: "string",
    },
    CreationDate: {
      format: "date-time",
      type: "string",
    },
    Tags: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
} as const;

export const FileSchema = {
  type: "object",
  properties: {
    FileID: {
      format: "uuid",
      type: "string",
      example: "00000000-0000-0000-0000-000000000000",
    },
    FileName: {
      type: "string",
    },
    MimeType: {
      type: "string",
    },
    FileContent: {
      format: "byte",
      type: "string",
    },
  },
} as const;

export const ODataQueryOptions_DocumentAPIViewSchema = {
  type: "object",
  properties: {
    IfMatch: {
      type: "object",
      readOnly: true,
    },
    IfNoneMatch: {
      type: "object",
      readOnly: true,
    },
    Context: {
      $ref: "#/definitions/ODataQueryContext",
      readOnly: true,
    },
    Request: {
      type: "object",
      readOnly: true,
    },
    RawValues: {
      $ref: "#/definitions/ODataRawQueryOptions",
      readOnly: true,
    },
    SelectExpand: {
      $ref: "#/definitions/SelectExpandQueryOption",
      readOnly: true,
    },
    Filter: {
      $ref: "#/definitions/FilterQueryOption",
      readOnly: true,
    },
    OrderBy: {
      $ref: "#/definitions/OrderByQueryOption",
      readOnly: true,
    },
    Skip: {
      $ref: "#/definitions/SkipQueryOption",
      readOnly: true,
    },
    Top: {
      $ref: "#/definitions/TopQueryOption",
      readOnly: true,
    },
    InlineCount: {
      $ref: "#/definitions/InlineCountQueryOption",
      readOnly: true,
    },
    Validator: {
      $ref: "#/definitions/ODataQueryValidator",
    },
  },
} as const;

export const PageResult_DocumentAPIViewSchema = {
  type: "object",
  properties: {
    Items: {
      type: "array",
      items: {
        $ref: "#/definitions/DocumentAPIView",
      },
    },
    NextPageLink: {
      type: "string",
    },
    Count: {
      format: "int64",
      type: "integer",
    },
  },
} as const;

export const DocumentAPIViewSchema = {
  type: "object",
  properties: {
    DocumentID: {
      format: "int32",
      type: "integer",
    },
    CompanyID: {
      format: "int32",
      type: "integer",
    },
    File: {
      $ref: "#/definitions/File",
    },
    Name: {
      type: "string",
    },
    Description: {
      type: "string",
    },
    DocumentDate: {
      format: "date-time",
      type: "string",
    },
    CreationDate: {
      format: "date-time",
      type: "string",
    },
    Tags: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
} as const;

export const EinvoiceRegistrationPostSchema = {
  type: "object",
  properties: {
    TaxIdentifier: {
      type: "string",
    },
    CompanyName: {
      type: "string",
    },
    CommercialName: {
      type: "string",
    },
    Addresses: {
      type: "array",
      items: {
        $ref: "#/definitions/PartyAddress",
      },
    },
    TaxDeductable: {
      type: "boolean",
    },
    TaxLiable: {
      type: "boolean",
    },
    IBAN: {
      type: "string",
    },
    BIC: {
      type: "string",
    },
    Mobile: {
      type: "string",
    },
    Phone: {
      type: "string",
    },
    Email: {
      type: "string",
    },
    ContactFirstName: {
      type: "string",
    },
    ContactLastName: {
      type: "string",
    },
    Language: {
      type: "string",
    },
    Identifiers: {
      type: "array",
      items: {
        $ref: "#/definitions/PartyIdentifier",
      },
    },
    AccountSettings: {
      $ref: "#/definitions/EinvoiceAccountSettings",
    },
  },
} as const;

export const EinvoiceAccountSettingsSchema = {
  type: "object",
  properties: {
    ProcessUBLPrePaidAmount: {
      type: "boolean",
    },
  },
} as const;

export const AccountRegistrationResponseSchema = {
  type: "object",
  properties: {
    RegistrationID: {
      format: "int32",
      type: "integer",
    },
  },
} as const;

export const GetEinvoiceAccountsReponseSchema = {
  type: "object",
  properties: {
    Companies: {
      type: "array",
      items: {
        $ref: "#/definitions/EinvoiceRegistrationsAccount",
      },
    },
  },
} as const;

export const EinvoiceRegistrationsAccountSchema = {
  type: "object",
  properties: {
    RegistrationID: {
      format: "int32",
      type: "integer",
    },
    CompanyDetails: {
      $ref: "#/definitions/EinvoiceRegistrationPost",
    },
    Integrations: {
      type: "array",
      items: {
        $ref: "#/definitions/EinvoiceIntegration",
      },
    },
  },
} as const;

export const EinvoiceIntegrationSchema = {
  type: "object",
  properties: {
    IntegrationID: {
      format: "int32",
      type: "integer",
    },
    Integration: {
      type: "string",
    },
    IntegrationStatus: {
      type: "string",
    },
    IntegrationStatusDescription: {
      type: "string",
    },
    IntegrationDocumentToSign: {
      type: "string",
    },
  },
} as const;

export const IntegrationPostSchema = {
  type: "object",
  properties: {
    Externalprovider: {
      type: "string",
    },
    Credentials: {
      type: "object",
      additionalProperties: {
        type: "string",
      },
    },
    Certificates: {
      type: "object",
      additionalProperties: {
        $ref: "#/definitions/File",
      },
    },
  },
} as const;

export const CreateAndSendEDocumentPostSchema = {
  type: "object",
  properties: {
    TransportType: {
      type: "string",
    },
    Order: {
      $ref: "#/definitions/Order",
    },
  },
} as const;

export const OrderSchema = {
  type: "object",
  properties: {
    OrderID: {
      format: "int32",
      type: "integer",
    },
    CompanyID: {
      format: "int32",
      type: "integer",
    },
    OrderPDF: {
      $ref: "#/definitions/File",
    },
    Attachments: {
      type: "array",
      items: {
        $ref: "#/definitions/File",
      },
    },
    OrderNumber: {
      type: "string",
    },
    CustomerID: {
      format: "int32",
      type: "integer",
    },
    SupplierID: {
      format: "int32",
      type: "integer",
    },
    CounterPartyID: {
      format: "int32",
      type: "integer",
    },
    Customer: {
      $ref: "#/definitions/Party",
    },
    Supplier: {
      $ref: "#/definitions/Party",
    },
    CounterParty: {
      $ref: "#/definitions/Party",
    },
    OrderDate: {
      format: "date-time",
      type: "string",
    },
    ExpiryDate: {
      format: "date-time",
      type: "string",
    },
    OrderType: {
      type: "string",
    },
    LastModified: {
      format: "date-time",
      type: "string",
    },
    Created: {
      format: "date-time",
      type: "string",
    },
    OrderDirection: {
      type: "string",
    },
    OrderLines: {
      type: "array",
      items: {
        $ref: "#/definitions/OrderLine",
      },
    },
    BookingEntries: {
      type: "array",
      items: {
        $ref: "#/definitions/BookingEntry",
      },
    },
    Journal: {
      type: "string",
    },
    OrderTitle: {
      type: "string",
    },
    PaymentDiscountPercentage: {
      format: "double",
      type: "number",
    },
    PaymentDiscountAmount: {
      format: "double",
      type: "number",
    },
    PaymentReductionDays: {
      format: "int32",
      type: "integer",
    },
    PaymentDiscountDate: {
      format: "date-time",
      type: "string",
    },
    VatGroups: {
      type: "array",
      items: {
        $ref: "#/definitions/VatGroup",
      },
    },
    VentilationCode: {
      type: "string",
    },
    TotalExcl: {
      format: "double",
      type: "number",
    },
    TotalIncl: {
      format: "double",
      type: "number",
    },
    TotalVAT: {
      format: "double",
      type: "number",
    },
    Reference: {
      type: "string",
    },
    Tags: {
      type: "array",
      items: {
        type: "string",
      },
    },
    DepartmentID: {
      format: "int32",
      type: "integer",
    },
    PaymentReference: {
      type: "string",
    },
    AboutInvoiceNumber: {
      type: "string",
    },
    OCRRawText: {
      type: "string",
    },
    OCRMetaPages: {
      type: "array",
      items: {
        $ref: "#/definitions/OCRPage",
      },
    },
    Paid: {
      type: "boolean",
    },
    PaidDate: {
      format: "date-time",
      type: "string",
    },
    ExternalProviderID: {
      type: "string",
    },
    ExternalProvider: {
      type: "string",
    },
    ProjectID: {
      format: "int32",
      type: "integer",
    },
    ProjectName: {
      type: "string",
    },
    ExternalProviderReferences: {
      type: "array",
      items: {
        $ref: "#/definitions/ExternalProviderReference",
      },
    },
    Comments: {
      type: "string",
    },
    Currency: {
      type: "string",
    },
    VatDeduction: {
      format: "double",
      type: "number",
    },
    MixedUseProfessionalPercentage: {
      format: "double",
      type: "number",
    },
    InternalInfo: {
      type: "string",
    },
    IsSent: {
      type: "boolean",
    },
    Invoiced: {
      type: "boolean",
    },
    CustomFields: {
      type: "object",
      additionalProperties: {
        type: "string",
      },
    },
    PeriodFrom: {
      format: "date-time",
      type: "string",
    },
    PeriodTill: {
      format: "date-time",
      type: "string",
    },
    CostCategoryCode: {
      format: "int32",
      type: "integer",
    },
    AccountCode: {
      format: "int32",
      type: "integer",
    },
    AccountingCostTypeTC: {
      type: "string",
    },
    LastReminder: {
      format: "date-time",
      type: "string",
    },
    RemindersSent: {
      format: "int32",
      type: "integer",
    },
    ToPay: {
      format: "double",
      type: "number",
    },
    OrderStatus: {
      type: "string",
    },
    ApprovalStatus: {
      type: "string",
    },
    Overdue: {
      type: "boolean",
    },
    DaysOverdue: {
      format: "int32",
      type: "integer",
    },
    FXRateToForeign: {
      format: "double",
      type: "number",
    },
    PaymentMethod: {
      type: "string",
    },
    DeliveryDate: {
      format: "date-time",
      type: "string",
    },
    ExportedToConnector: {
      type: "boolean",
    },
    PaymentLinks: {
      type: "array",
      items: {
        $ref: "#/definitions/PaymentLink",
      },
    },
    TemplateID: {
      format: "int32",
      type: "integer",
    },
    MessageTemplateID: {
      format: "int32",
      type: "integer",
    },
    AnalyticCostBearer: {
      type: "string",
    },
    AnalyticCostCenter: {
      type: "string",
    },
    AccountantVerificationNeeded: {
      type: "boolean",
    },
    CurrentDocumentDeliveryDetails: {
      $ref: "#/definitions/DocumentDeliveryDetails",
    },
    Messages: {
      type: "array",
      items: {
        $ref: "#/definitions/OrderMessage",
      },
    },
    AdditionalDocumentReference: {
      type: "array",
      items: {
        $ref: "#/definitions/AdditionalDocuments",
      },
    },
    PaymentTerms: {
      type: "string",
    },
    ContractDocumentReference: {
      type: "array",
      items: {
        $ref: "#/definitions/ContractDocumentReference",
      },
    },
    TaxPointDate: {
      format: "date-time",
      type: "string",
    },
    CategoryFieldItems: {
      type: "array",
      items: {
        $ref: "#/definitions/CategoryFieldItem",
      },
    },
    Signature: {
      $ref: "#/definitions/EInvoiceSignatureModel",
    },
  },
} as const;

export const OrderLineSchema = {
  type: "object",
  properties: {
    Quantity: {
      format: "double",
      type: "number",
    },
    UnitPriceExcl: {
      format: "double",
      type: "number",
    },
    AccountCode: {
      format: "int32",
      type: "integer",
    },
    Reference: {
      type: "string",
    },
    Description: {
      type: "string",
    },
    TotalExcl: {
      format: "double",
      type: "number",
    },
    TotalVAT: {
      format: "double",
      type: "number",
    },
    VATPercentage: {
      format: "double",
      type: "number",
    },
    VentilationCode: {
      type: "string",
    },
    ProductID: {
      format: "int32",
      type: "integer",
    },
    Unit: {
      type: "string",
    },
    CustomFields: {
      type: "object",
      additionalProperties: {
        type: "string",
      },
    },
    ExternalProviderReferences: {
      type: "array",
      items: {
        $ref: "#/definitions/ExternalProviderReference",
      },
    },
    InclLeading: {
      type: "boolean",
    },
    UnitPriceIncl: {
      format: "double",
      type: "number",
    },
    TotalIncl: {
      format: "double",
      type: "number",
    },
    AnalyticCostBearer: {
      type: "string",
    },
    AnalyticCostCenter: {
      type: "string",
    },
    ReductionPercentage: {
      format: "double",
      type: "number",
    },
    DescriptionExtended: {
      type: "string",
    },
  },
} as const;

export const BookingEntrySchema = {
  type: "object",
  properties: {
    BookingEntryID: {
      format: "int32",
      type: "integer",
    },
    OrderID: {
      format: "int32",
      type: "integer",
    },
    AccountCode: {
      format: "int32",
      type: "integer",
    },
    Amount: {
      format: "double",
      type: "number",
    },
    DebetOrCredit: {
      type: "string",
    },
    VAT1: {
      format: "int32",
      type: "integer",
    },
    VAT2: {
      format: "int32",
      type: "integer",
    },
    VAT3: {
      format: "int32",
      type: "integer",
    },
  },
} as const;

export const VatGroupSchema = {
  type: "object",
  properties: {
    VentilationCode: {
      type: "string",
    },
    VATPercentage: {
      format: "double",
      type: "number",
    },
    TotalExcl: {
      format: "double",
      type: "number",
    },
    TotalVAT: {
      format: "double",
      type: "number",
    },
    TotalIncl: {
      format: "double",
      type: "number",
    },
    Mtvh: {
      format: "double",
      type: "number",
    },
    FinancialReductionAmount: {
      format: "double",
      type: "number",
    },
  },
} as const;

export const OCRPageSchema = {
  type: "object",
  properties: {
    TextList: {
      type: "array",
      items: {
        $ref: "#/definitions/OCRText",
      },
    },
  },
} as const;

export const ExternalProviderReferenceSchema = {
  type: "object",
  properties: {
    ExternalProvider: {
      type: "string",
    },
    Category: {
      type: "string",
    },
    Value: {
      type: "string",
    },
    EntityType: {
      type: "string",
    },
    EntityID: {
      format: "int32",
      type: "integer",
    },
  },
} as const;

export const PaymentLinkSchema = {
  type: "object",
  properties: {
    ExternalProvider: {
      type: "string",
    },
    ClickUrl: {
      type: "string",
    },
    QRImageUrl: {
      type: "string",
    },
  },
} as const;

export const DocumentDeliveryDetailsSchema = {
  type: "object",
  properties: {
    DocumentRefusedDate: {
      format: "date-time",
      type: "string",
    },
    DocumentDeliveryDate: {
      format: "date-time",
      type: "string",
    },
    DocumentDeliveryInfo: {
      type: "string",
    },
    DocumentRefusedReasonTC: {
      type: "string",
    },
    DocumentRefusedInfo: {
      type: "string",
    },
    IsDocumentDelivered: {
      type: "boolean",
    },
    DocumentDeliveryStatus: {
      type: "string",
    },
  },
} as const;

export const OrderMessageSchema = {
  type: "object",
  properties: {
    OrderID: {
      format: "int32",
      type: "integer",
    },
    Description: {
      type: "string",
    },
    FileID: {
      format: "uuid",
      type: "string",
      example: "00000000-0000-0000-0000-000000000000",
    },
    CreationDate: {
      format: "date-time",
      type: "string",
    },
    TransportType: {
      type: "string",
    },
    Success: {
      type: "boolean",
    },
    Trials: {
      format: "int32",
      type: "integer",
    },
    Destination: {
      type: "string",
    },
    MessageDirection: {
      type: "string",
    },
  },
} as const;

export const AdditionalDocumentsSchema = {
  type: "object",
  properties: {
    DocumentDescription: {
      type: "string",
    },
    ID: {
      type: "string",
    },
    DocumentType: {
      type: "string",
    },
    Attachment: {
      $ref: "#/definitions/File",
    },
    CustomFields: {
      type: "object",
      additionalProperties: {
        type: "string",
      },
    },
  },
} as const;

export const ContractDocumentReferenceSchema = {
  type: "object",
  properties: {
    ID: {
      type: "string",
    },
  },
} as const;

export const CategoryFieldItemSchema = {
  type: "object",
  properties: {
    Value: {
      type: "string",
    },
    Name: {
      type: "string",
    },
  },
} as const;

export const EInvoiceSignatureModelSchema = {
  type: "object",
  properties: {
    OrginalString: {
      type: "string",
    },
    NetworkCertificateNumber: {
      type: "string",
    },
    DocumentCertificateNumber: {
      type: "string",
    },
    UUID: {
      type: "string",
    },
    NetworkStamp: {
      type: "string",
    },
    DocumentStamp: {
      type: "string",
    },
    DateTimeInfo: {
      $ref: "#/definitions/TimezoneInfo",
    },
    QRCode: {
      type: "string",
    },
    Cfdi: {
      type: "string",
    },
    StampUrl: {
      type: "string",
    },
  },
} as const;

export const OCRTextSchema = {
  type: "object",
  properties: {
    Text: {
      type: "string",
    },
    X: {
      format: "double",
      type: "number",
    },
    Y: {
      format: "double",
      type: "number",
    },
    Width: {
      format: "double",
      type: "number",
    },
    Height: {
      format: "double",
      type: "number",
    },
  },
} as const;

export const TimezoneInfoSchema = {
  type: "object",
  properties: {
    TimeZoneInfo: {
      type: "string",
    },
    DateTime: {
      format: "date-time",
      type: "string",
    },
  },
} as const;

export const CreateAndSendEdocumentResponseSchema = {
  type: "object",
  properties: {
    OrderID: {
      format: "int32",
      type: "integer",
    },
    TranssportStatus: {
      format: "int32",
      type: "integer",
    },
    TransportMessages: {
      type: "array",
      items: {
        $ref: "#/definitions/Error",
      },
    },
  },
} as const;

export const ErrorSchema = {
  type: "object",
  properties: {
    ErrorEnum: {
      type: "string",
    },
    ErrorParams: {
      type: "array",
      items: {
        type: "object",
      },
    },
    ErrorMessage: {
      type: "string",
    },
    Append: {
      type: "string",
    },
    DefaultText: {
      type: "string",
    },
  },
} as const;

export const ODataQueryOptions_OrderSchema = {
  type: "object",
  properties: {
    IfMatch: {
      type: "object",
      readOnly: true,
    },
    IfNoneMatch: {
      type: "object",
      readOnly: true,
    },
    Context: {
      $ref: "#/definitions/ODataQueryContext",
      readOnly: true,
    },
    Request: {
      type: "object",
      readOnly: true,
    },
    RawValues: {
      $ref: "#/definitions/ODataRawQueryOptions",
      readOnly: true,
    },
    SelectExpand: {
      $ref: "#/definitions/SelectExpandQueryOption",
      readOnly: true,
    },
    Filter: {
      $ref: "#/definitions/FilterQueryOption",
      readOnly: true,
    },
    OrderBy: {
      $ref: "#/definitions/OrderByQueryOption",
      readOnly: true,
    },
    Skip: {
      $ref: "#/definitions/SkipQueryOption",
      readOnly: true,
    },
    Top: {
      $ref: "#/definitions/TopQueryOption",
      readOnly: true,
    },
    InlineCount: {
      $ref: "#/definitions/InlineCountQueryOption",
      readOnly: true,
    },
    Validator: {
      $ref: "#/definitions/ODataQueryValidator",
    },
  },
} as const;

export const PageResult_OrderSchema = {
  type: "object",
  properties: {
    Items: {
      type: "array",
      items: {
        $ref: "#/definitions/Order",
      },
    },
    NextPageLink: {
      type: "string",
    },
    Count: {
      format: "int64",
      type: "integer",
    },
  },
} as const;

export const WebhookSchema = {
  type: "object",
  properties: {
    WebhookID: {
      format: "int32",
      type: "integer",
    },
    CompanyID: {
      format: "int32",
      type: "integer",
    },
    UserID: {
      format: "int32",
      type: "integer",
    },
    EntityType: {
      type: "string",
    },
    EntityUpdateType: {
      type: "string",
    },
    WebhookURL: {
      type: "string",
    },
    Secret: {
      type: "string",
    },
  },
} as const;

export const KYCInitiationPostSchema = {
  type: "object",
  properties: {
    IdentificationProviderTC: {
      type: "string",
    },
    RedirectURL: {
      type: "string",
    },
  },
} as const;

export const KYCInitiationResponseSchema = {
  type: "object",
  properties: {
    URL: {
      type: "string",
    },
  },
} as const;

export const TransactionSchema = {
  type: "object",
  properties: {
    BankAccountTransactionID: {
      format: "int32",
      type: "integer",
    },
    BankName: {
      type: "string",
    },
    IBAN: {
      type: "string",
    },
    BIC: {
      type: "string",
    },
    BankAccountID: {
      format: "int32",
      type: "integer",
    },
    DocumentId: {
      format: "int32",
      type: "integer",
    },
    IBANCounterParty: {
      type: "string",
    },
    BICCounterParty: {
      type: "string",
    },
    NameCounterParty: {
      type: "string",
    },
    TotalAmount: {
      format: "double",
      type: "number",
    },
    TransactionType: {
      type: "string",
    },
    ValueDate: {
      format: "date-time",
      type: "string",
    },
    Currency: {
      type: "string",
    },
    Description: {
      type: "string",
    },
    ExternalProviderID: {
      type: "string",
    },
    ExternalProviderTC: {
      type: "string",
    },
    FreeMessage: {
      type: "string",
    },
    CodaSource: {
      type: "string",
    },
    CodaFileID: {
      format: "uuid",
      type: "string",
      example: "00000000-0000-0000-0000-000000000000",
    },
    BankReference: {
      type: "string",
    },
    ClientReference: {
      type: "string",
    },
    Note: {
      type: "string",
    },
    AssignedEntities: {
      type: "array",
      items: {
        $ref: "#/definitions/AssignedEntity",
      },
    },
    ProprietaryBankTransactionCode: {
      type: "string",
    },
    BankTransactionCode: {
      type: "string",
    },
  },
} as const;

export const AssignedEntitySchema = {
  type: "object",
  properties: {
    AssignedAmount: {
      format: "double",
      type: "number",
    },
    FXRateToBankCurrency: {
      format: "double",
      type: "number",
    },
    EntityType: {
      type: "string",
    },
    EntityID: {
      format: "int32",
      type: "integer",
    },
  },
} as const;

export const ODataQueryOptions_TransactionSchema = {
  type: "object",
  properties: {
    IfMatch: {
      type: "object",
      readOnly: true,
    },
    IfNoneMatch: {
      type: "object",
      readOnly: true,
    },
    Context: {
      $ref: "#/definitions/ODataQueryContext",
      readOnly: true,
    },
    Request: {
      type: "object",
      readOnly: true,
    },
    RawValues: {
      $ref: "#/definitions/ODataRawQueryOptions",
      readOnly: true,
    },
    SelectExpand: {
      $ref: "#/definitions/SelectExpandQueryOption",
      readOnly: true,
    },
    Filter: {
      $ref: "#/definitions/FilterQueryOption",
      readOnly: true,
    },
    OrderBy: {
      $ref: "#/definitions/OrderByQueryOption",
      readOnly: true,
    },
    Skip: {
      $ref: "#/definitions/SkipQueryOption",
      readOnly: true,
    },
    Top: {
      $ref: "#/definitions/TopQueryOption",
      readOnly: true,
    },
    InlineCount: {
      $ref: "#/definitions/InlineCountQueryOption",
      readOnly: true,
    },
    Validator: {
      $ref: "#/definitions/ODataQueryValidator",
    },
  },
} as const;

export const PageResult_TransactionSchema = {
  type: "object",
  properties: {
    Items: {
      type: "array",
      items: {
        $ref: "#/definitions/Transaction",
      },
    },
    NextPageLink: {
      type: "string",
    },
    Count: {
      format: "int64",
      type: "integer",
    },
  },
} as const;

export const GLAccountSchema = {
  type: "object",
  properties: {
    Code: {
      format: "int32",
      type: "integer",
    },
    Description: {
      type: "string",
    },
    GLAccountType: {
      type: "string",
    },
  },
} as const;

export const JournalSchema = {
  type: "object",
  properties: {
    Code: {
      type: "string",
    },
    Description: {
      type: "string",
    },
    JournalType: {
      enum: ["Income", "Cost"],
      type: "string",
    },
  },
} as const;

export const CompanySearchResultSchema = {
  type: "object",
  properties: {
    Items: {
      type: "array",
      items: {
        $ref: "#/definitions/CompanySearchResultItem",
      },
    },
  },
} as const;

export const CompanySearchResultItemSchema = {
  type: "object",
  properties: {
    Source: {
      description: "Either KBO or VIES",
      type: "string",
    },
    CompanyIdentification: {
      type: "string",
    },
    Street: {
      type: "string",
    },
    Number: {
      type: "string",
    },
    Name: {
      type: "string",
    },
    Zipcode: {
      type: "string",
    },
    City: {
      type: "string",
    },
    Box: {
      type: "string",
    },
    Country: {
      type: "string",
    },
    StartDate: {
      format: "date-time",
      type: "string",
    },
    CommercialName: {
      type: "string",
    },
  },
} as const;

export const TypeCodeResultSchema = {
  type: "object",
  properties: {
    Items: {
      type: "array",
      items: {
        $ref: "#/definitions/TypeCodeResultItem",
      },
    },
  },
} as const;

export const TypeCodeResultItemSchema = {
  type: "object",
  properties: {
    Key: {
      type: "string",
    },
    Value: {
      type: "string",
    },
  },
} as const;

export const OAuthAccessTokenRequestSchema = {
  type: "object",
  properties: {
    client_id: {
      type: "string",
    },
    client_secret: {
      type: "string",
    },
    code: {
      type: "string",
    },
    grant_type: {
      type: "string",
    },
    redirect_uri: {
      type: "string",
    },
    refresh_token: {
      type: "string",
    },
    state: {
      type: "string",
    },
  },
} as const;

export const PostPaymentRequestSchema = {
  type: "object",
  properties: {
    Amount: {
      format: "double",
      type: "number",
    },
    Description: {
      type: "string",
    },
    Date: {
      format: "date-time",
      type: "string",
    },
  },
} as const;

export const SendRequestSchema = {
  type: "object",
  properties: {
    OrderIds: {
      type: "array",
      items: {
        format: "int32",
        type: "integer",
      },
    },
    TransportType: {
      type: "string",
    },
    PrintType: {
      type: "string",
    },
  },
} as const;

export const ODataQueryOptions_PartySchema = {
  type: "object",
  properties: {
    IfMatch: {
      type: "object",
      readOnly: true,
    },
    IfNoneMatch: {
      type: "object",
      readOnly: true,
    },
    Context: {
      $ref: "#/definitions/ODataQueryContext",
      readOnly: true,
    },
    Request: {
      type: "object",
      readOnly: true,
    },
    RawValues: {
      $ref: "#/definitions/ODataRawQueryOptions",
      readOnly: true,
    },
    SelectExpand: {
      $ref: "#/definitions/SelectExpandQueryOption",
      readOnly: true,
    },
    Filter: {
      $ref: "#/definitions/FilterQueryOption",
      readOnly: true,
    },
    OrderBy: {
      $ref: "#/definitions/OrderByQueryOption",
      readOnly: true,
    },
    Skip: {
      $ref: "#/definitions/SkipQueryOption",
      readOnly: true,
    },
    Top: {
      $ref: "#/definitions/TopQueryOption",
      readOnly: true,
    },
    InlineCount: {
      $ref: "#/definitions/InlineCountQueryOption",
      readOnly: true,
    },
    Validator: {
      $ref: "#/definitions/ODataQueryValidator",
    },
  },
} as const;

export const PageResult_PartySchema = {
  type: "object",
  properties: {
    Items: {
      type: "array",
      items: {
        $ref: "#/definitions/Party",
      },
    },
    NextPageLink: {
      type: "string",
    },
    Count: {
      format: "int64",
      type: "integer",
    },
  },
} as const;

export const RegisterParticipantRequestSchema = {
  type: "object",
  properties: {
    CompanyID: {
      type: "string",
    },
  },
} as const;

export const DeleteParticipantRequestSchema = {
  type: "object",
  properties: {
    CompanyID: {
      type: "string",
    },
  },
} as const;

export const InboxGetResultSchema = {
  type: "object",
  properties: {
    InboxItems: {
      type: "array",
      items: {
        $ref: "#/definitions/InboxGetResultItem",
      },
    },
  },
} as const;

export const InboxGetResultItemSchema = {
  type: "object",
  properties: {
    InboxItemID: {
      format: "int32",
      type: "integer",
    },
    SenderPeppolID: {
      type: "string",
    },
    PeppolDocumentType: {
      type: "string",
    },
    ReceiverPeppolID: {
      type: "string",
    },
    SenderCompanyID: {
      type: "string",
    },
    ReceiverCompanyID: {
      type: "string",
    },
    CreationDate: {
      format: "date-time",
      type: "string",
    },
    PeppolFileID: {
      format: "uuid",
      type: "string",
      example: "00000000-0000-0000-0000-000000000000",
    },
  },
} as const;

export const RefusePeppolItemRequestSchema = {
  type: "object",
  properties: {
    RefusalReason: {
      type: "string",
    },
  },
} as const;

export const ParticipantInformationResponseSchema = {
  type: "object",
  properties: {
    Registered: {
      type: "boolean",
    },
    Identifier: {
      type: "string",
    },
    DocumentTypes: {
      type: "array",
      items: {
        enum: [
          "Invoice4",
          "Invoice5",
          "CreditNote5",
          "MLR",
          "MLRBISV3",
          "MLRBISV2",
          "IMR",
          "EFFF",
          "BISv3Invoice",
          "BISv3CreditNote",
          "BISv3OrderForm",
          "BISv3AUNZInvoice",
          "BISv3AUNZCreditNote",
          "XRechnung22Invoice",
          "XRechnung22CreditNote",
          "SIInvoice",
          "SICreditNote",
          "UBLBEInvoice",
          "UBLBECreditNote",
          "CII",
          "PTCIUSInvoice",
          "PTCIUSCreditNote",
          "BISv3SGInvoice",
          "BISv3SGCreditNote",
          "ROCIUSInvoice",
          "ROCIUSCreditNote",
          "XRechnung3Invoice",
          "XRechnung3CreditNote",
          "EndUserStatistics",
          "TransactionStatistics",
          "MYPintInvoice",
          "MYPintCreditNote",
          "MYPintInvoiceWildCard",
          "MYPintCreditNoteWildCard",
          "PintInvoiceWildCard",
          "PintCreditNoteWildCard",
          "AUNZPintInvoice",
          "AUNZPintCreditNote",
          "FACeCIUSInvoice",
          "FACeCIUSCreditNote",
          "PintBillingWildCard",
        ],
        type: "string",
      },
    },
    ServiceDetails: {
      type: "array",
      items: {
        $ref: "#/definitions/ServiceDetail",
      },
    },
    ServiceProviderID: {
      type: "string",
    },
  },
} as const;

export const ServiceDetailSchema = {
  type: "object",
  properties: {
    DocumentIdentifier: {
      type: "string",
    },
    DocumentIdentifierScheme: {
      type: "string",
    },
    Processes: {
      type: "array",
      items: {
        $ref: "#/definitions/ProcessInfo",
      },
    },
  },
} as const;

export const ProcessInfoSchema = {
  type: "object",
  properties: {
    ProcessIdentifier: {
      type: "string",
    },
    ProcessIdentifierScheme: {
      type: "string",
    },
    Endpoints: {
      type: "array",
      items: {
        $ref: "#/definitions/Endpoint",
      },
    },
  },
} as const;

export const EndpointSchema = {
  type: "object",
  properties: {
    EndpointURL: {
      type: "string",
    },
    TransportProfile: {
      type: "string",
    },
    Certificate: {
      type: "string",
    },
  },
} as const;

export const ProductSchema = {
  type: "object",
  properties: {
    ProductID: {
      format: "int32",
      type: "integer",
    },
    Reference: {
      type: "string",
    },
    Description: {
      type: "string",
    },
    AmountExcl: {
      format: "double",
      type: "number",
    },
    VAT: {
      format: "double",
      type: "number",
    },
    Unit: {
      type: "string",
    },
    GroupID: {
      format: "int32",
      type: "integer",
    },
    GroupName: {
      type: "string",
    },
    AmountIncl: {
      format: "double",
      type: "number",
    },
    StockQuantity: {
      format: "double",
      type: "number",
    },
    MinimumBilledQuantity: {
      format: "double",
      type: "number",
    },
    BuyExcl: {
      format: "double",
      type: "number",
    },
    InternalInformation: {
      type: "string",
    },
    Created: {
      format: "date-time",
      type: "string",
    },
    LastModified: {
      format: "date-time",
      type: "string",
    },
    EAN: {
      type: "string",
    },
    GTIN: {
      type: "string",
    },
    GLN: {
      type: "string",
    },
    ExternalProviderTC: {
      type: "string",
    },
    ChildProducts: {
      type: "array",
      items: {
        $ref: "#/definitions/Product",
      },
    },
  },
} as const;

export const ODataQueryOptions_ProductSchema = {
  type: "object",
  properties: {
    IfMatch: {
      type: "object",
      readOnly: true,
    },
    IfNoneMatch: {
      type: "object",
      readOnly: true,
    },
    Context: {
      $ref: "#/definitions/ODataQueryContext",
      readOnly: true,
    },
    Request: {
      type: "object",
      readOnly: true,
    },
    RawValues: {
      $ref: "#/definitions/ODataRawQueryOptions",
      readOnly: true,
    },
    SelectExpand: {
      $ref: "#/definitions/SelectExpandQueryOption",
      readOnly: true,
    },
    Filter: {
      $ref: "#/definitions/FilterQueryOption",
      readOnly: true,
    },
    OrderBy: {
      $ref: "#/definitions/OrderByQueryOption",
      readOnly: true,
    },
    Skip: {
      $ref: "#/definitions/SkipQueryOption",
      readOnly: true,
    },
    Top: {
      $ref: "#/definitions/TopQueryOption",
      readOnly: true,
    },
    InlineCount: {
      $ref: "#/definitions/InlineCountQueryOption",
      readOnly: true,
    },
    Validator: {
      $ref: "#/definitions/ODataQueryValidator",
    },
  },
} as const;

export const PageResult_ProductSchema = {
  type: "object",
  properties: {
    Items: {
      type: "array",
      items: {
        $ref: "#/definitions/Product",
      },
    },
    NextPageLink: {
      type: "string",
    },
    Count: {
      format: "int64",
      type: "integer",
    },
  },
} as const;

export const ReportsExportOverViewModelSchema = {
  type: "object",
  properties: {
    ReportID: {
      format: "int32",
      type: "integer",
    },
    ReportName: {
      type: "string",
    },
  },
} as const;

export const ReportDetailModelSchema = {
  type: "object",
  properties: {
    ID: {
      format: "int32",
      type: "integer",
    },
    Name: {
      type: "string",
    },
    CSVs: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
} as const;

export const ToProcessSaveRequestSchema = {
  type: "object",
  properties: {
    Split: {
      type: "boolean",
    },
    File: {
      $ref: "#/definitions/File",
    },
    FileSource: {
      $ref: "#/definitions/File",
    },
    MetaData: {
      $ref: "#/definitions/UploadMetadata",
      description: "Optional",
    },
  },
} as const;

export const UploadMetadataSchema = {
  type: "object",
  properties: {
    TotalIncl: {
      format: "double",
      type: "number",
    },
    CostType: {
      type: "string",
    },
    PaymentMethod: {
      type: "string",
    },
    Description: {
      type: "string",
    },
    CurrencyTC: {
      type: "string",
    },
    OrderDate: {
      format: "date-time",
      type: "string",
    },
  },
} as const;
