// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  AccountGetAccountInformationData,
  AccountGetAccountInformationResponses,
  AccountGetAccountInformationErrors,
  AccountGetSsoTokenData,
  AccountGetSsoTokenResponses,
  AccountGetSsoTokenErrors,
  AccountPostSequencesData,
  AccountPostSequencesResponses,
  AccountPostSequencesErrors,
  AccountRegisterCompanyData,
  AccountRegisterCompanyResponses,
  AccountRegisterCompanyErrors,
  AccountUpdateLicenseData,
  AccountUpdateLicenseResponses,
  AccountUpdateLicenseErrors,
  AccountAddLicenseBillableData,
  AccountAddLicenseBillableResponses,
  AccountAddLicenseBillableErrors,
  AccountantGetFeedsData,
  AccountantGetFeedsResponses,
  AccountantGetFeedsErrors,
  AccountantPostFeedsData,
  AccountantPostFeedsResponses,
  AccountantPostFeedsErrors,
  AccountantDeleteFeedsData,
  AccountantDeleteFeedsResponses,
  AccountantDeleteFeedsErrors,
  AccountantGetIndexData,
  AccountantGetIndexResponses,
  AccountantGetIndexErrors,
  AccountantPostConfirmData,
  AccountantPostConfirmResponses,
  AccountantPostConfirmErrors,
  AccountantGetFileData,
  AccountantGetFileResponses,
  AccountantGetFileErrors,
  CashbookInitializeCashbookData,
  CashbookInitializeCashbookResponses,
  CashbookInitializeCashbookErrors,
  CashbookCloseCashbookData,
  CashbookCloseCashbookResponses,
  CashbookCloseCashbookErrors,
  CashbookGetCashbookData,
  CashbookGetCashbookResponses,
  CashbookGetCashbookErrors,
  CashbookGetCashbookEntriesData,
  CashbookGetCashbookEntriesResponses,
  CashbookGetCashbookEntriesErrors,
  CashbookGetCashbooksData,
  CashbookGetCashbooksResponses,
  CashbookGetCashbooksErrors,
  CashbookGetCashbookHistoryData,
  CashbookGetCashbookHistoryResponses,
  CashbookGetCashbookHistoryErrors,
  CashbookPostCashbookEntryData,
  CashbookPostCashbookEntryResponses,
  CashbookPostCashbookEntryErrors,
  DailyReceiptPostDailyReceiptBookEntryData,
  DailyReceiptPostDailyReceiptBookEntryResponses,
  DailyReceiptPostDailyReceiptBookEntryErrors,
  DailyReceiptGetDailyReceiptEntryData,
  DailyReceiptGetDailyReceiptEntryResponses,
  DailyReceiptGetDailyReceiptEntryErrors,
  DailyReceiptGetDailyReceiptBooksData,
  DailyReceiptGetDailyReceiptBooksResponses,
  DailyReceiptGetDailyReceiptBooksErrors,
  DailyReceiptGetDailyReceiptBooks2Data,
  DailyReceiptGetDailyReceiptBooks2Responses,
  DailyReceiptGetDailyReceiptBooks2Errors,
  DocumentGetDocumentsData,
  DocumentGetDocumentsResponses,
  DocumentPostDocumentData,
  DocumentPostDocumentResponses,
  DocumentGetDocumentData,
  DocumentGetDocumentResponses,
  EinvoiceGetRegistrationsData,
  EinvoiceGetRegistrationsResponses,
  EinvoiceGetRegistrationsErrors,
  EinvoicePostRegistrationData,
  EinvoicePostRegistrationResponses,
  EinvoicePostRegistrationErrors,
  EinvoiceDeleteRegistrationData,
  EinvoiceDeleteRegistrationResponses,
  EinvoiceDeleteRegistrationErrors,
  EinvoiceGetRegistrationData,
  EinvoiceGetRegistrationResponses,
  EinvoiceGetRegistrationErrors,
  EinvoicePatchEntityData,
  EinvoicePatchEntityResponses,
  EinvoicePatchEntityErrors,
  EinvoicePostRegistrationIntegrationData,
  EinvoicePostRegistrationIntegrationResponses,
  EinvoicePostRegistrationIntegrationErrors,
  EinvoiceDeleteRegistrationIntegrationData,
  EinvoiceDeleteRegistrationIntegrationResponses,
  EinvoiceDeleteRegistrationIntegrationErrors,
  EinvoicePostSendData,
  EinvoicePostSendResponses,
  EinvoicePostSendErrors,
  EinvoiceGetOrdersData,
  EinvoiceGetOrdersResponses,
  EinvoiceGetOrdersErrors,
  EinvoiceGetFileData,
  EinvoiceGetFileResponses,
  EinvoiceGetFileErrors,
  EinvoiceGetOrderData,
  EinvoiceGetOrderResponses,
  EinvoiceGetOrderErrors,
  EinvoicePatchOrderData,
  EinvoicePatchOrderResponses,
  EinvoicePatchOrderErrors,
  EinvoiceGetWebhooksData,
  EinvoiceGetWebhooksResponses,
  EinvoiceGetWebhooksErrors,
  EinvoicePostWebhookData,
  EinvoicePostWebhookResponses,
  EinvoicePostWebhookErrors,
  EinvoiceDeleteWebhooksData,
  EinvoiceDeleteWebhooksResponses,
  EinvoiceDeleteWebhooksErrors,
  EinvoiceRefreshWebhookSecretData,
  EinvoiceRefreshWebhookSecretResponses,
  EinvoiceRefreshWebhookSecretErrors,
  EinvoicePostKycInitiationData,
  EinvoicePostKycInitiationResponses,
  EinvoicePostKycInitiationErrors,
  FileGetOrdersData,
  FileGetOrdersResponses,
  FileGetOrdersErrors,
  FinancialTransactionPostImportFileData,
  FinancialTransactionPostImportFileResponses,
  FinancialTransactionPostImportFileErrors,
  FinancialTransactionPostImportData,
  FinancialTransactionPostImportResponses,
  FinancialTransactionPostImportErrors,
  FinancialTransactionGetBankTransactionsData,
  FinancialTransactionGetBankTransactionsResponses,
  FinancialTransactionGetBankTransactionsErrors,
  GlAccountPostGlAccountData,
  GlAccountPostGlAccountResponses,
  GlAccountPostGlAccountErrors,
  GlAccountPostGlAccountBulkData,
  GlAccountPostGlAccountBulkResponses,
  GlAccountPostGlAccountBulkErrors,
  JournalPostGlAccountData,
  JournalPostGlAccountResponses,
  JournalPostGlAccountErrors,
  MiscGetCompanySearchData,
  MiscGetCompanySearchResponses,
  MiscGetCompanySearchErrors,
  MiscGetTypeCodesData,
  MiscGetTypeCodesResponses,
  MiscGetTypeCodesErrors,
  MiscGetTranslationData,
  MiscGetTranslationResponses,
  MiscGetTranslationErrors,
  OAuth2PostTokenData,
  OAuth2PostTokenResponses,
  OAuth2PostTokenErrors,
  OAuth2PostTokenRevokeData,
  OAuth2PostTokenRevokeResponses,
  OAuth2PostTokenRevokeErrors,
  OrderGetOrdersData,
  OrderGetOrdersResponses,
  OrderGetOrdersErrors,
  OrderPostOrdersData,
  OrderPostOrdersResponses,
  OrderPostOrdersErrors,
  OrderPutOrderBookingsData,
  OrderPutOrderBookingsResponses,
  OrderPutOrderBookingsErrors,
  OrderDeleteOrderData,
  OrderDeleteOrderResponses,
  OrderDeleteOrderErrors,
  OrderGetOrderData,
  OrderGetOrderResponses,
  OrderGetOrderErrors,
  OrderPatchOrdersData,
  OrderPatchOrdersResponses,
  OrderPatchOrdersErrors,
  OrderPostOrderPaymentData,
  OrderPostOrderPaymentResponses,
  OrderPostOrderPaymentErrors,
  OrderPostSendData,
  OrderPostSendResponses,
  OrderPostSendErrors,
  OrderESignOrderData,
  OrderESignOrderResponses,
  OrderESignOrderErrors,
  OrderGetDeletedData,
  OrderGetDeletedResponses,
  OrderGetDeletedErrors,
  PartyGetPartyData,
  PartyGetPartyResponses,
  PartyGetPartyErrors,
  PartyPatchPartiesData,
  PartyPatchPartiesResponses,
  PartyPatchPartiesErrors,
  PartyGetPartiesData,
  PartyGetPartiesResponses,
  PartyGetPartiesErrors,
  PartyPostPartyData,
  PartyPostPartyResponses,
  PartyPostPartyErrors,
  PeppolDeleteParticipantData,
  PeppolDeleteParticipantResponses,
  PeppolDeleteParticipantErrors,
  PeppolPostParticipantData,
  PeppolPostParticipantResponses,
  PeppolPostParticipantErrors,
  PeppolGetInboxData,
  PeppolGetInboxResponses,
  PeppolGetInboxErrors,
  PeppolInboxItemConfirmData,
  PeppolInboxItemConfirmResponses,
  PeppolInboxItemConfirmErrors,
  PeppolInboxItemRefuseData,
  PeppolInboxItemRefuseResponses,
  PeppolInboxItemRefuseErrors,
  PeppolPostSendOrderData,
  PeppolPostSendOrderResponses,
  PeppolPostSendOrderErrors,
  PeppolGetParticipantInformationData,
  PeppolGetParticipantInformationResponses,
  PeppolGetParticipantInformationErrors,
  ProductGetProductData,
  ProductGetProductResponses,
  ProductGetProductErrors,
  ProductGetProductsData,
  ProductGetProductsResponses,
  ProductGetProductsErrors,
  ProductPostProductData,
  ProductPostProductResponses,
  ProductPostProductErrors,
  ReportReportListGetData,
  ReportReportListGetResponses,
  ReportReportListGetErrors,
  ReportReportDetailGetData,
  ReportReportDetailGetResponses,
  ReportReportDetailGetErrors,
  ToProcessPostToProcessData,
  ToProcessPostToProcessResponses,
  ToProcessPostToProcessErrors,
  ToProcessDeleteToProcessData,
  ToProcessDeleteToProcessResponses,
  ToProcessDeleteToProcessErrors,
  WebhookGetWebhooksData,
  WebhookGetWebhooksResponses,
  WebhookGetWebhooksErrors,
  WebhookPostWebhookData,
  WebhookPostWebhookResponses,
  WebhookPostWebhookErrors,
  WebhookDeleteWebhooksData,
  WebhookDeleteWebhooksResponses,
  WebhookDeleteWebhooksErrors,
  WebhookRefreshWebhookSecretData,
  WebhookRefreshWebhookSecretResponses,
  WebhookRefreshWebhookSecretErrors,
} from "./types.gen";
import {
  zAccountGetAccountInformationData,
  zAccountGetSsoTokenData,
  zAccountPostSequencesData,
  zAccountRegisterCompanyData,
  zAccountUpdateLicenseData,
  zAccountAddLicenseBillableData,
  zAccountantGetFeedsData,
  zAccountantPostFeedsData,
  zAccountantDeleteFeedsData,
  zAccountantGetIndexData,
  zAccountantPostConfirmData,
  zAccountantGetFileData,
  zCashbookInitializeCashbookData,
  zCashbookCloseCashbookData,
  zCashbookGetCashbookData,
  zCashbookGetCashbookEntriesData,
  zCashbookGetCashbooksData,
  zCashbookGetCashbookHistoryData,
  zCashbookPostCashbookEntryData,
  zDailyReceiptPostDailyReceiptBookEntryData,
  zDailyReceiptGetDailyReceiptEntryData,
  zDailyReceiptGetDailyReceiptBooksData,
  zDailyReceiptGetDailyReceiptBooks2Data,
  zDocumentGetDocumentsData,
  zDocumentPostDocumentData,
  zDocumentGetDocumentData,
  zEinvoiceGetRegistrationsData,
  zEinvoicePostRegistrationData,
  zEinvoiceDeleteRegistrationData,
  zEinvoiceGetRegistrationData,
  zEinvoicePatchEntityData,
  zEinvoicePostRegistrationIntegrationData,
  zEinvoiceDeleteRegistrationIntegrationData,
  zEinvoicePostSendData,
  zEinvoiceGetOrdersData,
  zEinvoiceGetFileData,
  zEinvoiceGetOrderData,
  zEinvoicePatchOrderData,
  zEinvoiceGetWebhooksData,
  zEinvoicePostWebhookData,
  zEinvoiceDeleteWebhooksData,
  zEinvoiceRefreshWebhookSecretData,
  zEinvoicePostKycInitiationData,
  zFileGetOrdersData,
  zFinancialTransactionPostImportFileData,
  zFinancialTransactionPostImportData,
  zFinancialTransactionGetBankTransactionsData,
  zGlAccountPostGlAccountData,
  zGlAccountPostGlAccountBulkData,
  zJournalPostGlAccountData,
  zMiscGetCompanySearchData,
  zMiscGetTypeCodesData,
  zMiscGetTranslationData,
  zOAuth2PostTokenData,
  zOAuth2PostTokenRevokeData,
  zOrderGetOrdersData,
  zOrderPostOrdersData,
  zOrderPutOrderBookingsData,
  zOrderDeleteOrderData,
  zOrderGetOrderData,
  zOrderPatchOrdersData,
  zOrderPostOrderPaymentData,
  zOrderPostSendData,
  zOrderESignOrderData,
  zOrderGetDeletedData,
  zPartyGetPartyData,
  zPartyPatchPartiesData,
  zPartyGetPartiesData,
  zPartyPostPartyData,
  zPeppolDeleteParticipantData,
  zPeppolPostParticipantData,
  zPeppolGetInboxData,
  zPeppolInboxItemConfirmData,
  zPeppolInboxItemRefuseData,
  zPeppolPostSendOrderData,
  zPeppolGetParticipantInformationData,
  zProductGetProductData,
  zProductGetProductsData,
  zProductPostProductData,
  zReportReportListGetData,
  zReportReportDetailGetData,
  zToProcessPostToProcessData,
  zToProcessDeleteToProcessData,
  zWebhookGetWebhooksData,
  zWebhookPostWebhookData,
  zWebhookDeleteWebhooksData,
  zWebhookRefreshWebhookSecretData,
} from "./zod.gen";
import {
  accountGetAccountInformationResponseTransformer,
  cashbookGetCashbookResponseTransformer,
  cashbookGetCashbookEntriesResponseTransformer,
  cashbookGetCashbooksResponseTransformer,
  cashbookGetCashbookHistoryResponseTransformer,
  cashbookPostCashbookEntryResponseTransformer,
  dailyReceiptGetDailyReceiptBooksResponseTransformer,
  dailyReceiptGetDailyReceiptBooks2ResponseTransformer,
  documentGetDocumentsResponseTransformer,
  documentGetDocumentResponseTransformer,
  einvoiceGetOrdersResponseTransformer,
  einvoiceGetOrderResponseTransformer,
  miscGetCompanySearchResponseTransformer,
  orderGetOrdersResponseTransformer,
  orderGetOrderResponseTransformer,
  orderGetDeletedResponseTransformer,
  partyGetPartyResponseTransformer,
  partyGetPartiesResponseTransformer,
  peppolGetInboxResponseTransformer,
  productGetProductResponseTransformer,
  productGetProductsResponseTransformer,
} from "./transformers.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get account information about the current user
 */
export const accountGetAccountInformation = <ThrowOnError extends boolean = false>(
  options?: Options<AccountGetAccountInformationData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    AccountGetAccountInformationResponses,
    AccountGetAccountInformationErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAccountGetAccountInformationData.parseAsync(data);
    },
    responseTransformer: accountGetAccountInformationResponseTransformer,
    url: "/v1/account/accountInformation",
    ...options,
  });
};

/**
 * Get an SSO token of the current user
 */
export const accountGetSsoToken = <ThrowOnError extends boolean = false>(
  options?: Options<AccountGetSsoTokenData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    AccountGetSsoTokenResponses,
    AccountGetSsoTokenErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAccountGetSsoTokenData.parseAsync(data);
    },
    url: "/v1/account/ssoToken",
    ...options,
  });
};

/**
 * Update the sequence of a specific type
 */
export const accountPostSequences = <ThrowOnError extends boolean = false>(
  options: Options<AccountPostSequencesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AccountPostSequencesResponses,
    AccountPostSequencesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAccountPostSequencesData.parseAsync(data);
    },
    url: "/v1/account/sequences",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Registers a Company in the Billit-ecosphere
 */
export const accountRegisterCompany = <ThrowOnError extends boolean = false>(
  options: Options<AccountRegisterCompanyData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AccountRegisterCompanyResponses,
    AccountRegisterCompanyErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAccountRegisterCompanyData.parseAsync(data);
    },
    url: "/v1/account/registercompany",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Update the license
 */
export const accountUpdateLicense = <ThrowOnError extends boolean = false>(
  options: Options<AccountUpdateLicenseData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AccountUpdateLicenseResponses,
    AccountUpdateLicenseErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAccountUpdateLicenseData.parseAsync(data);
    },
    url: "/v1/account/license",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Add new License Billable
 */
export const accountAddLicenseBillable = <ThrowOnError extends boolean = false>(
  options: Options<AccountAddLicenseBillableData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AccountAddLicenseBillableResponses,
    AccountAddLicenseBillableErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAccountAddLicenseBillableData.parseAsync(data);
    },
    url: "/v1/account/license/addons",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get a list of all feeds to download
 */
export const accountantGetFeeds = <ThrowOnError extends boolean = false>(
  options?: Options<AccountantGetFeedsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    AccountantGetFeedsResponses,
    AccountantGetFeedsErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAccountantGetFeedsData.parseAsync(data);
    },
    url: "/v1/accountant/feeds",
    ...options,
  });
};

/**
 * Register a new feed. All newly exported orders or documents will be available in this new feed.
 */
export const accountantPostFeeds = <ThrowOnError extends boolean = false>(
  options: Options<AccountantPostFeedsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AccountantPostFeedsResponses,
    AccountantPostFeedsErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAccountantPostFeedsData.parseAsync(data);
    },
    url: "/v1/accountant/feeds",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete the feed
 */
export const accountantDeleteFeeds = <ThrowOnError extends boolean = false>(
  options: Options<AccountantDeleteFeedsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    AccountantDeleteFeedsResponses,
    AccountantDeleteFeedsErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAccountantDeleteFeedsData.parseAsync(data);
    },
    url: "/v1/accountant/feeds/{feedName}",
    ...options,
  });
};

/**
 * Get A list of all feeds to download. Only query this once per minute
 */
export const accountantGetIndex = <ThrowOnError extends boolean = false>(
  options: Options<AccountantGetIndexData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    AccountantGetIndexResponses,
    AccountantGetIndexErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAccountantGetIndexData.parseAsync(data);
    },
    url: "/v1/accountant/feeds/{feedName}",
    ...options,
  });
};

/**
 * Confirm each succesfully downloaded feed item to remove it from the feedlist
 */
export const accountantPostConfirm = <ThrowOnError extends boolean = false>(
  options: Options<AccountantPostConfirmData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AccountantPostConfirmResponses,
    AccountantPostConfirmErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAccountantPostConfirmData.parseAsync(data);
    },
    url: "/v1/accountant/feeds/{feedName}/{feedItemID}/confirm",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * download a coda file from the feed
 */
export const accountantGetFile = <ThrowOnError extends boolean = false>(
  options: Options<AccountantGetFileData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    AccountantGetFileResponses,
    AccountantGetFileErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zAccountantGetFileData.parseAsync(data);
    },
    url: "/v1/accountant/feeds/{feedName}/{feedItemID}",
    ...options,
  });
};

/**
 * Initialize the cash book for first use
 */
export const cashbookInitializeCashbook = <ThrowOnError extends boolean = false>(
  options: Options<CashbookInitializeCashbookData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CashbookInitializeCashbookResponses,
    CashbookInitializeCashbookErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zCashbookInitializeCashbookData.parseAsync(data);
    },
    url: "/v1/Cashbook/Initialize",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Permanently close the cash book
 */
export const cashbookCloseCashbook = <ThrowOnError extends boolean = false>(
  options?: Options<CashbookCloseCashbookData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    CashbookCloseCashbookResponses,
    CashbookCloseCashbookErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zCashbookCloseCashbookData.parseAsync(data);
    },
    url: "/v1/Cashbook/Close",
    ...options,
  });
};

/**
 * Get the current active cash book
 */
export const cashbookGetCashbook = <ThrowOnError extends boolean = false>(
  options?: Options<CashbookGetCashbookData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    CashbookGetCashbookResponses,
    CashbookGetCashbookErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zCashbookGetCashbookData.parseAsync(data);
    },
    responseTransformer: cashbookGetCashbookResponseTransformer,
    url: "/v1/Cashbook",
    ...options,
  });
};

/**
 * Get an overview of all the entries in the current active cash book
 */
export const cashbookGetCashbookEntries = <ThrowOnError extends boolean = false>(
  options?: Options<CashbookGetCashbookEntriesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    CashbookGetCashbookEntriesResponses,
    CashbookGetCashbookEntriesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zCashbookGetCashbookEntriesData.parseAsync(data);
    },
    responseTransformer: cashbookGetCashbookEntriesResponseTransformer,
    url: "/v1/Cashbook/Entries",
    ...options,
  });
};

/**
 * Get an overview of all the closed cash books
 */
export const cashbookGetCashbooks = <ThrowOnError extends boolean = false>(
  options?: Options<CashbookGetCashbooksData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    CashbookGetCashbooksResponses,
    CashbookGetCashbooksErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zCashbookGetCashbooksData.parseAsync(data);
    },
    responseTransformer: cashbookGetCashbooksResponseTransformer,
    url: "/v1/Cashbook/History",
    ...options,
  });
};

/**
 * Get an overview of all the entries in a closed cash book
 */
export const cashbookGetCashbookHistory = <ThrowOnError extends boolean = false>(
  options: Options<CashbookGetCashbookHistoryData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    CashbookGetCashbookHistoryResponses,
    CashbookGetCashbookHistoryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zCashbookGetCashbookHistoryData.parseAsync(data);
    },
    responseTransformer: cashbookGetCashbookHistoryResponseTransformer,
    url: "/v1/Cashbook/{cashbookID}/History",
    ...options,
  });
};

/**
 * Add an entry to the current active cash book
 */
export const cashbookPostCashbookEntry = <ThrowOnError extends boolean = false>(
  options: Options<CashbookPostCashbookEntryData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CashbookPostCashbookEntryResponses,
    CashbookPostCashbookEntryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zCashbookPostCashbookEntryData.parseAsync(data);
    },
    responseTransformer: cashbookPostCashbookEntryResponseTransformer,
    url: "/v1/Cashbook/AddEntry",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Add a new daily receipt to a new or open daily receipt book
 */
export const dailyReceiptPostDailyReceiptBookEntry = <ThrowOnError extends boolean = false>(
  options: Options<DailyReceiptPostDailyReceiptBookEntryData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    DailyReceiptPostDailyReceiptBookEntryResponses,
    DailyReceiptPostDailyReceiptBookEntryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zDailyReceiptPostDailyReceiptBookEntryData.parseAsync(data);
    },
    url: "/v1/DailyReceiptBooks/commands/CreateEntryInOpenExistingOrNew",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get a daily receipt entry
 */
export const dailyReceiptGetDailyReceiptEntry = <ThrowOnError extends boolean = false>(
  options: Options<DailyReceiptGetDailyReceiptEntryData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    DailyReceiptGetDailyReceiptEntryResponses,
    DailyReceiptGetDailyReceiptEntryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zDailyReceiptGetDailyReceiptEntryData.parseAsync(data);
    },
    url: "/v1/DailyReceiptBooks/DailyReceiptEntry/{DailyReceiptEntryID}",
    ...options,
  });
};

/**
 * Get a daily receipt book with details
 */
export const dailyReceiptGetDailyReceiptBooks = <ThrowOnError extends boolean = false>(
  options: Options<DailyReceiptGetDailyReceiptBooksData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    DailyReceiptGetDailyReceiptBooksResponses,
    DailyReceiptGetDailyReceiptBooksErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zDailyReceiptGetDailyReceiptBooksData.parseAsync(data);
    },
    responseTransformer: dailyReceiptGetDailyReceiptBooksResponseTransformer,
    url: "/v1/DailyReceiptBooks/{DailyReceiptBookID}",
    ...options,
  });
};

/**
 * Get a daily receipt book list
 */
export const dailyReceiptGetDailyReceiptBooks2 = <ThrowOnError extends boolean = false>(
  options?: Options<DailyReceiptGetDailyReceiptBooks2Data, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    DailyReceiptGetDailyReceiptBooks2Responses,
    DailyReceiptGetDailyReceiptBooks2Errors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zDailyReceiptGetDailyReceiptBooks2Data.parseAsync(data);
    },
    responseTransformer: dailyReceiptGetDailyReceiptBooks2ResponseTransformer,
    url: "/v1/DailyReceiptBooks",
    ...options,
  });
};

/**
 * Get a list of documents
 */
export const documentGetDocuments = <ThrowOnError extends boolean = false>(
  options?: Options<DocumentGetDocumentsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    DocumentGetDocumentsResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zDocumentGetDocumentsData.parseAsync(data);
    },
    responseTransformer: documentGetDocumentsResponseTransformer,
    url: "/v1/documents",
    ...options,
  });
};

/**
 * Save a document
 */
export const documentPostDocument = <ThrowOnError extends boolean = false>(
  options: Options<DocumentPostDocumentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    DocumentPostDocumentResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zDocumentPostDocumentData.parseAsync(data);
    },
    url: "/v1/documents",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get a document specified by the documentID
 */
export const documentGetDocument = <ThrowOnError extends boolean = false>(
  options: Options<DocumentGetDocumentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<DocumentGetDocumentResponses, unknown, ThrowOnError>(
    {
      requestValidator: async (data) => {
        return await zDocumentGetDocumentData.parseAsync(data);
      },
      responseTransformer: documentGetDocumentResponseTransformer,
      url: "/v1/documents/{documentID}",
      ...options,
    }
  );
};

/**
 * Retrieve all E-invoice registrations
 */
export const einvoiceGetRegistrations = <ThrowOnError extends boolean = false>(
  options?: Options<EinvoiceGetRegistrationsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    EinvoiceGetRegistrationsResponses,
    EinvoiceGetRegistrationsErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoiceGetRegistrationsData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations",
    ...options,
  });
};

/**
 * Create an E-invoice registration for a new entity
 */
export const einvoicePostRegistration = <ThrowOnError extends boolean = false>(
  options: Options<EinvoicePostRegistrationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    EinvoicePostRegistrationResponses,
    EinvoicePostRegistrationErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoicePostRegistrationData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a registration
 */
export const einvoiceDeleteRegistration = <ThrowOnError extends boolean = false>(
  options: Options<EinvoiceDeleteRegistrationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    EinvoiceDeleteRegistrationResponses,
    EinvoiceDeleteRegistrationErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoiceDeleteRegistrationData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations/{registrationID}",
    ...options,
  });
};

/**
 * Retrieve an E-invoice registration
 */
export const einvoiceGetRegistration = <ThrowOnError extends boolean = false>(
  options: Options<EinvoiceGetRegistrationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    EinvoiceGetRegistrationResponses,
    EinvoiceGetRegistrationErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoiceGetRegistrationData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations/{registrationID}",
    ...options,
  });
};

/**
 * Update an E-invoice registration
 */
export const einvoicePatchEntity = <ThrowOnError extends boolean = false>(
  options: Options<EinvoicePatchEntityData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    EinvoicePatchEntityResponses,
    EinvoicePatchEntityErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoicePatchEntityData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations/{registrationID}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Activate a new integration
 */
export const einvoicePostRegistrationIntegration = <ThrowOnError extends boolean = false>(
  options: Options<EinvoicePostRegistrationIntegrationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    EinvoicePostRegistrationIntegrationResponses,
    EinvoicePostRegistrationIntegrationErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoicePostRegistrationIntegrationData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations/{registrationID}/integrations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Deactivate an integration
 */
export const einvoiceDeleteRegistrationIntegration = <ThrowOnError extends boolean = false>(
  options: Options<EinvoiceDeleteRegistrationIntegrationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    EinvoiceDeleteRegistrationIntegrationResponses,
    EinvoiceDeleteRegistrationIntegrationErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoiceDeleteRegistrationIntegrationData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations/{registrationID}/integrations/{integrationID}",
    ...options,
  });
};

/**
 * Create and send an E-document
 */
export const einvoicePostSend = <ThrowOnError extends boolean = false>(
  options: Options<EinvoicePostSendData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    EinvoicePostSendResponses,
    EinvoicePostSendErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoicePostSendData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations/{registrationID}/commands/send",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get a list of orders
 */
export const einvoiceGetOrders = <ThrowOnError extends boolean = false>(
  options: Options<EinvoiceGetOrdersData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    EinvoiceGetOrdersResponses,
    EinvoiceGetOrdersErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoiceGetOrdersData.parseAsync(data);
    },
    responseTransformer: einvoiceGetOrdersResponseTransformer,
    url: "/v1/einvoices/registrations/{registrationID}/orders",
    ...options,
  });
};

/**
 * Get a file specified by the fileID
 */
export const einvoiceGetFile = <ThrowOnError extends boolean = false>(
  options: Options<EinvoiceGetFileData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    EinvoiceGetFileResponses,
    EinvoiceGetFileErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoiceGetFileData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations/{registrationID}/files/{fileID}",
    ...options,
  });
};

/**
 * Get an order specified by the orderID
 */
export const einvoiceGetOrder = <ThrowOnError extends boolean = false>(
  options: Options<EinvoiceGetOrderData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    EinvoiceGetOrderResponses,
    EinvoiceGetOrderErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoiceGetOrderData.parseAsync(data);
    },
    responseTransformer: einvoiceGetOrderResponseTransformer,
    url: "/v1/einvoices/registrations/{registrationID}/orders/{orderID}",
    ...options,
  });
};

/**
 * Patch an E-document
 */
export const einvoicePatchOrder = <ThrowOnError extends boolean = false>(
  options: Options<EinvoicePatchOrderData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    EinvoicePatchOrderResponses,
    EinvoicePatchOrderErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoicePatchOrderData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations/{registrationID}/orders/{orderID}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get all webhooks
 */
export const einvoiceGetWebhooks = <ThrowOnError extends boolean = false>(
  options: Options<EinvoiceGetWebhooksData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    EinvoiceGetWebhooksResponses,
    EinvoiceGetWebhooksErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoiceGetWebhooksData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations/{registrationID}/webhooks",
    ...options,
  });
};

/**
 * Create a webhook
 */
export const einvoicePostWebhook = <ThrowOnError extends boolean = false>(
  options: Options<EinvoicePostWebhookData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    EinvoicePostWebhookResponses,
    EinvoicePostWebhookErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoicePostWebhookData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations/{registrationID}/webhooks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a webhook
 */
export const einvoiceDeleteWebhooks = <ThrowOnError extends boolean = false>(
  options: Options<EinvoiceDeleteWebhooksData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    EinvoiceDeleteWebhooksResponses,
    EinvoiceDeleteWebhooksErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoiceDeleteWebhooksData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations/{registrationID}/webhooks/{webhookID}",
    ...options,
  });
};

/**
 * Refresh an webhook secret
 */
export const einvoiceRefreshWebhookSecret = <ThrowOnError extends boolean = false>(
  options: Options<EinvoiceRefreshWebhookSecretData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    EinvoiceRefreshWebhookSecretResponses,
    EinvoiceRefreshWebhookSecretErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoiceRefreshWebhookSecretData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations/{registrationID}/webhooks/refresh/{webhookID}",
    ...options,
  });
};

/**
 * Initiate a KYC procedure
 */
export const einvoicePostKycInitiation = <ThrowOnError extends boolean = false>(
  options: Options<EinvoicePostKycInitiationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    EinvoicePostKycInitiationResponses,
    EinvoicePostKycInitiationErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEinvoicePostKycInitiationData.parseAsync(data);
    },
    url: "/v1/einvoices/registrations/{registrationID}/identification",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get a file specified by the fileID
 */
export const fileGetOrders = <ThrowOnError extends boolean = false>(
  options: Options<FileGetOrdersData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    FileGetOrdersResponses,
    FileGetOrdersErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zFileGetOrdersData.parseAsync(data);
    },
    url: "/v1/files/{fileID}",
    ...options,
  });
};

/**
 * Upload a coda file and import the transactions
 */
export const financialTransactionPostImportFile = <ThrowOnError extends boolean = false>(
  options: Options<FinancialTransactionPostImportFileData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    FinancialTransactionPostImportFileResponses,
    FinancialTransactionPostImportFileErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zFinancialTransactionPostImportFileData.parseAsync(data);
    },
    url: "/v1/financialTransactions/importFile",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Create transactions using a list
 */
export const financialTransactionPostImport = <ThrowOnError extends boolean = false>(
  options: Options<FinancialTransactionPostImportData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    FinancialTransactionPostImportResponses,
    FinancialTransactionPostImportErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zFinancialTransactionPostImportData.parseAsync(data);
    },
    url: "/v1/financialTransactions/commands/import",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const financialTransactionGetBankTransactions = <ThrowOnError extends boolean = false>(
  options?: Options<FinancialTransactionGetBankTransactionsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    FinancialTransactionGetBankTransactionsResponses,
    FinancialTransactionGetBankTransactionsErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zFinancialTransactionGetBankTransactionsData.parseAsync(data);
    },
    url: "/v1/financialTransactions",
    ...options,
  });
};

/**
 * Create a general ledger account
 */
export const glAccountPostGlAccount = <ThrowOnError extends boolean = false>(
  options: Options<GlAccountPostGlAccountData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    GlAccountPostGlAccountResponses,
    GlAccountPostGlAccountErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGlAccountPostGlAccountData.parseAsync(data);
    },
    url: "/v1/glaccounts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Create multiple general ledger accounts using a list
 */
export const glAccountPostGlAccountBulk = <ThrowOnError extends boolean = false>(
  options: Options<GlAccountPostGlAccountBulkData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    GlAccountPostGlAccountBulkResponses,
    GlAccountPostGlAccountBulkErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zGlAccountPostGlAccountBulkData.parseAsync(data);
    },
    url: "/v1/glaccounts/commands/import",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Import a list of journals
 */
export const journalPostGlAccount = <ThrowOnError extends boolean = false>(
  options: Options<JournalPostGlAccountData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    JournalPostGlAccountResponses,
    JournalPostGlAccountErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zJournalPostGlAccountData.parseAsync(data);
    },
    url: "/v1/journals/commands/import",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Search for parties/companies based on a keyword
 */
export const miscGetCompanySearch = <ThrowOnError extends boolean = false>(
  options: Options<MiscGetCompanySearchData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    MiscGetCompanySearchResponses,
    MiscGetCompanySearchErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zMiscGetCompanySearchData.parseAsync(data);
    },
    responseTransformer: miscGetCompanySearchResponseTransformer,
    url: "/v1/misc/companysearch/{Keywords}",
    ...options,
  });
};

/**
 * Get all translations of a specified TypeCode
 */
export const miscGetTypeCodes = <ThrowOnError extends boolean = false>(
  options: Options<MiscGetTypeCodesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    MiscGetTypeCodesResponses,
    MiscGetTypeCodesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zMiscGetTypeCodesData.parseAsync(data);
    },
    url: "/v1/misc/typecodes/{TypeCodeType}",
    ...options,
  });
};

/**
 * Get a translations of a key of a typecode, optionally in a specified language
 */
export const miscGetTranslation = <ThrowOnError extends boolean = false>(
  options: Options<MiscGetTranslationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    MiscGetTranslationResponses,
    MiscGetTranslationErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zMiscGetTranslationData.parseAsync(data);
    },
    url: "/v1/misc/typecodes/{TypeCodeType}/{key}/{language}",
    ...options,
  });
};

export const oAuth2PostToken = <ThrowOnError extends boolean = false>(
  options: Options<OAuth2PostTokenData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    OAuth2PostTokenResponses,
    OAuth2PostTokenErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zOAuth2PostTokenData.parseAsync(data);
    },
    url: "/OAuth2/token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const oAuth2PostTokenRevoke = <ThrowOnError extends boolean = false>(
  options?: Options<OAuth2PostTokenRevokeData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    OAuth2PostTokenRevokeResponses,
    OAuth2PostTokenRevokeErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zOAuth2PostTokenRevokeData.parseAsync(data);
    },
    url: "/OAuth2/revoke",
    ...options,
  });
};

/**
 * Get a list of invoices/credit notes/order/...
 */
export const orderGetOrders = <ThrowOnError extends boolean = false>(
  options?: Options<OrderGetOrdersData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    OrderGetOrdersResponses,
    OrderGetOrdersErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zOrderGetOrdersData.parseAsync(data);
    },
    responseTransformer: orderGetOrdersResponseTransformer,
    url: "/v1/orders",
    ...options,
  });
};

/**
 * Create a new order or update an existing one
 */
export const orderPostOrders = <ThrowOnError extends boolean = false>(
  options: Options<OrderPostOrdersData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    OrderPostOrdersResponses,
    OrderPostOrdersErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zOrderPostOrdersData.parseAsync(data);
    },
    url: "/v1/orders",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Add a booking lines collection
 */
export const orderPutOrderBookings = <ThrowOnError extends boolean = false>(
  options: Options<OrderPutOrderBookingsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    OrderPutOrderBookingsResponses,
    OrderPutOrderBookingsErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zOrderPutOrderBookingsData.parseAsync(data);
    },
    url: "/v1/orders/{orderID}/bookingEntries",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a specific order
 */
export const orderDeleteOrder = <ThrowOnError extends boolean = false>(
  options: Options<OrderDeleteOrderData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    OrderDeleteOrderResponses,
    OrderDeleteOrderErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zOrderDeleteOrderData.parseAsync(data);
    },
    url: "/v1/orders/{orderID}",
    ...options,
  });
};

/**
 * Get a specific order
 */
export const orderGetOrder = <ThrowOnError extends boolean = false>(
  options: Options<OrderGetOrderData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    OrderGetOrderResponses,
    OrderGetOrderErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zOrderGetOrderData.parseAsync(data);
    },
    responseTransformer: orderGetOrderResponseTransformer,
    url: "/v1/orders/{orderID}",
    ...options,
  });
};

/**
 * Patch an order
 */
export const orderPatchOrders = <ThrowOnError extends boolean = false>(
  options: Options<OrderPatchOrdersData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    OrderPatchOrdersResponses,
    OrderPatchOrdersErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zOrderPatchOrdersData.parseAsync(data);
    },
    url: "/v1/orders/{orderID}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Add a partial or full payment to an order
 */
export const orderPostOrderPayment = <ThrowOnError extends boolean = false>(
  options: Options<OrderPostOrderPaymentData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    OrderPostOrderPaymentResponses,
    OrderPostOrderPaymentErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zOrderPostOrderPaymentData.parseAsync(data);
    },
    url: "/v1/orders/{orderID}/payments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Send a list of orders via a specified channel
 */
export const orderPostSend = <ThrowOnError extends boolean = false>(
  options: Options<OrderPostSendData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    OrderPostSendResponses,
    OrderPostSendErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zOrderPostSendData.parseAsync(data);
    },
    url: "/v1/orders/commands/send",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * E-Sign an order
 */
export const orderESignOrder = <ThrowOnError extends boolean = false>(
  options: Options<OrderESignOrderData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    OrderESignOrderResponses,
    OrderESignOrderErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zOrderESignOrderData.parseAsync(data);
    },
    url: "/v1/orders/commands/eSign/{orderID}",
    ...options,
  });
};

/**
 * Get a list of deleted orders
 */
export const orderGetDeleted = <ThrowOnError extends boolean = false>(
  options?: Options<OrderGetDeletedData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    OrderGetDeletedResponses,
    OrderGetDeletedErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zOrderGetDeletedData.parseAsync(data);
    },
    responseTransformer: orderGetDeletedResponseTransformer,
    url: "/v1/orders/deleted",
    ...options,
  });
};

/**
 * Get a party specified by the partyID
 */
export const partyGetParty = <ThrowOnError extends boolean = false>(
  options: Options<PartyGetPartyData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    PartyGetPartyResponses,
    PartyGetPartyErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zPartyGetPartyData.parseAsync(data);
    },
    responseTransformer: partyGetPartyResponseTransformer,
    url: "/v1/parties/{partyID}",
    ...options,
  });
};

/**
 * Patch Party Properties. NavigationProperties are not supported.
 */
export const partyPatchParties = <ThrowOnError extends boolean = false>(
  options: Options<PartyPatchPartiesData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PartyPatchPartiesResponses,
    PartyPatchPartiesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zPartyPatchPartiesData.parseAsync(data);
    },
    url: "/v1/parties/{partyID}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get a list of customers or suppliers
 */
export const partyGetParties = <ThrowOnError extends boolean = false>(
  options?: Options<PartyGetPartiesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    PartyGetPartiesResponses,
    PartyGetPartiesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zPartyGetPartiesData.parseAsync(data);
    },
    responseTransformer: partyGetPartiesResponseTransformer,
    url: "/v1/parties",
    ...options,
  });
};

/**
 * Create a new party or update an existing one
 */
export const partyPostParty = <ThrowOnError extends boolean = false>(
  options: Options<PartyPostPartyData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PartyPostPartyResponses,
    PartyPostPartyErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zPartyPostPartyData.parseAsync(data);
    },
    url: "/v1/parties",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a Peppol registration for a specific company
 */
export const peppolDeleteParticipant = <ThrowOnError extends boolean = false>(
  options: Options<PeppolDeleteParticipantData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    PeppolDeleteParticipantResponses,
    PeppolDeleteParticipantErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zPeppolDeleteParticipantData.parseAsync(data);
    },
    url: "/v1/peppol/participants",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Create a new Peppol registration for a specific company
 */
export const peppolPostParticipant = <ThrowOnError extends boolean = false>(
  options: Options<PeppolPostParticipantData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PeppolPostParticipantResponses,
    PeppolPostParticipantErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zPeppolPostParticipantData.parseAsync(data);
    },
    url: "/v1/peppol/participants",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Lists the first 10 peppol items in the inbox. Use the file api to download the actual message. Use the confirm or refuse endpoint to remove it from the queue
 */
export const peppolGetInbox = <ThrowOnError extends boolean = false>(
  options?: Options<PeppolGetInboxData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    PeppolGetInboxResponses,
    PeppolGetInboxErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zPeppolGetInboxData.parseAsync(data);
    },
    responseTransformer: peppolGetInboxResponseTransformer,
    url: "/v1/peppol/inbox",
    ...options,
  });
};

/**
 * Confirm an inbox item and remove it from the queue
 */
export const peppolInboxItemConfirm = <ThrowOnError extends boolean = false>(
  options: Options<PeppolInboxItemConfirmData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PeppolInboxItemConfirmResponses,
    PeppolInboxItemConfirmErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zPeppolInboxItemConfirmData.parseAsync(data);
    },
    url: "/v1/peppol/inbox/{inboxItemId}/confirm",
    ...options,
  });
};

/**
 * Refuse an inbox item and remove it from the queue
 */
export const peppolInboxItemRefuse = <ThrowOnError extends boolean = false>(
  options: Options<PeppolInboxItemRefuseData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PeppolInboxItemRefuseResponses,
    PeppolInboxItemRefuseErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zPeppolInboxItemRefuseData.parseAsync(data);
    },
    url: "/v1/peppol/inbox/{inboxItemId}/refuse",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Send a direct Peppol message. Compatible with receivers that support Invoice5, Creditnote5, BisV3 Invoice or BisV3 Creditnote
 */
export const peppolPostSendOrder = <ThrowOnError extends boolean = false>(
  options: Options<PeppolPostSendOrderData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    PeppolPostSendOrderResponses,
    PeppolPostSendOrderErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zPeppolPostSendOrderData.parseAsync(data);
    },
    url: "/v1/peppol/sendOrder",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Peppol participant information. API key is not required
 */
export const peppolGetParticipantInformation = <ThrowOnError extends boolean = false>(
  options: Options<PeppolGetParticipantInformationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    PeppolGetParticipantInformationResponses,
    PeppolGetParticipantInformationErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zPeppolGetParticipantInformationData.parseAsync(data);
    },
    url: "/v1/peppol/participantInformation/{VATorCBE}",
    ...options,
  });
};

/**
 * Get a specific product
 */
export const productGetProduct = <ThrowOnError extends boolean = false>(
  options: Options<ProductGetProductData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ProductGetProductResponses,
    ProductGetProductErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zProductGetProductData.parseAsync(data);
    },
    responseTransformer: productGetProductResponseTransformer,
    url: "/v1/products/{productID}",
    ...options,
  });
};

/**
 * Get a list of products
 */
export const productGetProducts = <ThrowOnError extends boolean = false>(
  options?: Options<ProductGetProductsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ProductGetProductsResponses,
    ProductGetProductsErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zProductGetProductsData.parseAsync(data);
    },
    responseTransformer: productGetProductsResponseTransformer,
    url: "/v1/products",
    ...options,
  });
};

/**
 * Create a new product or update an existing one
 */
export const productPostProduct = <ThrowOnError extends boolean = false>(
  options: Options<ProductPostProductData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    ProductPostProductResponses,
    ProductPostProductErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zProductPostProductData.parseAsync(data);
    },
    url: "/v1/products",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get a list of available reports for the current user
 */
export const reportReportListGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReportReportListGetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ReportReportListGetResponses,
    ReportReportListGetErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zReportReportListGetData.parseAsync(data);
    },
    url: "/v1/reports",
    ...options,
  });
};

/**
 * Get the result and name of the report specified by the reportID
 */
export const reportReportDetailGet = <ThrowOnError extends boolean = false>(
  options: Options<ReportReportDetailGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ReportReportDetailGetResponses,
    ReportReportDetailGetErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zReportReportDetailGetData.parseAsync(data);
    },
    url: "/v1/reports/{reportID}",
    ...options,
  });
};

/**
 * Save a new document to process
 */
export const toProcessPostToProcess = <ThrowOnError extends boolean = false>(
  options: Options<ToProcessPostToProcessData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    ToProcessPostToProcessResponses,
    ToProcessPostToProcessErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zToProcessPostToProcessData.parseAsync(data);
    },
    url: "/v1/toProcess",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a document to process
 */
export const toProcessDeleteToProcess = <ThrowOnError extends boolean = false>(
  options: Options<ToProcessDeleteToProcessData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    ToProcessDeleteToProcessResponses,
    ToProcessDeleteToProcessErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zToProcessDeleteToProcessData.parseAsync(data);
    },
    url: "/v1/toProcess/{uploadID}",
    ...options,
  });
};

/**
 * Get all webhooks
 */
export const webhookGetWebhooks = <ThrowOnError extends boolean = false>(
  options?: Options<WebhookGetWebhooksData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    WebhookGetWebhooksResponses,
    WebhookGetWebhooksErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zWebhookGetWebhooksData.parseAsync(data);
    },
    url: "/v1/webhooks",
    ...options,
  });
};

/**
 * Create a webhook
 * Sample request:
 *
 * POST /v1/webhooks
 * {
 * "EntityType": "Order",
 * "WebhookURL": "https://my.Webhook.url.com/Callback"
 * }
 */
export const webhookPostWebhook = <ThrowOnError extends boolean = false>(
  options: Options<WebhookPostWebhookData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    WebhookPostWebhookResponses,
    WebhookPostWebhookErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zWebhookPostWebhookData.parseAsync(data);
    },
    url: "/v1/webhooks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a webhook
 */
export const webhookDeleteWebhooks = <ThrowOnError extends boolean = false>(
  options: Options<WebhookDeleteWebhooksData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    WebhookDeleteWebhooksResponses,
    WebhookDeleteWebhooksErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zWebhookDeleteWebhooksData.parseAsync(data);
    },
    url: "/v1/webhooks/{webhookID}",
    ...options,
  });
};

/**
 * Refresh a webhook secret
 */
export const webhookRefreshWebhookSecret = <ThrowOnError extends boolean = false>(
  options: Options<WebhookRefreshWebhookSecretData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    WebhookRefreshWebhookSecretResponses,
    WebhookRefreshWebhookSecretErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zWebhookRefreshWebhookSecretData.parseAsync(data);
    },
    url: "/v1/webhooks/refresh/{webhookID}",
    ...options,
  });
};
