// This file is auto-generated by @hey-api/openapi-ts

import type {
  AccountGetAccountInformationResponse,
  CashbookGetCashbookResponse,
  CashbookGetCashbookEntriesResponse,
  CashbookGetCashbooksResponse,
  CashbookGetCashbookHistoryResponse,
  CashbookPostCashbookEntryResponse,
  DailyReceiptGetDailyReceiptBooksResponse,
  DailyReceiptGetDailyReceiptBooks2Response,
  DocumentGetDocumentsResponse,
  DocumentGetDocumentResponse,
  EinvoiceGetOrdersResponse,
  EinvoiceGetOrderResponse,
  MiscGetCompanySearchResponse,
  OrderGetOrdersResponse,
  OrderGetOrderResponse,
  OrderGetDeletedResponse,
  PartyGetPartyResponse,
  PartyGetPartiesResponse,
  PeppolGetInboxResponse,
  ProductGetProductResponse,
  ProductGetProductsResponse,
} from "./types.gen";

const accountInformationPartySchemaResponseTransformer = (data: any) => {
  if (data.BookYearStart) {
    data.BookYearStart = new Date(data.BookYearStart);
  }
  if (data.LastModified) {
    data.LastModified = new Date(data.LastModified);
  }
  if (data.Created) {
    data.Created = new Date(data.Created);
  }
  if (data.GLAccountCode) {
    data.GLAccountCode = BigInt(data.GLAccountCode.toString());
  }
  if (data.DomiciliationMandateSigningDate) {
    data.DomiciliationMandateSigningDate = new Date(data.DomiciliationMandateSigningDate);
  }
  if (data.GLDefaultExpiryOffset) {
    data.GLDefaultExpiryOffset = BigInt(data.GLDefaultExpiryOffset.toString());
  }
  return data;
};

const accountInformationSchemaResponseTransformer = (data: any) => {
  if (data.Companies) {
    data.Companies = data.Companies.map((item: any) => {
      return accountInformationPartySchemaResponseTransformer(item);
    });
  }
  return data;
};

export const accountGetAccountInformationResponseTransformer = async (
  data: any
): Promise<AccountGetAccountInformationResponse> => {
  data = accountInformationSchemaResponseTransformer(data);
  return data;
};

const cashbookModelSchemaResponseTransformer = (data: any) => {
  if (data.CreationDate) {
    data.CreationDate = new Date(data.CreationDate);
  }
  if (data.LastEntryDate) {
    data.LastEntryDate = new Date(data.LastEntryDate);
  }
  return data;
};

export const cashbookGetCashbookResponseTransformer = async (
  data: any
): Promise<CashbookGetCashbookResponse> => {
  data = cashbookModelSchemaResponseTransformer(data);
  return data;
};

const cashbookEntrySchemaResponseTransformer = (data: any) => {
  if (data.TransactionDate) {
    data.TransactionDate = new Date(data.TransactionDate);
  }
  return data;
};

const pageResultCashbookEntrySchemaResponseTransformer = (data: any) => {
  if (data.Items) {
    data.Items = data.Items.map((item: any) => {
      return cashbookEntrySchemaResponseTransformer(item);
    });
  }
  if (data.Count) {
    data.Count = BigInt(data.Count.toString());
  }
  return data;
};

export const cashbookGetCashbookEntriesResponseTransformer = async (
  data: any
): Promise<CashbookGetCashbookEntriesResponse> => {
  data = pageResultCashbookEntrySchemaResponseTransformer(data);
  return data;
};

export const cashbookGetCashbooksResponseTransformer = async (
  data: any
): Promise<CashbookGetCashbooksResponse> => {
  data = data.map((item: any) => {
    return cashbookModelSchemaResponseTransformer(item);
  });
  return data;
};

export const cashbookGetCashbookHistoryResponseTransformer = async (
  data: any
): Promise<CashbookGetCashbookHistoryResponse> => {
  data = pageResultCashbookEntrySchemaResponseTransformer(data);
  return data;
};

export const cashbookPostCashbookEntryResponseTransformer = async (
  data: any
): Promise<CashbookPostCashbookEntryResponse> => {
  data = cashbookEntrySchemaResponseTransformer(data);
  return data;
};

const cashbookSchemaResponseTransformer = (data: any) => {
  if (data.FromDate) {
    data.FromDate = new Date(data.FromDate);
  }
  return data;
};

const dailyReceiptBookModelResponseModelSchemaResponseTransformer = (data: any) => {
  if (data.Cashbooks) {
    data.Cashbooks = data.Cashbooks.map((item: any) => {
      return cashbookSchemaResponseTransformer(item);
    });
  }
  return data;
};

export const dailyReceiptGetDailyReceiptBooksResponseTransformer = async (
  data: any
): Promise<DailyReceiptGetDailyReceiptBooksResponse> => {
  data = dailyReceiptBookModelResponseModelSchemaResponseTransformer(data);
  return data;
};

export const dailyReceiptGetDailyReceiptBooks2ResponseTransformer = async (
  data: any
): Promise<DailyReceiptGetDailyReceiptBooks2Response> => {
  data = dailyReceiptBookModelResponseModelSchemaResponseTransformer(data);
  return data;
};

const documentApiViewSchemaResponseTransformer = (data: any) => {
  if (data.DocumentDate) {
    data.DocumentDate = new Date(data.DocumentDate);
  }
  if (data.CreationDate) {
    data.CreationDate = new Date(data.CreationDate);
  }
  return data;
};

const pageResultDocumentApiViewSchemaResponseTransformer = (data: any) => {
  if (data.Items) {
    data.Items = data.Items.map((item: any) => {
      return documentApiViewSchemaResponseTransformer(item);
    });
  }
  if (data.Count) {
    data.Count = BigInt(data.Count.toString());
  }
  return data;
};

export const documentGetDocumentsResponseTransformer = async (
  data: any
): Promise<DocumentGetDocumentsResponse> => {
  data = pageResultDocumentApiViewSchemaResponseTransformer(data);
  return data;
};

export const documentGetDocumentResponseTransformer = async (
  data: any
): Promise<DocumentGetDocumentResponse> => {
  data = documentApiViewSchemaResponseTransformer(data);
  return data;
};

const partySchemaResponseTransformer = (data: any) => {
  if (data.BookYearStart) {
    data.BookYearStart = new Date(data.BookYearStart);
  }
  if (data.LastModified) {
    data.LastModified = new Date(data.LastModified);
  }
  if (data.Created) {
    data.Created = new Date(data.Created);
  }
  if (data.GLAccountCode) {
    data.GLAccountCode = BigInt(data.GLAccountCode.toString());
  }
  if (data.DomiciliationMandateSigningDate) {
    data.DomiciliationMandateSigningDate = new Date(data.DomiciliationMandateSigningDate);
  }
  if (data.GLDefaultExpiryOffset) {
    data.GLDefaultExpiryOffset = BigInt(data.GLDefaultExpiryOffset.toString());
  }
  return data;
};

const documentDeliveryDetailsSchemaResponseTransformer = (data: any) => {
  if (data.DocumentRefusedDate) {
    data.DocumentRefusedDate = new Date(data.DocumentRefusedDate);
  }
  if (data.DocumentDeliveryDate) {
    data.DocumentDeliveryDate = new Date(data.DocumentDeliveryDate);
  }
  return data;
};

const orderMessageSchemaResponseTransformer = (data: any) => {
  if (data.CreationDate) {
    data.CreationDate = new Date(data.CreationDate);
  }
  return data;
};

const timezoneInfoSchemaResponseTransformer = (data: any) => {
  if (data.DateTime) {
    data.DateTime = new Date(data.DateTime);
  }
  return data;
};

const eInvoiceSignatureModelSchemaResponseTransformer = (data: any) => {
  if (data.DateTimeInfo) {
    data.DateTimeInfo = timezoneInfoSchemaResponseTransformer(data.DateTimeInfo);
  }
  return data;
};

const orderSchemaResponseTransformer = (data: any) => {
  if (data.Customer) {
    data.Customer = partySchemaResponseTransformer(data.Customer);
  }
  if (data.Supplier) {
    data.Supplier = partySchemaResponseTransformer(data.Supplier);
  }
  if (data.CounterParty) {
    data.CounterParty = partySchemaResponseTransformer(data.CounterParty);
  }
  if (data.OrderDate) {
    data.OrderDate = new Date(data.OrderDate);
  }
  if (data.ExpiryDate) {
    data.ExpiryDate = new Date(data.ExpiryDate);
  }
  if (data.LastModified) {
    data.LastModified = new Date(data.LastModified);
  }
  if (data.Created) {
    data.Created = new Date(data.Created);
  }
  if (data.PaymentDiscountDate) {
    data.PaymentDiscountDate = new Date(data.PaymentDiscountDate);
  }
  if (data.PaidDate) {
    data.PaidDate = new Date(data.PaidDate);
  }
  if (data.PeriodFrom) {
    data.PeriodFrom = new Date(data.PeriodFrom);
  }
  if (data.PeriodTill) {
    data.PeriodTill = new Date(data.PeriodTill);
  }
  if (data.LastReminder) {
    data.LastReminder = new Date(data.LastReminder);
  }
  if (data.DeliveryDate) {
    data.DeliveryDate = new Date(data.DeliveryDate);
  }
  if (data.CurrentDocumentDeliveryDetails) {
    data.CurrentDocumentDeliveryDetails = documentDeliveryDetailsSchemaResponseTransformer(
      data.CurrentDocumentDeliveryDetails
    );
  }
  if (data.Messages) {
    data.Messages = data.Messages.map((item: any) => {
      return orderMessageSchemaResponseTransformer(item);
    });
  }
  if (data.TaxPointDate) {
    data.TaxPointDate = new Date(data.TaxPointDate);
  }
  if (data.Signature) {
    data.Signature = eInvoiceSignatureModelSchemaResponseTransformer(data.Signature);
  }
  return data;
};

const pageResultOrderSchemaResponseTransformer = (data: any) => {
  if (data.Items) {
    data.Items = data.Items.map((item: any) => {
      return orderSchemaResponseTransformer(item);
    });
  }
  if (data.Count) {
    data.Count = BigInt(data.Count.toString());
  }
  return data;
};

export const einvoiceGetOrdersResponseTransformer = async (
  data: any
): Promise<EinvoiceGetOrdersResponse> => {
  data = pageResultOrderSchemaResponseTransformer(data);
  return data;
};

export const einvoiceGetOrderResponseTransformer = async (
  data: any
): Promise<EinvoiceGetOrderResponse> => {
  data = orderSchemaResponseTransformer(data);
  return data;
};

const companySearchResultItemSchemaResponseTransformer = (data: any) => {
  if (data.StartDate) {
    data.StartDate = new Date(data.StartDate);
  }
  return data;
};

const companySearchResultSchemaResponseTransformer = (data: any) => {
  if (data.Items) {
    data.Items = data.Items.map((item: any) => {
      return companySearchResultItemSchemaResponseTransformer(item);
    });
  }
  return data;
};

export const miscGetCompanySearchResponseTransformer = async (
  data: any
): Promise<MiscGetCompanySearchResponse> => {
  data = companySearchResultSchemaResponseTransformer(data);
  return data;
};

export const orderGetOrdersResponseTransformer = async (
  data: any
): Promise<OrderGetOrdersResponse> => {
  data = pageResultOrderSchemaResponseTransformer(data);
  return data;
};

export const orderGetOrderResponseTransformer = async (
  data: any
): Promise<OrderGetOrderResponse> => {
  data = orderSchemaResponseTransformer(data);
  return data;
};

export const orderGetDeletedResponseTransformer = async (
  data: any
): Promise<OrderGetDeletedResponse> => {
  data = pageResultOrderSchemaResponseTransformer(data);
  return data;
};

export const partyGetPartyResponseTransformer = async (
  data: any
): Promise<PartyGetPartyResponse> => {
  data = partySchemaResponseTransformer(data);
  return data;
};

const pageResultPartySchemaResponseTransformer = (data: any) => {
  if (data.Items) {
    data.Items = data.Items.map((item: any) => {
      return partySchemaResponseTransformer(item);
    });
  }
  if (data.Count) {
    data.Count = BigInt(data.Count.toString());
  }
  return data;
};

export const partyGetPartiesResponseTransformer = async (
  data: any
): Promise<PartyGetPartiesResponse> => {
  data = pageResultPartySchemaResponseTransformer(data);
  return data;
};

const inboxGetResultItemSchemaResponseTransformer = (data: any) => {
  if (data.CreationDate) {
    data.CreationDate = new Date(data.CreationDate);
  }
  return data;
};

const inboxGetResultSchemaResponseTransformer = (data: any) => {
  if (data.InboxItems) {
    data.InboxItems = data.InboxItems.map((item: any) => {
      return inboxGetResultItemSchemaResponseTransformer(item);
    });
  }
  return data;
};

export const peppolGetInboxResponseTransformer = async (
  data: any
): Promise<PeppolGetInboxResponse> => {
  data = inboxGetResultSchemaResponseTransformer(data);
  return data;
};

const productSchemaResponseTransformer = (data: any) => {
  if (data.Created) {
    data.Created = new Date(data.Created);
  }
  if (data.LastModified) {
    data.LastModified = new Date(data.LastModified);
  }
  if (data.ChildProducts) {
    data.ChildProducts = data.ChildProducts.map((item: any) => {
      return productSchemaResponseTransformer(item);
    });
  }
  return data;
};

export const productGetProductResponseTransformer = async (
  data: any
): Promise<ProductGetProductResponse> => {
  data = productSchemaResponseTransformer(data);
  return data;
};

const pageResultProductSchemaResponseTransformer = (data: any) => {
  if (data.Items) {
    data.Items = data.Items.map((item: any) => {
      return productSchemaResponseTransformer(item);
    });
  }
  if (data.Count) {
    data.Count = BigInt(data.Count.toString());
  }
  return data;
};

export const productGetProductsResponseTransformer = async (
  data: any
): Promise<ProductGetProductsResponse> => {
  data = pageResultProductSchemaResponseTransformer(data);
  return data;
};
